/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 24185848-664f-4661-9ba5-de2ed5c684e6

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines a Brockian circle embedding on the 5-cycle using the 5th root of unity.
It defines `ω` as the 5th root of unity, `emb` as the embedding function, and `dist` as the Euclidean distance.
It proves that the rotation `a ↦ a + 1` is an isometry with respect to this distance.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators

#check IsCyclotomicExtension.zeta

#check Complex.normSq

#check Complex.re
#check Real.sqrt
#synth Norm ℂ

/-
Defining Complex.zeta and Complex.abs as helpers. Complex.zeta n is exp(2πi/n). Complex.abs z is the norm of z.
-/
/-- Helper: Define Complex.zeta since it is missing -/
noncomputable def Complex.zeta (n : ℕ) : ℂ := Complex.exp (2 * Real.pi * Complex.I / n)

/-- Helper: Define Complex.abs as norm since it is missing -/
noncomputable def Complex.abs (z : ℂ) : ℝ := ‖z‖

/-
Definitions of ω, emb, and dist. ω is defined as Complex.zeta 5. emb maps a in Fin 5 to ω^a. dist is the Euclidean distance between embeddings.
-/
/-- The canonical primitive 5th root of unity in `ℂ`. -/
noncomputable def ω : ℂ := Complex.zeta 5

/-- Embedding of the 5-cycle into the unit circle: `a ↦ ω^(a.val)`. -/
noncomputable def emb (a : Fin 5) : ℂ := ω ^ (a.val)

/-- Euclidean distance in the embedding. -/
noncomputable def dist (a b : Fin 5) : ℝ := Complex.abs (emb a - emb b)

/-
Lemma: ω is not zero. Proof uses Complex.zeta_ne_zero.
-/
lemma ω_ne_zero : (ω : ℂ) ≠ 0 := by
  exact Complex.exp_ne_zero _

/-
Lemma: The absolute value of ω is 1. Proof uses the definition of ω and the norm of the complex exponential.
-/
lemma abs_ω : Complex.abs ω = 1 := by
  simp [ω, Complex.zeta, Complex.abs, Complex.norm_exp]

/-
Lemma: The absolute value of ω * z is equal to the absolute value of z. Proof uses the multiplicative property of absolute value and the fact that |ω| = 1.
-/
lemma abs_mul_ω (z : ℂ) : Complex.abs (ω * z) = Complex.abs z := by
  convert Complex.norm_mul ( ω : ℂ ) z using 1;
  erw [ show ‖ω‖ = 1 from by simpa [ Complex.norm_exp ] using abs_ω ] ; norm_num;
  rfl

/-
Lemma: emb(a+1) = ω * emb(a). Proof by cases on a.
-/
/-- The key rotation step on the 5-cycle: emb(a+1) = ω * emb(a). -/
lemma emb_succ (a : Fin 5) : emb (a + 1) = ω * emb a := by
  fin_cases a <;> simp +decide [ pow_succ', ← mul_assoc ];
  · unfold emb; norm_num [ pow_succ' ] ;
  · unfold emb; norm_num [ mul_comm ω, pow_succ' ] ;
  · unfold emb; ring;
    exact?;
  · unfold emb; ring; norm_num [ pow_succ, Complex.exp_ne_zero ] ;
    ring;
  · unfold emb;
    simp +decide [ ← pow_succ' ];
    rw [ show ω = Complex.exp ( 2 * Real.pi * Complex.I / 5 ) by rfl, ← Complex.exp_nat_mul, mul_comm ] ; norm_num

/-
Theorem: dist(a+1, b+1) = dist(a, b). Proof uses the definition of distance, the rotation property, and the fact that multiplication by ω preserves absolute value.
-/
/-- Rotation isometry: shifting both points by +1 preserves distance. -/
theorem dist_succ_succ (a b : Fin 5) : dist (a + 1) (b + 1) = dist a b := by
  unfold _root_.dist; ring;
  -- We can factor out ω from the difference, giving us ω * (emb a - emb b).
  have h_factor : emb (a + 1) - emb (b + 1) = ω * (emb a - emb b) := by
    rw [ emb_succ, emb_succ, mul_sub ];
  rw [ h_factor, abs_mul_ω ]
