/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6cd44807-389a-4a3a-91d2-6550b9a79936
-/

/-
Formalization of the Brockian Magnum Opus (V2) architecture for a conditional Goldbach proof.
Includes definitions of the golden ratio, pentagon scaffolding, Goldbach representation count,
Spectral Model structure, and the main conditional theorems deriving Goldbach from the model.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the golden ratio φ.
-/
noncomputable def BrockianMagnumOpus.φ : ℝ := (1 + Real.sqrt 5) / 2

/-
Definition of the conjugate golden ratio ψ.
-/
noncomputable def BrockianMagnumOpus.ψ : ℝ := (1 - Real.sqrt 5) / 2

/-
φ is positive.
-/
lemma BrockianMagnumOpus.φ_pos : 0 < BrockianMagnumOpus.φ := by
  unfold BrockianMagnumOpus.φ
  have hs : 0 < Real.sqrt 5 := by positivity
  nlinarith

/-
φ is not zero.
-/
lemma BrockianMagnumOpus.φ_ne_zero : (BrockianMagnumOpus.φ : ℝ) ≠ 0 := ne_of_gt BrockianMagnumOpus.φ_pos

/-
The golden identity φ^2 = φ + 1.
-/
theorem BrockianMagnumOpus.golden_identity : BrockianMagnumOpus.φ ^ 2 = BrockianMagnumOpus.φ + 1 := by
  -- robust algebraic proof
  unfold BrockianMagnumOpus.φ
  field_simp
  ring_nf
  -- (sqrt 5)^2 = 5
  rw [Real.sq_sqrt (by norm_num)]
  ring

/-
The reciprocal of φ is φ - 1.
-/
theorem BrockianMagnumOpus.golden_reciprocal : 1 / BrockianMagnumOpus.φ = BrockianMagnumOpus.φ - 1 := by
  -- Multiply both sides by φ and use φ^2 = φ + 1.
  apply (div_eq_iff BrockianMagnumOpus.φ_ne_zero).2
  have h := BrockianMagnumOpus.golden_identity
  -- goal: 1 = (φ - 1) * φ
  nlinarith [h]

/-
Vertices of a regular pentagon as complex numbers.
-/
noncomputable def BrockianMagnumOpus.pentagonVertex (k : Fin 5) : ℂ :=
  Complex.exp (2 * Real.pi * Complex.I * (k : ℝ) / 5)

/-
Distance between two vertices of the pentagon.
-/
noncomputable def BrockianMagnumOpus.pentagonDistance (j k : Fin 5) : ℝ :=
  ‖BrockianMagnumOpus.pentagonVertex j - BrockianMagnumOpus.pentagonVertex k‖

/-
Goldbach representation count defined as a finite cardinality.
-/
/-- Goldbach representation count:
number of primes `p ≤ n/2` such that `n - p` is prime. -/
def BrockianMagnumOpus.goldbachReps (n : ℕ) : ℕ :=
  ((Finset.range (n / 2 + 1)).filter (fun p => Nat.Prime p ∧ Nat.Prime (n - p))).card

/-
If goldbachReps n ≥ 1, then n is the sum of two primes.
-/
/-- If the representation count is ≥ 1, then a Goldbach decomposition exists. -/
lemma BrockianMagnumOpus.goldbach_rep_exists {n : ℕ} (h : BrockianMagnumOpus.goldbachReps n ≥ 1) :
    ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ p + q = n := by
      -- If the cardinality of the set of primes p ≤ n/2 such that n - p is also prime is at least 1, then there exists at least one such prime p.
      obtain ⟨p, hp⟩ : ∃ p ∈ Finset.filter (fun p => Nat.Prime p ∧ Nat.Prime (n - p)) (Finset.range (n / 2 + 1)), True := by
        exact Exists.elim ( Finset.card_pos.mp h ) fun p hp => ⟨ p, hp, trivial ⟩;
      grind

/-
Helper lemma: |x - m| ≤ e implies m - e ≤ x.
-/
/-- The fundamental inequality extracted from an `abs` bound:
`|x - m| ≤ e` ⇒ `m - e ≤ x`. -/
lemma BrockianMagnumOpus.le_of_abs_sub_le {x m e : ℝ} (h : |x - m| ≤ e) : m - e ≤ x := by
  linarith [ abs_le.mp h ]

/-
Definition of the Goldbach property for a number n.
-/
/-- Goldbach statement in the standard ∃p q form. -/
def BrockianMagnumOpus.Goldbach (n : ℕ) : Prop :=
  ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ p + q = n

#check Even

/-
Structure defining a spectral model for Goldbach representations (corrected Nat.Even to Even).
-/
/-- A Brockian “spectral model” is any theory that predicts Goldbach reps via:
`|G(n) - Main(n)| ≤ Err(n)`, with Main eventually bounded away from 0. -/
structure BrockianMagnumOpus.SpectralModel where
  mainTerm : ℕ → ℝ
  errTerm  : ℕ → ℝ
  err_nonneg : ∀ n, 0 ≤ errTerm n
  approx :
    ∀ n, n > 2 → Even n →
      |(BrockianMagnumOpus.goldbachReps n : ℝ) - mainTerm n| ≤ errTerm n
  /-- A *usable* margin hypothesis: beyond N₀, mainTerm dominates error by ≥ 1/2. -/
  N₀ : ℕ
  main_minus_err_ge_half :
    ∀ n, n > N₀ → (1/2 : ℝ) ≤ mainTerm n - errTerm n

/-
Theorem: A valid spectral model implies Goldbach reps ≥ 1 for large enough n (using Even).
-/
theorem BrockianMagnumOpus.goldbachReps_ge_one_of_model (M : BrockianMagnumOpus.SpectralModel) :
    ∀ n, n > max 2 M.N₀ → Even n → BrockianMagnumOpus.goldbachReps n ≥ 1 := by
      intros n hn hn_even
      have h_error : abs ((BrockianMagnumOpus.goldbachReps n : ℝ) - M.mainTerm n) ≤ M.errTerm n := by
        exact M.approx n ( by linarith [ le_max_left 2 M.N₀ ] ) hn_even;
      exact Nat.cast_pos.mp ( by linarith [ abs_le.mp h_error, M.main_minus_err_ge_half n ( lt_of_le_of_lt ( le_max_right _ _ ) hn ) ] : ( 0 : ℝ ) < BrockianMagnumOpus.goldbachReps n )

/-
Main Theorem: Goldbach holds if a spectral model exists and small cases are verified (using Even).
-/
theorem BrockianMagnumOpus.goldbach_from_spectral_model
    (M : BrockianMagnumOpus.SpectralModel)
    (h_small :
      ∀ n, n ≤ max 2 M.N₀ → n > 2 → Even n → BrockianMagnumOpus.Goldbach n) :
    ∀ n, n > 2 → Even n → BrockianMagnumOpus.Goldbach n := by
  intro n hn2 hEven
  by_cases hcase : n ≤ max 2 M.N₀
  · exact h_small n hcase hn2 hEven
  · have hnlarge : n > max 2 M.N₀ := lt_of_not_ge hcase
    have hrep : BrockianMagnumOpus.goldbachReps n ≥ 1 :=
      BrockianMagnumOpus.goldbachReps_ge_one_of_model M n hnlarge hEven
    -- reps ≥ 1 ⇒ ∃ primes summing to n
    rcases BrockianMagnumOpus.goldbach_rep_exists (n := n) hrep with ⟨p, q, hp, hq, hpq⟩
    exact ⟨p, q, hp, hq, hpq⟩
