/-
  The bounded-perturbation Kato-Rellich theorem for densely defined
  essentially self-adjoint operators.  The graph-shear and adjoint-domain
  arguments were generated by Harmonic project 7bfd75f8 and independently
  checked by AXLE before this extraction into the canonical namespace.
-/
import Brockian.WeylKatoUnbounded
import Brockian.WeylUpstream

namespace Brockian.Weyl.KatoRellich

open Brockian.Weyl.Operator
open Brockian.Weyl.KatoUnbounded

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace Complex H]
  [CompleteSpace H]

/-- Adding a bounded operator to the second graph coordinate is a
homeomorphism. -/
noncomputable def graphShear (B : H →L[Complex] H) : H × H ≃ₜ H × H where
  toFun p := (p.1, B p.1 + p.2)
  invFun p := (p.1, p.2 - B p.1)
  left_inv p := by ext <;> simp
  right_inv p := by ext <;> simp
  continuous_toFun := continuous_fst.prodMk
    (B.continuous.comp continuous_fst |>.add continuous_snd)
  continuous_invFun := continuous_fst.prodMk
    (continuous_snd.sub (B.continuous.comp continuous_fst))

/-- The graph of `T + B` is the bounded graph shear of the graph of `T`. -/
theorem graph_perturb_eq_shear_image (T : H →ₗ.[Complex] H)
    (B : H →L[Complex] H) :
    ((perturb T B).graph : Set (H × H)) =
      graphShear B '' (T.graph : Set (H × H)) := by
  ext p
  constructor
  · intro hp
    change p ∈ (perturb T B).graph at hp
    rw [LinearPMap.mem_graph_iff] at hp
    obtain ⟨x, hxp, hact⟩ := hp
    have hxpdom : p.1 ∈ (perturb T B).domain := hxp ▸ x.2
    have hxT : p.1 ∈ T.domain := by rwa [perturb_domain T B] at hxpdom
    let xT : T.domain := ⟨p.1, hxT⟩
    refine ⟨(p.1, T xT), T.mem_graph xT, ?_⟩
    apply Prod.ext
    · rfl
    · change B p.1 + T xT = p.2
      rw [← hact, perturb_apply]
      congr 1
      · exact congrArg B hxp.symm
      · exact congrArg T.toFun (Subtype.ext hxp.symm)
  · rintro ⟨q, hq, rfl⟩
    change q ∈ T.graph at hq
    change graphShear B q ∈ (perturb T B).graph
    rw [LinearPMap.mem_graph_iff] at hq ⊢
    obtain ⟨x, hxq, hact⟩ := hq
    refine ⟨⟨q.1, ?_⟩, rfl, ?_⟩
    · rw [perturb_domain]
      simpa [← hxq] using x.2
    · change B q.1 + T ⟨q.1, by simpa [← hxq] using x.2⟩ = B q.1 + q.2
      congr 1
      simpa [← hxq] using hact

/-- Closure commutes with adding a bounded operator. -/
theorem closure_perturb_eq_perturb_closure
    {T : H →ₗ.[Complex] H} (hT : IsSymmetric T)
    (hd : Dense (T.domain : Set H)) (B : H →L[Complex] H) :
    (perturb T B).closure = perturb T.closure B := by
  have hTcl : T.IsClosable := Brockian.Weyl.Closure.symmetric_isClosable hT hd
  have hgraph : (perturb T B).graph.topologicalClosure =
      (perturb T.closure B).graph := by
    apply SetLike.coe_injective
    rw [Submodule.topologicalClosure_coe, graph_perturb_eq_shear_image,
      ← Homeomorph.image_closure, ← Submodule.topologicalClosure_coe,
      hTcl.graph_closure_eq_closure_graph, graph_perturb_eq_shear_image]
  have hTp : (perturb T B).IsClosable := ⟨perturb T.closure B, hgraph⟩
  apply LinearPMap.eq_of_eq_graph
  rw [← hTp.graph_closure_eq_closure_graph]
  exact hgraph

/-- A bounded self-adjoint perturbation of a self-adjoint operator is
self-adjoint, even when the first operator is unbounded. -/
theorem isSelfAdjoint_perturb
    {A : H →ₗ.[Complex] H} {B : H →L[Complex] H}
    (hA : IsSelfAdjoint A) (hB : IsSelfAdjoint B) :
    IsSelfAdjoint (perturb A B) := by
  rw [LinearPMap.isSelfAdjoint_def]
  apply le_antisymm
  · refine ⟨?_, ?_⟩
    · intro y hy
      let yAdj : (perturb A B).adjoint.domain := ⟨y, hy⟩
      have hpDense : Dense ((perturb A B).domain : Set H) :=
        perturb_dense_domain B hA.dense_domain
      have hyAadj : y ∈ A.adjoint.domain := by
        apply LinearPMap.mem_adjoint_domain_of_exists
        refine ⟨(perturb A B).adjoint yAdj - B y, ?_⟩
        intro x
        let xp : (perturb A B).domain :=
          ⟨(x : H), by rw [perturb_domain]; exact x.2⟩
        have hpform := LinearPMap.adjoint_isFormalAdjoint hpDense yAdj xp
        have hBform : inner Complex (B y) (x : H) =
            inner Complex (y : H) (B (x : H)) := by
          rw [← B.adjoint_inner_left, hB.adjoint_eq]
        calc
          inner Complex ((perturb A B).adjoint yAdj - B y) (x : H) =
              inner Complex (y : H) ((perturb A B) xp) -
                inner Complex (B y) (x : H) := by
                  rw [inner_sub_left, hpform]
          _ = inner Complex (y : H) (B (x : H) + A x) -
                inner Complex (B y) (x : H) := by
                  rw [perturb_apply]
                  rfl
          _ = inner Complex (y : H) (A x) := by
                  rw [inner_add_right, hBform]
                  abel
      have hyA : y ∈ A.domain := by
        rw [← LinearPMap.isSelfAdjoint_def.mp hA]
        exact hyAadj
      simpa [perturb_domain] using hyA
    · intro x y hxy
      have hpDense : Dense ((perturb A B).domain : Set H) :=
        perturb_dense_domain B hA.dense_domain
      have hpSymm : IsSymmetric (perturb A B) := perturb_isSymmetric
        (Brockian.Weyl.Extension.isSymmetric_of_le_adjoint hA.dense_domain
          (by rw [LinearPMap.isSelfAdjoint_def.mp hA])) hB
      exact ((Brockian.Weyl.Closure.symmetric_le_adjoint hpSymm hpDense).2
        hxy.symm).symm
  · have hpDense : Dense ((perturb A B).domain : Set H) :=
      perturb_dense_domain B hA.dense_domain
    have hpSymm : IsSymmetric (perturb A B) := perturb_isSymmetric
      (Brockian.Weyl.Extension.isSymmetric_of_le_adjoint hA.dense_domain
        (by rw [LinearPMap.isSelfAdjoint_def.mp hA])) hB
    exact Brockian.Weyl.Closure.symmetric_le_adjoint hpSymm hpDense

/-- **Bounded Kato-Rellich.** A bounded self-adjoint perturbation preserves
essential self-adjointness of a densely defined symmetric core. -/
theorem essentiallySelfAdjoint_bounded_perturbation
    {T : H →ₗ.[Complex] H} {B : H →L[Complex] H}
    (hT : IsSymmetric T) (hd : Dense (T.domain : Set H))
    (hESA : EssentiallySelfAdjoint T) (hB : IsSelfAdjoint B) :
    EssentiallySelfAdjoint (perturb T B) := by
  have hpSymm : IsSymmetric (perturb T B) := perturb_isSymmetric hT hB
  have hpDense : Dense ((perturb T B).domain : Set H) :=
    perturb_dense_domain B hd
  apply (Brockian.Weyl.Upstream.essentiallySelfAdjoint_iff_closure_isSelfAdjoint
    hpSymm hpDense).2
  rw [closure_perturb_eq_perturb_closure hT hd B]
  exact isSelfAdjoint_perturb
    (Brockian.Weyl.ClosedShiftedRanges.closure_isSelfAdjoint_of_essentiallySelfAdjoint
      hT hd hESA) hB

end Brockian.Weyl.KatoRellich
