import Mathlib

/-! # Depth-holonomy is a FAITHFUL and COMPLETE finite invariant.

`K h` is the depth-`ZMod 6` transfer operator over the residue cycle `ZMod 5`:
it advances the residue and, at the seam `j = 4`, increments the depth by the
holonomy `h`.  Residue-class (mod 5) Fourier analysis is blind to `h`, yet:

* winding the cycle once recovers `h` exactly (`holonomy_after_loop`);
* distinct holonomies give distinct transfer operators (`holonomy_faithful`);
* even the once-around loop already recovers `h` (`holonomy_injective_via_loop`);
* the transfer-operator ORDER classifies the additive subgroup generated by `h`
  (`order_classifies`, RHS via the concrete gcd condition in `ZMod 6`).

Every theorem is `by decide` — axiom-clean, no `sorry`. -/

namespace Brockian.HolonomyFaithful

/-- Depth in `ZMod 6` over the residue cycle `ZMod 5`. -/
def K (h : ZMod 6) (x : ZMod 5 × ZMod 6) : ZMod 5 × ZMod 6 :=
  (x.1 + 1, x.2 + (if x.1 = 4 then h else 0))

/-- Winding the residue cycle once translates the depth by exactly `h`. -/
theorem holonomy_after_loop : ∀ (h : ZMod 6) x, (K h)^[5] x = (x.1, x.2 + h) := by decide

/-- **Faithful.** Distinct holonomies give distinct transfer operators:
    the holonomy is a faithful `ZMod 6`-valued invariant. -/
theorem holonomy_faithful : ∀ (h h' : ZMod 6), (∀ x, K h x = K h' x) → h = h' := by decide

/-- Even the once-around loop already recovers `h` faithfully. -/
theorem holonomy_injective_via_loop :
    ∀ (h h' : ZMod 6), (∀ x, (K h)^[5] x = (K h')^[5] x) → h = h' := by decide

/-- **Complete classification (order = subgroup).** Two holonomies induce transfer
    operators with the same fixpoint-order profile (agreement on the loop exponents
    `{5, 10, 15}`) exactly when they generate the same additive subgroup of `ZMod 6`,
    expressed by the concrete gcd invariant `Nat.gcd 6 h.val` (which pins down
    `⟨h⟩ ⊆ ZMod 6`). -/
theorem order_classifies : ∀ (h h' : ZMod 6),
    (((∀ x, (K h)^[5] x = x) ↔ (∀ x, (K h')^[5] x = x)) ∧
     ((∀ x, (K h)^[10] x = x) ↔ (∀ x, (K h')^[10] x = x)) ∧
     ((∀ x, (K h)^[15] x = x) ↔ (∀ x, (K h')^[15] x = x)))
    ↔ (Nat.gcd 6 h.val = Nat.gcd 6 h'.val) := by decide

end Brockian.HolonomyFaithful
