/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9e0f623f-c2aa-4007-b021-1d2701b47405

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real ComplexConjugate TensorProduct
open Complex Finset MeasureTheory

inductive BZFC.BrockRay
  | E  -- Ray E: 0 mod 5
  | A  -- Ray A: 1 mod 5
  | B  -- Ray B: 2 mod 5
  | C  -- Ray C: 3 mod 5
  | D  -- Ray D: 4 mod 5
  deriving DecidableEq, Repr

def BZFC.BrockRay.residue : BZFC.BrockRay → ℕ
  | .E => 0
  | .A => 1
  | .B => 2
  | .C => 3
  | .D => 4

theorem BZFC.BrockRay.residue_le_four (r : BZFC.BrockRay) : BZFC.BrockRay.residue r ≤ 4 := by
  cases r <;> decide

theorem BZFC.BrockRay.residue_lt_five (r : BZFC.BrockRay) : BZFC.BrockRay.residue r < 5 := by
  exact Nat.lt_of_le_of_lt (BZFC.BrockRay.residue_le_four r) (by decide)

def BZFC.BrockRay.contains (r : BZFC.BrockRay) (n : ℕ) : Prop := n % 5 = BZFC.BrockRay.residue r

def BZFC.BrockRay.index (r : BZFC.BrockRay) (t : ℕ) : ℕ := BZFC.BrockRay.residue r + 5 * t

theorem BZFC.BrockRay.unique_membership (n : ℕ) : ∃! r : BZFC.BrockRay, BZFC.BrockRay.contains r n := by
  unfold BZFC.BrockRay.contains;
  have h_mod : n % 5 < 5 := Nat.mod_lt _ ( by decide ) ; interval_cases _ : n % 5 <;> simp_all +decide [ ExistsUnique ] ;
  · exact ⟨ BZFC.BrockRay.E, rfl, by rintro ( _ | _ | _ | _ | _ | y ) <;> tauto ⟩;
  · exact ⟨ BZFC.BrockRay.A, rfl, by rintro ( _ | _ | _ | _ | _ | y ) <;> tauto ⟩;
  · exact ⟨ BZFC.BrockRay.B, rfl, fun y hy => by rcases y with ( _ | _ | _ | _ | _ | y ) <;> cases hy ; trivial ⟩;
  · exact ⟨ BZFC.BrockRay.C, rfl, by rintro ( _ | _ | _ | _ | _ | y ) <;> tauto ⟩;
  · exact ⟨ BZFC.BrockRay.D, rfl, fun y hy => by rcases y with ( _ | _ | _ | _ | _ | y ) <;> cases hy ; trivial ⟩

theorem BZFC.BrockRay.index_surjective (r : BZFC.BrockRay) (n : ℕ) (h : BZFC.BrockRay.contains r n) :
    ∃ t, BZFC.BrockRay.index r t = n := by
      -- Since $r.contains n$, we have $n \equiv r.residue \pmod{5}$. Therefore, $n = r.residue + 5k$ for some integer $k$.
      obtain ⟨k, hk⟩ : ∃ k : ℕ, n = r.residue + 5 * k := by
        -- By definition of contains, we know that n % 5 = r.residue.
        have h_mod : n % 5 = r.residue := by
          -- By definition of contains, we have n % 5 = r.residue.
          apply h;
        -- By the division algorithm, since $n \mod 5 = r.residue$, we can write $n = r.residue + 5 * (n / 5)$.
        use n / 5
        linarith [Nat.mod_add_div n 5];
      -- By definition of index, we have r.index k = r.residue + 5 * k.
      use k
      simp [hk, BZFC.BrockRay.index]

def BZFC.RayIntersection (r : BZFC.BrockRay) (d : ℕ) (n : ℕ) : Prop :=
  BZFC.BrockRay.contains r n ∧ d ∣ n

def BZFC.stepSize (d : ℕ) : ℕ := Nat.lcm 5 d

theorem BZFC.step_preserves_intersection (r : BZFC.BrockRay) (d n : ℕ) :
    BZFC.RayIntersection r d n → BZFC.RayIntersection r d (n + BZFC.stepSize d) := by
  intro ⟨h_ray, h_div⟩
  constructor
  · -- Ray preservation: stepSize d ≡ 0 (mod 5)
    have : 5 ∣ BZFC.stepSize d := Nat.dvd_lcm_left 5 d
    have : BZFC.stepSize d % 5 = 0 := Nat.mod_eq_zero_of_dvd this
    unfold BZFC.BrockRay.contains at *
    calc (n + BZFC.stepSize d) % 5
        = (n % 5 + BZFC.stepSize d % 5) % 5 := by rw [Nat.add_mod]
      _ = (n % 5 + 0) % 5 := by rw [this]
      _ = n % 5 := by simp
      _ = BZFC.BrockRay.residue r := h_ray
  · -- Divisibility preservation: d ∣ stepSize d
    have : d ∣ BZFC.stepSize d := Nat.dvd_lcm_right 5 d
    exact Nat.dvd_add h_div this

abbrev BZFC.BrockAddress := Stream' BZFC.BrockRay

def BZFC.addressTerm (addr : BZFC.BrockAddress) (n : ℕ) : ℝ :=
  (BZFC.BrockRay.residue (addr n)) / (5 : ℝ) ^ (n + 1)

def BZFC.addressPrefix (addr : BZFC.BrockAddress) (depth : ℕ) : ℝ :=
  ∑ n ∈ range depth, BZFC.addressTerm addr n

def BZFC.addressValue (addr : BZFC.BrockAddress) : ℝ :=
  ∑' n : ℕ, BZFC.addressTerm addr n

theorem BZFC.addressTerm_nonneg (addr : BZFC.BrockAddress) (n : ℕ) : 
    0 ≤ BZFC.addressTerm addr n := by
  unfold BZFC.addressTerm
  positivity

theorem BZFC.addressTerm_le_geom (addr : BZFC.BrockAddress) (n : ℕ) :
    BZFC.addressTerm addr n ≤ 4 / (5 : ℝ) ^ (n + 1) := by
      -- Since the residue of any Brock Ray is at most 4, we have BZFC.BrockRay.residue (addr n) ≤ 4.
      have h_residue_le_4 : BZFC.BrockRay.residue (addr n) ≤ 4 := by
        -- Apply the fact that the residue of any Brock Ray is at most 4.
        apply BZFC.BrockRay.residue_le_four;
      -- Substitute the upper bound of the residue into the address term.
      have h_subst : BZFC.addressTerm addr n = (BZFC.BrockRay.residue (addr n)) / (5 : ℝ) ^ (n + 1) := by
        -- By definition of BZFC.addressTerm, we have BZFC.addressTerm addr n = (BZFC.BrockRay.residue (addr n)) / (5 : ℝ) ^ (n + 1).
        simp [BZFC.addressTerm];
      -- Since the residue is at most 4, we can replace it with 4 in the numerator to get the upper bound.
      rw [h_subst]
      skip
      exact div_le_div_of_nonneg_right (Nat.cast_le.mpr h_residue_le_4) (by positivity)

theorem BZFC.summable_geom_bound :
    Summable (fun n : ℕ => (4 : ℝ) / (5 : ℝ) ^ (n + 1)) := by
      -- The series $\sum_{n=0}^{\infty} \frac{4}{5^{n+1}}$ is a geometric series with common ratio $\frac{1}{5}$ and first term $\frac{4}{5}$.
      have h_geo_series : Summable (fun n : ℕ => (4 : ℝ) * (1 / 5) ^ (n + 1)) := by
        -- The series $\sum' n : ℕ, 4 * (1 / 5)^(n + 1)$ is a geometric series with common ratio $1/5$ and first term $4/5$, which converges to $4/5 / (1 - 1/5) = 1$. We can use the formula for the sum of an infinite geometric series.
        have h_geo_series : Summable (fun n : ℕ => (4 : ℝ) * (1 / 5) ^ n) := by
          -- The series $\sum_{n=0}^{\infty} \frac{4}{5^n}$ is a geometric series with ratio $\frac{1}{5}$, which is less than 1. Therefore, it converges by the geometric series test.
          apply Summable.mul_left; exact summable_geometric_of_lt_one (by norm_num) (by norm_num);
        -- By shifting the index of the summable series, we can conclude that the new series is also summable.
        have h_shift : Summable (fun n : ℕ => (4 : ℝ) * (1 / 5) ^ (n + 1)) := by
          have := h_geo_series
          convert this.mul_left ( 1 / 5 ) using 2 ; ring;
        convert h_shift using 1;
      -- Since the series $\sum_{n=0}^{\infty} \frac{4}{5^{n+1}}$ is the same as the series $\sum_{n=0}^{\infty} 4 \cdot \left(\frac{1}{5}\right)^{n+1}$, we can conclude that it is summable.
      convert h_geo_series using 1;
      -- By simplifying, we can see that the two functions are indeed equal.
      funext n; field_simp [pow_succ'];
      -- By simplifying, we can see that $5^{n+1} \cdot (1/5)^{n+1} = 1$.
      norm_num [ ← mul_pow ]

theorem BZFC.summable_addressTerm (addr : BZFC.BrockAddress) : 
    Summable (BZFC.addressTerm addr) :=
  Summable.of_nonneg_of_le (BZFC.addressTerm_nonneg addr) 
    (BZFC.addressTerm_le_geom addr) BZFC.summable_geom_bound

theorem BZFC.addressValue_in_unit_interval (addr : BZFC.BrockAddress) :
    BZFC.addressValue addr ∈ Set.Icc (0 : ℝ) 1 := by
      constructor;
      · -- The sum of non-negative terms is non-negative.
        apply tsum_nonneg; intro n; exact BZFC.addressTerm_nonneg addr n;
      · refine' le_trans ( Summable.tsum_le_tsum _ _ _ ) _;
        refine' fun n => 4 / 5 ^ ( n + 1 );
        · exact?;
        · exact?;
        · ring_nf; exact Summable.mul_right _ ( summable_geometric_of_lt_one ( by norm_num ) ( by norm_num ) ) ;
        · ring_nf; rw [ tsum_mul_right, tsum_geometric_of_lt_one ] <;> norm_num;

theorem BZFC.tendsto_addressPrefix (addr : BZFC.BrockAddress) :
    Filter.Tendsto (BZFC.addressPrefix addr) Filter.atTop (nhds (BZFC.addressValue addr)) := by
  simpa [BZFC.addressPrefix, BZFC.addressValue] using
    HasSum.tendsto_sum_nat (BZFC.summable_addressTerm addr).hasSum

abbrev D5 := DihedralGroup 5

theorem D5.card : Fintype.card D5 = 10 := by
  -- The cardinality of the dihedral group D5 is indeed 10, as it has 5 rotations and 5 reflections.
  norm_cast at *

theorem D5.rotation_order : orderOf (DihedralGroup.r 1 : D5) = 5 := by
  -- The order of the rotation $r$ in $D_5$ is 5 because $r^5 = e$.
  simp [orderOf_eq_iff]

theorem D5.reflection_order : orderOf (DihedralGroup.sr 0 : D5) = 2 := by
  -- The element sr 0 is a reflection, and its order is 2.
  simp [orderOf_eq_iff]

inductive D5.ConjClass
  | identity     -- {e}: the neutral element
  | rot1         -- {r, r⁴}: basic rotations
  | rot2         -- {r², r³}: double rotations
  | reflection   -- 5 reflections (one per ray!)
  deriving DecidableEq, Fintype

def D5.ConjClass.size : D5.ConjClass → ℕ
  | .identity => 1
  | .rot1 => 2
  | .rot2 => 2
  | .reflection => 5  -- One reflection per ray!

theorem D5.reflection_ray_correspondence : D5.ConjClass.size .reflection = 5 := rfl

theorem D5.conjClass_size_sum : 
    D5.ConjClass.size .identity + D5.ConjClass.size .rot1 + 
    D5.ConjClass.size .rot2 + D5.ConjClass.size .reflection = 10 := rfl

def D5.toConjClass : D5 → D5.ConjClass
  | DihedralGroup.r 0 => .identity
  | DihedralGroup.r 1 => .rot1
  | DihedralGroup.r 4 => .rot1
  | DihedralGroup.r 2 => .rot2
  | DihedralGroup.r 3 => .rot2
  | DihedralGroup.sr _ => .reflection

inductive D5.IrrepIndex
  | trivial     -- 1D: all → 1
  | sign        -- 1D: rot → 1, ref → -1
  | golden      -- 2D: involves φ
  | conjugate   -- 2D: conjugate of golden
  deriving DecidableEq, Fintype

def D5.IrrepIndex.dim : D5.IrrepIndex → ℕ
  | .trivial => 1
  | .sign => 1
  | .golden => 2
  | .conjugate => 2

def φ : ℝ := (1 + Real.sqrt 5) / 2

theorem GoldenRatio.phi_pos : 0 < φ := by
  unfold φ
  have : 0 < Real.sqrt 5 := Real.sqrt_pos.mpr (by norm_num : (0 : ℝ) < 5)
  linarith

theorem D5.dimension_sum : ∑ i : D5.IrrepIndex, i.dim ^ 2 = 10 := by decide

theorem GoldenRatio.phi_squared : φ ^ 2 = φ + 1 := by
  unfold φ
  have sqrt5_sq : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 5)
  field_simp; ring_nf; rw [sqrt5_sq]; ring

theorem GoldenRatio.phi_inv : φ⁻¹ = φ - 1 := by
  have : φ ≠ 0 := GoldenRatio.phi_pos.ne'
  field_simp [this]
  linarith [GoldenRatio.phi_squared]

theorem GoldenRatio.phi_minus_one : φ - 1 = φ⁻¹ := GoldenRatio.phi_inv.symm

def GoldenRatio.φ_conj : ℝ := (1 - Real.sqrt 5) / 2

theorem GoldenRatio.phi_sum : φ + GoldenRatio.φ_conj = 1 := by unfold φ GoldenRatio.φ_conj; field_simp; ring

theorem GoldenRatio.phi_prod : φ * GoldenRatio.φ_conj = -1 := by
  unfold φ GoldenRatio.φ_conj
  field_simp; ring_nf
  rw [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 5)]
  ring

theorem GoldenRatio.phi_bounds_precise : (1.6180339 : ℝ) < φ ∧ φ < (1.6180340 : ℝ) := by
  -- By definition of φ, we know that φ = (1 + Real.sqrt 5) / 2.
  have h_phi_def : φ = (1 + Real.sqrt 5) / 2 := by
    -- By definition of φ, we have φ = (1 + Real.sqrt 5) / 2.
    rw [show φ = (1 + Real.sqrt 5) / 2 from rfl];
  -- By calculating the numerical values, we can confirm that the inequalities hold.
  apply And.intro;
  · -- By calculating the numerical values, we can confirm that the inequality holds.
    nlinarith [Real.sqrt_nonneg 5, Real.sq_sqrt (show 0 ≤ 5 by norm_num)];
  · -- By calculating the numerical values, we can confirm that the inequality holds.
    nlinarith [Real.sqrt_nonneg 5, Real.sq_sqrt (show 0 ≤ 5 by norm_num)]

theorem GoldenRatio.phi_bounds : (1.618 : ℝ) < φ ∧ φ < (1.619 : ℝ) := by
  have := GoldenRatio.phi_bounds_precise
  constructor <;> linarith

theorem GoldenRatio.phi_is_pisot : 1 < φ ∧ |GoldenRatio.φ_conj| < 1 := by
  -- We'll use that φ is approximately 1.618 and φ_conj is approximately -0.618.
  have h_phi_approx : 1 < (1 + Real.sqrt 5) / 2 ∧ |(1 - Real.sqrt 5) / 2| < 1 := by
    -- We'll use that √5 is approximately 2.236 to show that (1 + √5)/2 is greater than 1 and |(1 - √5)/2| is less than 1.
    have h_sqrt5 : 2.236 < Real.sqrt 5 ∧ Real.sqrt 5 < 2.237 := by
      -- We'll use that √5 is approximately 2.236 to show that 2.236 < √5 and √5 < 2.237.
      norm_num [Real.lt_sqrt, Real.sqrt_lt];
    -- By calculating the numerical values, we can see that both inequalities hold.
    exact ⟨by linarith, by rw [abs_of_neg] <;> linarith⟩;
  -- Apply the hypothesis `h_phi_approx` to conclude the proof.
  exact h_phi_approx

def ω : ℂ := exp (2 * π * I / 5)

theorem Representation.omega_pow_five : ω ^ 5 = 1 := by
  -- By definition of exponentiation, we know that $(e^{2\pi i / 5})^5 = e^{2\pi i} = 1$.
  simp [ω, ← Complex.exp_nat_mul, mul_div_cancel₀]

theorem Representation.omega_ne_zero : ω ≠ 0 := exp_ne_zero _

theorem Representation.omega_four_eq_inv : ω ^ 4 = ω⁻¹ := by
  -- By definition of ω, we know that ω^5 = 1.
  have h_omega_pow : ω ^ 5 = 1 := by
    -- By definition of ω, we know that ω^5 = 1. This follows from the properties of the exponential function and the fact that 2πi is a full rotation in the complex plane.
    apply Representation.omega_pow_five;
  grind

theorem Representation.cos_two_pi_div_five : Real.cos (2 * π / 5) = (Real.sqrt 5 - 1) / 4 := by
  /-
  This follows from the cyclotomic polynomial Φ₅(x) = x⁴ + x³ + x² + x + 1.
  Setting x = e^(2πi/5) and taking real parts gives the result.
  Full proof requires cyclotomic polynomial theory from Mathlib.
  -/
  -- We know that $\cos(\pi/5) = \frac{1 + \sqrt{5}}{4}$.
  have h_cos_pi_5 : Real.cos (Real.pi / 5) = (1 + Real.sqrt 5) / 4 := by
    -- Let's set $x = \cos(\pi/5)$ and use known polynomial satisfied by $\cos(\pi/5)$.
    set x : ℝ := Real.cos (Real.pi / 5)
    have hx_poly : 4 * x ^ 2 - 2 * x - 1 = 0 := by
      have := Real.cos_three_mul ( Real.pi / 5 ) ; rw [ show 3 * ( Real.pi / 5 ) = Real.pi - 2 * ( Real.pi / 5 ) by ring, Real.cos_pi_sub, Real.cos_two_mul ] at this ; nlinarith [ show 0 < Real.cos ( Real.pi / 5 ) from Real.cos_pos_of_mem_Ioo ⟨ by linarith [ Real.pi_pos ], by linarith [ Real.pi_pos ] ⟩ ] ;
    nlinarith [ show 1 / 2 < Real.cos ( Real.pi / 5 ) from by nth_rw 1 [ ← Real.cos_pi_div_three ] ; exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by positivity ) ( by linarith only [ Real.pi_pos ] ) ( by linarith only [ Real.pi_pos ] ), Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ) ];
  rw [ show 2 * Real.pi / 5 = 2 * ( Real.pi / 5 ) by ring, Real.cos_two_mul, h_cos_pi_5 ] ; nlinarith [ Real.sq_sqrt ( show 0 ≤ 5 by norm_num ) ]

theorem Representation.omega_sum_eq_golden : ω + ω⁻¹ = ↑(φ - 1) := by
  -- We know that $ω = e^{2πi/5}$ and $ω^5 = 1$, so $ω + ω⁻¹ = 2 \cos(2π/5)$.
  have h_cos : ω + ω⁻¹ = 2 * Real.cos (2 * Real.pi / 5) := by
    -- By definition of ω, we have ω = e^(2πi/5).
    have hω : ω = Complex.exp (2 * Real.pi * Complex.I / 5) := by
      rfl;
    norm_num [ hω, Complex.cos, Complex.exp_neg ] ; ring;
  -- Substitute the known value of Real.cos (2 * Real.pi / 5) into the equation.
  have h_cos_val : Real.cos (2 * Real.pi / 5) = (Real.sqrt 5 - 1) / 4 := by
    exact?;
  unfold φ; norm_num [ h_cos, h_cos_val ] ; ring

def Representation.character : D5.IrrepIndex → D5.ConjClass → ℂ
  | .trivial,   _ => 1
  | .sign,      .reflection => -1
  | .sign,      _ => 1
  | .golden,    .identity   => 2
  | .golden,    .rot1       => (φ - 1 : ℝ)  -- THE GOLDEN RATIO APPEARS!
  | .golden,    .rot2       => (-φ : ℝ)
  | .golden,    .reflection => 0
  | .conjugate, .identity   => 2
  | .conjugate, .rot1       => (-φ : ℝ)
  | .conjugate, .rot2       => (φ - 1 : ℝ)
  | .conjugate, .reflection => 0

theorem Representation.golden_char_real (c : D5.ConjClass) : (Representation.character .golden c).im = 0 := by
  cases c <;> simp [Representation.character, φ]

def Representation.charInnerProduct (π₁ π₂ : D5.IrrepIndex) : ℂ :=
  (1 / 10 : ℂ) * ∑ c : D5.ConjClass, 
    (D5.ConjClass.size c : ℂ) * Representation.character π₁ c * conj (Representation.character π₂ c)

lemma Representation.sum_D5ConjClass {α : Type*} [AddCommMonoid α] (f : D5.ConjClass → α) :
    ∑ c : D5.ConjClass, f c = f .identity + f .rot1 + f .rot2 + f .reflection := by
      -- By definition of Finset.univ, we can expand the sum to include all four elements.
      have h_univ : Finset.univ = {D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection} := by
        -- Since these are the only elements in the Finset.univ, we can conclude that the Finset.univ is equal to the set containing these four elements.
        ext c
        simp [Finset.mem_univ, Finset.mem_insert, Finset.mem_singleton];
        -- Since D5.ConjClass has exactly four elements, any element c must be one of these four.
        cases c <;> tauto;
      -- Substitute Finset.univ with the set containing the four elements and then apply the associativity of addition.
      rw [h_univ]
      simp [add_assoc]

def Representation.χ (irrep : D5.IrrepIndex) (g : D5) : ℂ := Representation.character irrep (D5.toConjClass g)

theorem Representation.charInner_golden_golden : Representation.charInnerProduct .golden .golden = 1 := by
  -- Let's compute the sum of the squares of the characters for the golden irrep.
  have h_sum : ∑ c : D5.ConjClass, (D5.ConjClass.size c : ℂ) * (Representation.character D5.IrrepIndex.golden c) * (starRingEnd ℂ (Representation.character D5.IrrepIndex.golden c)) = 10 := by
    -- Let's compute each term in the sum.
    simp [D5.ConjClass.size, Representation.character];
    rw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by decide ] ; simp +decide;
    norm_num [ Complex.ext_iff, sq ] ; ring_nf ; norm_num [ Real.sqrt_eq_iff_mul_self_eq, φ ];
    ring;
  unfold Representation.charInnerProduct; aesop;

theorem Representation.charInner_golden_trivial : Representation.charInnerProduct .golden .trivial = 0 := by
  -- Let's simplify the expression for the inner product.
  simp [Representation.charInnerProduct, Representation.character];
  rw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by rfl ] ; simp +decide ; ring;
  -- Substitute the sizes of the conjugacy classes into the expression.
  simp [D5.ConjClass.size];
  -- Since multiplication is commutative, we have $2 * φ = φ * 2$.
  ring

theorem Representation.charInner_orthog (π₁ π₂ : D5.IrrepIndex) (h : π₁ ≠ π₂) :
    Representation.charInnerProduct π₁ π₂ = 0 := by
      -- By definition of D5.IrrepIndex, we can split into cases based on the values of π₁ and π₂.
      cases' π₁ with π₁_1 π₁_2;
      · -- By definition of D5.IrrepIndex, we can split into cases based on the values of π₂.
        cases' π₂ with π₂_1 π₂_2;
        · grind;
        · -- By definition of character inner product, we can compute it explicitly.
          simp [Representation.charInnerProduct];
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by decide ] ; simp +decide [ *, Finset.sum ] ; ring!;
          norm_num [ D5.ConjClass.size, Representation.character ];
        · -- By definition of irreducible representations, we know that the character of the trivial representation is 1 for all elements.
          simp [Representation.charInnerProduct];
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { .identity, .rot1, .rot2, .reflection } by decide ] ; simp +decide [ Finset.sum ] ; ring;
          unfold Representation.character; norm_num [ D5.ConjClass.size ] ;
          norm_num [ Complex.ext_iff ];
          ring;
        · unfold Representation.charInnerProduct; norm_cast;
          erw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by rfl ] ; simp +decide ;
          unfold Representation.character; norm_num [ Complex.ext_iff ] ;
          norm_num [ D5.ConjClass.size ] ; ring;
      · -- By definition of D5.IrrepIndex, we can split into cases based on the values of π₂.
        cases' π₂ with π₂_1 π₂_2;
        · -- By definition of D5.IrrepIndex, we can split into cases based on the values of π₂. Since π₁ is sign and π₂ is trivial, we need to show that the inner product is zero.
          simp [Representation.charInnerProduct];
          erw [ Representation.sum_D5ConjClass ] ; norm_num [ Representation.character ];
          norm_cast;
        · aesop;
        · unfold Representation.charInnerProduct;
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by rfl ] ; simp +decide ; ring;
          norm_num [ Representation.character ];
          norm_num [ Complex.ext_iff, D5.ConjClass.size ];
          ring;
        · unfold Representation.charInnerProduct; simp +decide ;
          erw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by decide ] ; simp +decide;
          norm_num [ Complex.ext_iff, Representation.character ];
          norm_num [ D5.ConjClass.size ] ; ring;
      · -- By definition of D5.IrrepIndex, we can split into cases based on the values of π₂.
        cases' π₂ with π₂_1 π₂_2;
        · exact?;
        · unfold Representation.charInnerProduct; norm_num [ GoldenRatio.phi_bounds ] ;
          unfold Representation.character; norm_num [ D5.ConjClass.size ] ;
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by rfl ] ; simp +decide ; ring;
        · tauto;
        · -- By definition of the character inner product, we can compute it explicitly.
          simp [Representation.charInnerProduct];
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { .identity, .rot1, .rot2, .reflection } by rfl ] ; simp +decide [ Finset.sum_range_succ, Representation.character ] ; ring;
          norm_num [ Complex.ext_iff, sq ];
          -- Substitute the sizes of the conjugacy classes and simplify the expression.
          simp [D5.ConjClass.size];
          nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ), show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ];
      · cases' π₂ with π₂_1 π₂_2;
        · unfold Representation.charInnerProduct;
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { .identity, .rot1, .rot2, .reflection } by decide ] ; simp +decide [ Representation.character ];
          unfold D5.ConjClass.size; norm_num;
          ring;
        · -- By definition of the conjugate irrep, its character is the conjugate of the golden irrep's character.
          simp [Representation.charInnerProduct];
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by decide ] ; simp +decide [ Representation.character ] ; ring!;
          norm_cast;
        · unfold Representation.charInnerProduct;
          rw [ show ( Finset.univ : Finset D5.ConjClass ) = { D5.ConjClass.identity, D5.ConjClass.rot1, D5.ConjClass.rot2, D5.ConjClass.reflection } by decide ] ; simp +decide [ Representation.character ] ; ring;
          norm_num [ Complex.ext_iff, sq ];
          -- Substitute the sizes of the conjugacy classes and simplify the expression.
          simp [D5.ConjClass.size];
          nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ), show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ];
        · tauto

structure UnitaryRep (G : Type*) [Group G] (H : Type*) 
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] where
  ρ : G →* (H ≃ₗᵢ[ℂ] H)

def UnitaryRep.toCLM {G : Type*} [Group G] {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    (rep : UnitaryRep G H) (g : G) : H →L[ℂ] H := (rep.ρ g).toContinuousLinearEquiv

theorem UnitaryRep.star_eq_inv {G : Type*} [Group G] {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (rep : UnitaryRep G H) (g : G) : star (UnitaryRep.toCLM rep g) = UnitaryRep.toCLM rep g⁻¹ := by
      have h_unitary : ∀ g : G, star (rep.toCLM g) = rep.toCLM g⁻¹ := by
        intro g
        simp [Star.star, UnitaryRep.toCLM];
        refine' ContinuousLinearMap.ext fun x => _;
        refine' ( InnerProductSpace.toDual ℂ H ).injective _;
        ext y; simp +decide [ ContinuousLinearMap.adjoint_inner_left ] ;
        have := rep.ρ g |>.inner_map_map ( ( rep.ρ g ).symm x ) y; aesop;
      exact h_unitary g

def isotypicProjector {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (rep : UnitaryRep D5 H) (irrep : D5.IrrepIndex) : H →L[ℂ] H :=
  (irrep.dim / 10 : ℂ) • ∑ g : D5, conj (Representation.χ irrep g) • UnitaryRep.toCLM rep g

def P_golden {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (rep : UnitaryRep D5 H) : H →L[ℂ] H :=
  isotypicProjector rep .golden

theorem IsotypicProjector.golden_selfAdjoint {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (rep : UnitaryRep D5 H) : IsSelfAdjoint (P_golden rep) := by
      simp [IsSelfAdjoint, P_golden, isotypicProjector];
      -- By definition of $χ$, we know that $χ(g⁻¹) = \overline{χ(g)}$ for any $g \in D5$.
      have h_char_conj : ∀ g : D5, Representation.χ .golden g⁻¹ = starRingEnd ℂ (Representation.χ .golden g) := by
        -- Since the character of the golden representation is real, conjugating it doesn't change it.
        have h_real : ∀ g : D5, (Representation.χ .golden g).im = 0 := by
          unfold Representation.χ;
          unfold Representation.character; aesop;
        -- Since the character is real, conjugating it doesn't change it. Therefore, the equality holds.
        intros g
        simp [h_real, Complex.ext_iff];
        cases g <;> simp +decide [ h_real ];
        rename_i a; fin_cases a <;> rfl;
      refine' congr_arg _ ( Finset.sum_bij ( fun g _ => g⁻¹ ) _ _ _ _ ) <;> simp +decide [ h_char_conj ];
      intro g; rw [ UnitaryRep.star_eq_inv ] ;

theorem IsotypicProjector.golden_convolution (k : D5) :
    ∑ g : D5, Representation.χ .golden g * Representation.χ .golden (g⁻¹ * k) =
    (5 : ℂ) * Representation.χ .golden k := by
  -- Since these are the only elements in the group, we can split the sum into cases based on the value of `g`.
  have h_cases : ∀ g : D5, Representation.χ D5.IrrepIndex.golden g = if g = DihedralGroup.r 0 then 2 else if g = DihedralGroup.r 1 ∨ g = DihedralGroup.r 4 then (φ - 1 : ℝ) else if g = DihedralGroup.r 2 ∨ g = DihedralGroup.r 3 then (-φ : ℝ) else 0 := by
    intro g; rcases g with ( _ | _ | _ | _ | _ | _ | g ) <;> norm_cast;
    rename_i x; fin_cases x <;> rfl;
  simp +decide only [h_cases] at *;
  rcases k with ⟨ _ | _ | _ | _ | _ | _ | k ⟩ <;> norm_num <;> norm_cast;
  all_goals simp +decide [ Finset.sum_ite, Finset.filter_eq', Finset.filter_or ] at *;
  any_goals nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ), show ( φ : ℝ ) = ( 1 + Real.sqrt 5 ) / 2 by rfl ];
  · simp +decide [ show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; ring;
    grind;
  · simp +decide [ show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; ring;
    grind;
  · rename_i k; fin_cases k <;> trivial;

theorem IsotypicProjector.golden_idempotent {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (rep : UnitaryRep D5 H) : P_golden rep * P_golden rep = P_golden rep := by
  unfold P_golden;
  -- Using the convolution property, we can rewrite the sum as:
  have h_convolution : ∑ g : D5, ∑ h : D5, (conj (Representation.χ .golden g) * conj (Representation.χ .golden h)) • (UnitaryRep.toCLM rep g * UnitaryRep.toCLM rep h) = (5 : ℂ) • ∑ k : D5, (conj (Representation.χ .golden k)) • (UnitaryRep.toCLM rep k) := by
    -- Apply the convolution property to rewrite the double sum.
    have h_convolution : ∑ g : D5, ∑ h : D5, (starRingEnd ℂ (Representation.χ .golden g) * starRingEnd ℂ (Representation.χ .golden h)) • (rep.toCLM g * rep.toCLM h) = ∑ k : D5, (∑ g : D5, starRingEnd ℂ (Representation.χ .golden g) * starRingEnd ℂ (Representation.χ .golden (g⁻¹ * k))) • rep.toCLM k := by
      have h_convolution : ∀ g : D5, ∑ h : D5, (starRingEnd ℂ (Representation.χ .golden g) * starRingEnd ℂ (Representation.χ .golden h)) • (rep.toCLM g * rep.toCLM h) = ∑ k : D5, (starRingEnd ℂ (Representation.χ .golden g) * starRingEnd ℂ (Representation.χ .golden (g⁻¹ * k))) • rep.toCLM k := by
        intro g;
        refine' Finset.sum_bij ( fun h _ => g * h ) _ _ _ _ <;> simp +decide;
        · exact fun b => ⟨ g⁻¹ * b, mul_inv_cancel_left g b ⟩;
        · intro a;
          exact ContinuousLinearMap.ext fun x => by simp +decide [ UnitaryRep.toCLM ] ;
      rw [ Finset.sum_congr rfl fun g _ => h_convolution g, Finset.sum_comm ];
      simp +decide only [sum_smul];
    -- Apply the convolution property to rewrite the inner sum.
    have h_inner_sum : ∀ k : D5, ∑ g : D5, starRingEnd ℂ (Representation.χ .golden g) * starRingEnd ℂ (Representation.χ .golden (g⁻¹ * k)) = 5 * starRingEnd ℂ (Representation.χ .golden k) := by
      have h_inner_sum : ∀ k : D5, ∑ g : D5, (Representation.χ .golden g) * (Representation.χ .golden (g⁻¹ * k)) = 5 * (Representation.χ .golden k) := by
        exact?;
      exact fun k => by simpa [ mul_comm ] using congr_arg Star.star ( h_inner_sum k ) ;
    simp_all +decide [ Finset.smul_sum, smul_smul ];
  convert congr_arg ( fun x : H →L[ℂ] H => ( 2 / 10 : ℂ ) • ( 2 / 10 : ℂ ) • x ) h_convolution using 1 <;> norm_num [ isotypicProjector ] ; ring;
  · simp +decide [ Finset.sum_mul _ _ _, Finset.mul_sum, Finset.sum_smul, smul_smul, mul_assoc, mul_comm, mul_left_comm, D5.IrrepIndex.dim ];
    norm_num [ ← mul_assoc, ← smul_assoc ];
  · norm_num [ ← smul_assoc, D5.IrrepIndex.dim ]

theorem Representation.golden_on_reflection (i : Fin 5) : 
    Representation.χ .golden (DihedralGroup.sr i) = 0 := by
  simp [Representation.χ, D5.toConjClass, Representation.character]

theorem Representation.conjugate_on_reflection (i : Fin 5) : 
    Representation.χ .conjugate (DihedralGroup.sr i) = 0 := by
  simp [Representation.χ, D5.toConjClass, Representation.character]

theorem Representation.convolution_orthog_golden_conjugate_reflection (i : ZMod 5) :
    ∑ g : D5, conj (Representation.χ .golden g) * conj (Representation.χ .conjugate (g⁻¹ * DihedralGroup.sr i)) = 0 := by
      unfold Representation.χ;
      unfold Representation.character;
      rw [ show D5.IrrepIndex.golden = D5.IrrepIndex.golden from rfl ] ; ( ( erw [ Finset.sum_eq_zero ] ; intros ; simp +decide ; ) );
      cases ‹D5› <;> simp +decide [ D5.toConjClass ]



open scoped BigOperators Real ComplexConjugate TensorProduct
open Complex Finset MeasureTheory

inductive ProofObligation where
  | functionalAnalysis : String → ProofObligation
  | numberTheory : String → ProofObligation
  | brockianConstruction : String → ProofObligation
  deriving Repr

def allObligations : List (ProofObligation × Bool) := [
  -- BZFC Layer (✓ Complete)
  (.functionalAnalysis "Pentagonal partition of ℕ", true),
  (.functionalAnalysis "Ray intersection preservation", true),
  (.functionalAnalysis "Convergent ray addresses", true),
  (.functionalAnalysis "Address values in [0,1]", true),
  
  -- Representation Theory (mostly ✓)
  (.functionalAnalysis "D₅ character table", true),
  (.functionalAnalysis "Character orthogonality", true),
  (.functionalAnalysis "Projector self-adjointness", true),
  (.functionalAnalysis "Ray-conjugacy class correspondence", true),
  (.functionalAnalysis "Projector idempotence", false),
  (.functionalAnalysis "Projector completeness", false),
  
  -- Number Theory (standard, needs formalization)
  (.numberTheory "cos(2π/5) = (√5-1)/4", false),
  (.numberTheory "Explicit formula", false),
  (.numberTheory "Functional equation", false),
  (.numberTheory "Selberg trace formula", false),
  
  -- Spiral Geometry (partial)
  (.brockianConstruction "Spiral continuity", false),
  (.brockianConstruction "Spiral-ray correspondence", false),
  (.brockianConstruction "Potential convergence", false),
  
  -- The Core (OPEN)
  (.brockianConstruction "Spectral determinant identity", false),
  (.brockianConstruction "Spec(B) = {zeros}", false),
  (.brockianConstruction "Echo-rigidity ⟺ monadicity", false)
]

def provenCount : ℕ := (allObligations.filter (·.2)).length
def openCount : ℕ := (allObligations.filter (!·.2)).length

#eval provenCount  -- 8
#eval openCount    -- 13

/-- Self-adjoint unbounded operator. -/
structure SelfAdjointUnbounded (H : Type*) 
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H] where
  A : LinearPMap ℂ H H
  selfAdjoint : A.adjoint = A

open scoped BigOperators Real ComplexConjugate TensorProduct
open Complex Finset MeasureTheory

/-- Hecke operator family. -/
structure HeckeOperatorFamily (ι : Type*) (H : Type*) 
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H] where
  T : ι → (H →L[ℂ] H)
  selfAdjoint : ∀ i, IsSelfAdjoint (T i)
  commute : ∀ i j, Commute (T i) (T j)

def IsTrivialZetaZero (s : ℂ) : Prop :=
  ∃ n : ℕ, s = -((2 : ℂ) * (n + 1 : ℕ))

def brockianSpiral (k α : ℝ) (t : ℝ) : ℂ :=
  ((k * t : ℝ) : ℂ) * exp (2 * π * I * ((Real.rpow t α : ℝ) : ℂ))

def BrockianSpiral.primeWeight (p : ℕ) : ℝ := Real.log p / p

structure BrockianSystem where
  SB : Type
  prime : Set SB
  rank : ℕ
  dimH0 : ℕ
  unitIso : Prop
  transformEquiv : Prop
  multiplicity : SB → ℕ

def BrockianSystem.IsPrime (sys : BrockianSystem) (σ : sys.SB) : Prop := σ ∈ sys.prime

class B12 (sys : BrockianSystem) : Prop where
  rank_pos : 1 ≤ sys.rank

class B3 (sys : BrockianSystem) : Prop where
  dim_ge_rank : sys.rank ≤ sys.dimH0

class B4 (sys : BrockianSystem) : Prop where
  dim_eq_one : sys.dimH0 = 1

class B0 (sys : BrockianSystem) : Prop where
  unitIso_of_rank_one : sys.rank = 1 → sys.unitIso
  equiv_of_unitIso : sys.unitIso → sys.transformEquiv
  multiplicity_one_of_unitIso : sys.unitIso → 
    ∀ σ ∈ sys.prime, sys.multiplicity σ = 1

theorem brockian_multiplicity_one (sys : BrockianSystem)
    [B0 sys] [B12 sys] [B3 sys] [B4 sys] :
    sys.transformEquiv ∧ (∀ σ ∈ sys.prime, sys.multiplicity σ = 1) := by
  have h_rank_le_dim : sys.rank ≤ sys.dimH0 := B3.dim_ge_rank
  have h_dim_eq_one : sys.dimH0 = 1 := B4.dim_eq_one
  have h_rank_le_one : sys.rank ≤ 1 := by simpa [h_dim_eq_one] using h_rank_le_dim
  have h_one_le_rank : 1 ≤ sys.rank := B12.rank_pos
  -- THE CLAMP: 1 ≤ rank ≤ 1 ⟹ rank = 1
  have h_rank_eq_one : sys.rank = 1 := Nat.le_antisymm h_rank_le_one h_one_le_rank
  have h_unit : sys.unitIso := B0.unitIso_of_rank_one h_rank_eq_one
  have h_equiv : sys.transformEquiv := B0.equiv_of_unitIso h_unit
  have h_mult : ∀ σ ∈ sys.prime, sys.multiplicity σ = 1 :=
    B0.multiplicity_one_of_unitIso h_unit
  exact ⟨h_equiv, h_mult⟩

/-- Atkin-Lehner involution. -/
structure AtkinLehnerInvolution (H : Type*) 
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] where
  W : H ≃ₗᵢ[ℂ] H
  involutive : W.trans W = LinearIsometryEquiv.refl ℂ H

/-- Level 5 covering data. -/
structure Level5CoverData (H5 H0 : Type*) 
    [NormedAddCommGroup H5] [InnerProductSpace ℂ H5] [CompleteSpace H5]
    [NormedAddCommGroup H0] [InnerProductSpace ℂ H0] [CompleteSpace H0] where
  rep : UnitaryRep D5 H5
  proj : H5 →L[ℂ] H0
  proj_invariant : ∀ g : D5, proj.comp (rep.toCLM g) = proj

theorem UnitaryRep.preserves_inner {G : Type*} [Group G] {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    (rep : UnitaryRep G H) (g : G) (x y : H) :
    inner (𝕜 := ℂ) (rep.ρ g x) (rep.ρ g y) = inner (𝕜 := ℂ) x y :=
  (rep.ρ g).inner_map_map x y

theorem selfAdjoint_spectrum_real {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H] {T : H →L[ℂ] H} (hT : IsSelfAdjoint T) :
    ∀ mu : ℂ, mu ∈ spectrum ℂ T → mu.im = 0 := by
  exact?

def BrockianSpiral.gaussianKernel (ε : ℝ) (z w : ℂ) : ℝ :=
  Real.exp (-(‖z - w‖)^2 / ε^2)

#check BZFC.BrockRay.ofNat

theorem Representation.character_is_real (irrep : D5.IrrepIndex) (c : D5.ConjClass) :
    (Representation.character irrep c).im = 0 := by
      -- By definition of Representation.character, the character values are real for all conjugacy classes.
      cases irrep <;> cases c <;> simp [Representation.character]

theorem Representation.convolution_orthog_golden_conjugate (k : D5) :
    ∑ g : D5, conj (Representation.χ .golden g) * conj (Representation.χ .conjugate (g⁻¹ * k)) = 0 := by
      -- Since the characters are real, their conjugates are just the characters themselves.
      have h_real : ∀ g : D5, (starRingEnd ℂ (Representation.χ .golden g)) = (Representation.χ .golden g) ∧ (starRingEnd ℂ (Representation.χ .conjugate g)) = (Representation.χ .conjugate g) := by
        -- Since the characters are real, their conjugates are equal to themselves.
        intros g
        simp [Representation.χ, Representation.character];
        cases h : g.toConjClass <;> simp +decide [ h ];
        norm_num [ Complex.ext_iff ];
      simp_all +decide [ Representation.χ ];
      fin_cases k <;> simp +decide [ Representation.character ];
      all_goals norm_cast;
      all_goals erw [ Finset.sum_congr rfl fun x hx => by erw [ show D5.toConjClass = fun g => if g = DihedralGroup.r 0 then D5.ConjClass.identity else if g = DihedralGroup.r 1 then D5.ConjClass.rot1 else if g = DihedralGroup.r 2 then D5.ConjClass.rot2 else if g = DihedralGroup.r 3 then D5.ConjClass.rot2 else if g = DihedralGroup.r 4 then D5.ConjClass.rot1 else D5.ConjClass.reflection from by funext g; fin_cases g <;> rfl ] ] ; simp +decide [ Fin.sum_univ_succ ] ;
      all_goals erw [ Finset.sum_eq_multiset_sum ] ; norm_cast;
      all_goals erw [ Multiset.map_coe ] ; simp +decide [ Finset.univ ] ;
      all_goals simp +decide [ List.finRange ] ;
      · norm_cast; ring; norm_num [ φ ] ; ring;
      · ring;
        norm_cast; rw [ show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; ring_nf; norm_num;
      · norm_num [ Complex.ext_iff, sq ];
        rw [ show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; ring ; norm_num;
      · norm_num [ Complex.ext_iff, sq ];
        rw [ show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; ring ; norm_num;
      · norm_num [ Complex.ext_iff, sq ];
        rw [ show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; ring ; norm_num

theorem BrockianSpiral.continuous (k α : ℝ) : Continuous (brockianSpiral k α) := by
  -- The function $t \mapsto (k * t : ℝ) * \exp(2 * \pi * I * (Real.rpow t α : ℝ))$ is continuous because it is a product of continuous functions.
  have h_cont : Continuous (fun t : ℝ => (k * t : ℝ) * Complex.exp (2 * Real.pi * Complex.I * (Real.rpow t α : ℝ))) := by
    by_cases h : α = 0 <;> simp_all +decide [ Real.rpow_def_of_pos ];
    · continuity;
    · refine' continuous_iff_continuousAt.mpr fun t => _;
      by_cases ht : t = 0 <;> simp_all +decide [ ContinuousAt ];
      · refine' squeeze_zero_norm _ _;
        exacts [ fun n => |k| * |n|, fun n => by simp +decide [ Complex.norm_exp ], Continuous.tendsto' ( by continuity ) _ _ ( by norm_num ) ];
      · exact Filter.Tendsto.mul ( Filter.Tendsto.mul tendsto_const_nhds ( Complex.continuous_ofReal.continuousAt ) ) ( Complex.continuous_exp.continuousAt.comp <| Filter.Tendsto.mul tendsto_const_nhds <| Complex.continuous_ofReal.continuousAt.comp <| Filter.Tendsto.rpow ( Filter.tendsto_id ) tendsto_const_nhds <| by aesop );
  -- Since the function brockianSpiral is defined as the product of two continuous functions, it is continuous.
  convert h_cont using 1

def BrockianSpiral.potential (k α ε : ℝ) (z : ℂ) : ℝ :=
  ∑' p : ℕ, if Nat.Prime p then 
    BrockianSpiral.primeWeight p * BrockianSpiral.gaussianKernel ε z (brockianSpiral k α p)
  else 0

def BrockianSpiral.potentialTrunc (k α ε : ℝ) (N : ℕ) (z : ℂ) : ℝ :=
  ∑ p ∈ range N, if Nat.Prime p then
    BrockianSpiral.primeWeight p * BrockianSpiral.gaussianKernel ε z (brockianSpiral k α p)
  else 0

structure GrandBrockianSystem where
  (H0 : Type*)
  [H0_add : NormedAddCommGroup H0]
  [H0_ip : InnerProductSpace ℂ H0]
  [H0_complete : CompleteSpace H0]
  
  (Δ0 : SelfAdjointUnbounded H0)
  
  (ι : Type)
  (Hecke : HeckeOperatorFamily ι H0)
  (W5 : AtkinLehnerInvolution H0)
  
  (Hecke_commutes_Δ0 : Prop)
  (W5_commutes_Δ0 : Prop)
  (W5_commutes_Hecke : Prop)
  
  (H5 : Type*)
  [H5_add : NormedAddCommGroup H5]
  [H5_ip : InnerProductSpace ℂ H5]
  [H5_complete : CompleteSpace H5]
  
  (cover : Level5CoverData H5 H0)
  
  (HB : Type*)
  [HB_add : NormedAddCommGroup HB]
  [HB_ip : InnerProductSpace ℂ HB]
  [HB_complete : CompleteSpace HB]
  
  (B : SelfAdjointUnbounded HB)
  
  (traceFormula : Prop)
  (spectralDeterminant : Prop)

def GrandBrockianSystem.isComplete (S : GrandBrockianSystem) : Prop :=
  S.Hecke_commutes_Δ0 ∧ S.W5_commutes_Δ0 ∧ S.W5_commutes_Hecke

def GrandBrockianSystem.provesRH (S : GrandBrockianSystem) : Prop := S.spectralDeterminant ∧ S.traceFormula

#check BZFC.BrockRay.ofNat
#check Representation.χ
#check isotypicProjector
#check P_golden
#check BrockianSpiral.potential
#check BrockianSpiral.potentialTrunc

#eval provenCount  -- 8

#eval openCount    -- 13

#check RiemannHypothesis
#check GrandBrockianSystem

theorem Representation.omega_abs : ‖ω‖ = 1 := by
  unfold ω
  rw [Complex.norm_exp]
  have : (2 * π * I / 5).re = 0 := by
    rw [div_eq_mul_inv, mul_assoc, mul_assoc]
    simp [Complex.mul_re, Complex.I_re, Complex.I_im]
  rw [this, Real.exp_zero]

open scoped BigOperators Real ComplexConjugate TensorProduct
open Complex Finset MeasureTheory

#check BrockianSpiral.gaussianKernel
