/-
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Benzene D 6 H Irreps
Category: Chemistry
Target: Chem.benzene_D6h_irreps
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Chem

/-- The molecular point group of benzene, `D₆ₕ`, realized as the direct product of the
dihedral group of order 12 (the symmetries `D₆` of the planar hexagonal carbon skeleton)
with the order-two group generated by the inversion centre `i`. -/
abbrev D6h : Type := DihedralGroup 6 × Multiplicative (ZMod 2)

/-- The list of dimensions of the irreducible representations appearing in the standard
`D₆ₕ` character table:
`A₁g, A₂g, B₁g, B₂g, E₁g, E₂g, A₁u, A₂u, B₁u, B₂u, E₁u, E₂u`. -/
def D6hIrrepDims : List ℕ := [1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2]

/-- The point group `D₆ₕ` of benzene has order 24. -/
theorem card_D6h : Nat.card D6h = 24 := by
  simp [Nat.card_eq_fintype_card, DihedralGroup.card]

/-- `D₆ₕ` has exactly 12 conjugacy classes
(`E, 2C₆, 2C₃, C₂, 3C₂', 3C₂'', i, 2S₃, 2S₆, σ_h, 3σ_d, 3σ_v`). -/
theorem card_conjClasses_D6h : Nat.card (ConjClasses D6h) = 12 := by
  rw [Nat.card_eq_fintype_card]
  decide

/-- **Benzene (`D₆ₕ`) irreducible representations.**

The `D₆ₕ` character table has the correct number of irreducible representations: the list of
irrep dimensions has exactly as many entries as `D₆ₕ` has conjugacy classes (namely 12), and
these dimensions satisfy the Burnside dimension identity `∑ dᵢ² = |G| = 24`, so no irreducible
representation is missing or repeated. Moreover every listed dimension divides the group order. -/
theorem benzene_D6h_irreps :
    D6hIrrepDims.length = Nat.card (ConjClasses D6h) ∧
    D6hIrrepDims.length = 12 ∧
    (D6hIrrepDims.map (fun d => d ^ 2)).sum = Nat.card D6h ∧
    ∀ d ∈ D6hIrrepDims, 0 < d ∧ d ∣ Nat.card D6h := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [card_conjClasses_D6h]; rfl
  · rfl
  · rw [card_D6h]; rfl
  · rw [card_D6h]
    decide

end Chem

