/-
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Chem

open MulAction

-- The action of the symmetry group `G` of a molecular skeleton `S` on the set of
-- substitution patterns `S → C` (assignments of substituents from `C` to the sites of `S`),
-- given by `(g • F) s = F (g⁻¹ • s)`.
attribute [local instance] arrowAction

variable {G S C : Type*} [Group G] [MulAction G S]

/-- The number of cycles of the skeleton symmetry `g` acting on the site set `S`,
i.e. the number of orbits of the cyclic group generated by `g`. -/
noncomputable def cycleCount (S : Type*) [MulAction G S] (g : G) : ℕ :=
  Nat.card (orbitRel.Quotient (Subgroup.zpowers g) S)

/-- A substitution pattern invariant under `g` is invariant under every power of `g`. -/
theorem invariant_zpow_smul {g : G} {F : S → C} (hF : ∀ s, F (g • s) = F s) (n : ℤ) (s : S) :
    F (g ^ n • s) = F s := by
  have hinv : ∀ s : S, F (g⁻¹ • s) = F s := by
    intro s
    have h := hF (g⁻¹ • s)
    rw [smul_smul, mul_inv_cancel, one_smul] at h
    exact h.symm
  induction n using Int.induction_on generalizing s with
  | zero => simp
  | succ k ih =>
      have : g ^ ((k : ℤ) + 1) • s = g ^ (k : ℤ) • (g • s) := by
        rw [zpow_add_one, mul_smul]
      rw [this, ih (g • s), hF]
  | pred k ih =>
      have : g ^ (-(k : ℤ) - 1) • s = g ^ (-(k : ℤ)) • (g⁻¹ • s) := by
        rw [zpow_sub_one, mul_smul]
      rw [this, ih (g⁻¹ • s), hinv]

/-- Substitution patterns fixed by `g` correspond exactly to arbitrary assignments of
substituents to the cycles of `g`. -/
noncomputable def fixedByArrowEquiv (g : G) :
    (fixedBy (S → C) g) ≃ (orbitRel.Quotient (Subgroup.zpowers g) S → C) where
  toFun := fun F => Quotient.lift (fun s => (F : S → C) s) (by
    rintro a b ⟨⟨x, hx⟩, hxa⟩
    obtain ⟨n, rfl⟩ := hx
    have hF : ∀ s, (F : S → C) (g • s) = (F : S → C) s := by
      intro s
      have h : (g • (F : S → C)) = (F : S → C) := F.2
      have h2 : (F : S → C) (g⁻¹ • (g • s)) = (F : S → C) (g • s) := congrFun h (g • s)
      rw [smul_smul, inv_mul_cancel, one_smul] at h2
      exact h2.symm
    have hb : g ^ n • b = a := hxa
    show (F : S → C) a = (F : S → C) b
    rw [← hb, invariant_zpow_smul hF])
  invFun := fun Φ => ⟨fun s => Φ (Quotient.mk _ s), by
    show (g • fun s => Φ (Quotient.mk _ s)) = fun s => Φ (Quotient.mk _ s)
    funext s
    show Φ (Quotient.mk _ (g⁻¹ • s)) = Φ (Quotient.mk _ s)
    congr 1
    apply Quotient.sound
    exact ⟨⟨g⁻¹, Subgroup.mem_zpowers_iff.2 ⟨-1, by simp⟩⟩, rfl⟩⟩
  left_inv := by intro F; ext s; rfl
  right_inv := by
    intro Φ
    funext q
    induction q using Quotient.inductionOn with
    | h s => rfl

/-- The number of substitution patterns fixed by `g` is `|C|` to the power of the number of
cycles of `g`. -/
theorem card_fixedBy_arrow [Finite S] (g : G) :
    Nat.card (fixedBy (S → C) g) = Nat.card C ^ cycleCount S g := by
  rw [Nat.card_congr (fixedByArrowEquiv (C := C) g), cycleCount, Nat.card_fun]

/-- Burnside's lemma in `Nat.card` form. -/
theorem burnside_nat_card {β : Type*} [MulAction G β] [Fintype G] [Finite β] :
    (∑ g : G, Nat.card (fixedBy β g)) = Nat.card (orbitRel.Quotient G β) * Nat.card G := by
  letI : ∀ g : G, Fintype (fixedBy β g) := fun g => Fintype.ofFinite _
  letI : Fintype (orbitRel.Quotient G β) := Fintype.ofFinite _
  simp only [Nat.card_eq_fintype_card]
  exact MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group G β

/-- **Pólya / Burnside isomer count.**  For a molecular skeleton with site set `S` carrying an
action of a finite symmetry group `G`, and a set `C` of possible substituents, the number of
distinct substitution isomers (orbits of `G` on the substitution patterns `S → C`), multiplied by
`|G|`, equals the sum over the symmetries `g ∈ G` of `|C| ^ (number of cycles of g on S)`.
Equivalently, the isomer count is the cycle-index average
`(1/|G|) * ∑_{g ∈ G} |C| ^ (cycles of g)`. -/
theorem polya_isomer_count [Fintype G] [Finite S] [Finite C] :
    Nat.card (orbitRel.Quotient G (S → C)) * Nat.card G
      = ∑ g : G, Nat.card C ^ cycleCount S g := by
  rw [← burnside_nat_card (G := G) (β := (S → C))]
  exact Finset.sum_congr rfl fun g _ => card_fixedBy_arrow g

/-- The cycle-index average form: the number of substitution isomers equals
`(1/|G|) * ∑_{g ∈ G} |C| ^ (number of cycles of g on the skeleton)`. -/
theorem polya_isomer_count_average [Fintype G] [Nonempty G] [Finite S] [Finite C] :
    (Nat.card (orbitRel.Quotient G (S → C)) : ℚ)
      = (∑ g : G, (Nat.card C : ℚ) ^ cycleCount S g) / (Nat.card G : ℚ) := by
  have hG : (Nat.card G : ℚ) ≠ 0 := by
    simp [Nat.card_eq_fintype_card, Fintype.card_ne_zero]
  rw [eq_div_iff hG]
  exact_mod_cast congrArg (fun n : ℕ => (n : ℚ)) (polya_isomer_count (G := G) (S := S) (C := C))

/-- The identity symmetry has exactly one cycle per site. -/
theorem cycleCount_one : cycleCount S (1 : G) = Nat.card S := by
  refine Nat.card_congr ?_
  refine ⟨Quotient.lift id ?_, fun s => Quotient.mk _ s, ?_, ?_⟩
  · rintro a b ⟨⟨x, hx⟩, hxa⟩
    obtain ⟨n, rfl⟩ := hx
    have : (1 : G) ^ n • b = a := hxa
    simpa using this.symm
  · intro q
    induction q using Quotient.inductionOn with
    | h s => rfl
  · intro s; rfl

/-- With a trivial symmetry group every substitution pattern is its own isomer:
there are `|C| ^ |S|` of them. -/
theorem isomer_count_of_trivial_group [Unique G] [Finite S] [Finite C] :
    Nat.card (orbitRel.Quotient G (S → C)) = Nat.card C ^ Nat.card S := by
  have h := polya_isomer_count (G := G) (S := S) (C := C)
  simp only [Finset.univ_unique, Finset.sum_singleton, Nat.card_unique, mul_one,
    Unique.eq_default] at h
  rw [h]
  congr 1
  rw [show (default : G) = 1 from Subsingleton.elim _ _, cycleCount_one]

/-! ### A worked chemical example: the rotational isomer count of a six-membered ring -/

section CyclicSkeleton

/-- For the rotation action of a cyclic (translation) group on itself, the number of cycles of
the rotation by `k` is the index of the subgroup generated by `k`. -/
theorem cycleCount_translation {A : Type*} [AddCommGroup A] (k : A) :
    cycleCount A (Multiplicative.ofAdd k) = (AddSubgroup.zmultiples k).index := by
  rw [cycleCount, AddSubgroup.index_eq_card]
  refine Nat.card_congr (Quotient.congr (Equiv.refl A) ?_)
  intro a b
  simp only [Equiv.refl_apply, QuotientAddGroup.leftRel_apply, MulAction.orbitRel_apply,
    MulAction.mem_orbit_iff, AddSubgroup.mem_zmultiples_iff]
  constructor
  · rintro ⟨⟨m, z, rfl⟩, hm⟩
    have hm' : (Multiplicative.ofAdd k) ^ z • b = a := hm
    rw [← ofAdd_zsmul] at hm'
    have h2 : z • k + b = a := hm'
    exact ⟨-z, by rw [neg_zsmul, ← h2]; abel⟩
  · rintro ⟨z, hz⟩
    refine ⟨⟨(Multiplicative.ofAdd k) ^ (-z), ⟨-z, rfl⟩⟩, ?_⟩
    show (Multiplicative.ofAdd k) ^ (-z) • b = a
    rw [← ofAdd_zsmul]
    show (-z) • k + b = a
    rw [neg_zsmul, hz]
    abel

/-- The subgroup of `ZMod n` generated by `k` has index `gcd n k`. -/
theorem index_zmultiples_zmod (n : ℕ) [NeZero n] (k : ZMod n) :
    (AddSubgroup.zmultiples k).index = Nat.gcd n k.val := by
  have hn : n ≠ 0 := NeZero.ne n
  have hk : ((k.val : ℕ) : ZMod n) = k := ZMod.natCast_zmod_val k
  have hord : addOrderOf k = n / Nat.gcd n k.val := by
    conv_lhs => rw [← hk]
    rw [ZMod.addOrderOf_coe _ hn]
  have hcard : Nat.card (AddSubgroup.zmultiples k) * (AddSubgroup.zmultiples k).index = n := by
    rw [AddSubgroup.card_mul_index, Nat.card_zmod]
  rw [Nat.card_zmultiples, hord] at hcard
  have hdvd : Nat.gcd n k.val ∣ n := Nat.gcd_dvd_left _ _
  have hgpos : 0 < Nat.gcd n k.val := Nat.gcd_pos_of_pos_left _ (Nat.pos_of_ne_zero hn)
  have hq : n / Nat.gcd n k.val * Nat.gcd n k.val = n := Nat.div_mul_cancel hdvd
  have hqpos : 0 < n / Nat.gcd n k.val :=
    Nat.div_pos (Nat.le_of_dvd (Nat.pos_of_ne_zero hn) hdvd) hgpos
  exact Nat.eq_of_mul_eq_mul_left hqpos (hcard.trans hq.symm)

/-- The rotation by `k` of an `n`-membered ring has `gcd n k` cycles. -/
theorem cycleCount_zmod_rotation (n : ℕ) [NeZero n] (k : ZMod n) :
    cycleCount (ZMod n) (Multiplicative.ofAdd k) = Nat.gcd n k.val := by
  rw [cycleCount_translation, index_zmultiples_zmod]

/-- **Substitution isomers of a six-membered ring under its rotation group.**
Labelling the six ring positions by `ZMod 6`, with the cyclic rotation group `C₆` acting on them
and two possible substituents at each position (`Bool`), there are exactly `14` distinct
substitution patterns up to rotation. -/
theorem benzene_rotation_isomer_count :
    Nat.card (orbitRel.Quotient (Multiplicative (ZMod 6)) (ZMod 6 → Bool)) = 14 := by
  have hterm : ∀ k : ZMod 6,
      (2 : ℕ) ^ Nat.gcd 6 k.val
        = Nat.card Bool ^ cycleCount (ZMod 6) (Multiplicative.ofAdd k) := by
    intro k
    rw [cycleCount_zmod_rotation]
    norm_num [Nat.card_eq_fintype_card]
  have hsum : ∑ g : Multiplicative (ZMod 6), Nat.card Bool ^ cycleCount (ZMod 6) g = 84 := by
    rw [← Fintype.sum_equiv (Multiplicative.ofAdd (α := ZMod 6))
      (fun k : ZMod 6 => (2 : ℕ) ^ Nat.gcd 6 k.val) _ hterm]
    decide
  have hG : Nat.card (Multiplicative (ZMod 6)) = 6 := by
    simp [Nat.card_eq_fintype_card]
  have h := polya_isomer_count (G := Multiplicative (ZMod 6)) (S := ZMod 6) (C := Bool)
  rw [hsum, hG] at h
  omega

end CyclicSkeleton

/-! ### A computational handle on cycle counts, and the full benzene isomer count -/

section Computation

/-- If `g ^ m = 1`, every integer power of `g` is one of `g ^ 0, …, g ^ (m-1)`. -/
theorem zpow_eq_pow_toNat_emod {g : G} {m : ℕ} (hm : 0 < m) (hgm : g ^ m = 1) (z : ℤ) :
    g ^ z = g ^ ((z % m).toNat) := by
  have hmz : (m : ℤ) ≠ 0 := by exact_mod_cast hm.ne'
  have h1 : (m : ℤ) * (z / m) + z % m = z := Int.mul_ediv_add_emod z m
  have hnn : 0 ≤ z % m := Int.emod_nonneg z hmz
  calc g ^ z = g ^ ((m : ℤ) * (z / m) + z % m) := by rw [h1]
    _ = (g ^ (m : ℤ)) ^ (z / m) * g ^ (z % m) := by rw [zpow_add, zpow_mul]
    _ = g ^ (z % m) := by rw [zpow_natCast, hgm, one_zpow, one_mul]
    _ = g ^ ((z % m).toNat) := by rw [← zpow_natCast, Int.toNat_of_nonneg hnn]

/-- A computable description of the cycle count: the number of distinct orbit sets
`{g ^ i • s : i < m}`, for any exponent `m > 0` with `g ^ m = 1`. -/
theorem cycleCount_eq_card_image [Fintype S] [DecidableEq S] (g : G) (m : ℕ) (hm : 0 < m)
    (hgm : g ^ m = 1) :
    cycleCount S g
      = (Finset.image (fun s : S => Finset.image (fun i : Fin m => g ^ (i : ℕ) • s) Finset.univ)
          Finset.univ).card := by
  set f : S → Finset S :=
    fun s => Finset.image (fun i : Fin m => g ^ (i : ℕ) • s) Finset.univ with hf
  have hmem : ∀ (s x : S), x ∈ f s ↔ x ∈ orbit (Subgroup.zpowers g) s := by
    intro s x
    constructor
    · intro hx
      rw [hf] at hx
      simp only [Finset.mem_image, Finset.mem_univ, true_and] at hx
      obtain ⟨i, rfl⟩ := hx
      exact ⟨⟨g ^ (i : ℕ), ⟨(i : ℕ), by simp⟩⟩, rfl⟩
    · rintro ⟨⟨y, z, rfl⟩, hy⟩
      have hyx : g ^ z • s = x := hy
      rw [zpow_eq_pow_toNat_emod hm hgm z] at hyx
      have hlt : (z % m).toNat < m := by
        have h0 : 0 ≤ z % m := Int.emod_nonneg z (by exact_mod_cast hm.ne')
        have h1 : z % m < m := Int.emod_lt_of_pos z (by exact_mod_cast hm)
        omega
      rw [hf]
      simp only [Finset.mem_image, Finset.mem_univ, true_and]
      exact ⟨⟨(z % m).toNat, hlt⟩, hyx⟩
  have hfeq : ∀ s t : S, f s = f t ↔ orbitRel (Subgroup.zpowers g) S s t := by
    intro s t
    constructor
    · intro h
      have hs : s ∈ f s := by rw [hmem]; exact mem_orbit_self s
      rw [h, hmem] at hs
      exact hs
    · intro h
      have horb : orbit (Subgroup.zpowers g) s = orbit (Subgroup.zpowers g) t := by
        rw [orbit_eq_iff]; exact h
      ext x
      rw [hmem, hmem, horb]
  have hwd : ∀ s t : S, orbitRel (Subgroup.zpowers g) S s t → f s = f t := fun s t h =>
    (hfeq s t).2 h
  rw [cycleCount]
  have hcard : Nat.card (orbitRel.Quotient (Subgroup.zpowers g) S)
      = Nat.card {x // x ∈ Finset.image f Finset.univ} := by
    refine Nat.card_congr (Equiv.ofBijective (fun q => ⟨Quotient.liftOn q f hwd, ?_⟩) ⟨?_, ?_⟩)
    · induction q using Quotient.inductionOn with
      | h s => exact Finset.mem_image_of_mem f (Finset.mem_univ s)
    · intro q1 q2 h
      induction q1 using Quotient.inductionOn with
      | h s =>
        induction q2 using Quotient.inductionOn with
        | h t =>
          have hst : f s = f t := congrArg Subtype.val h
          exact Quotient.sound ((hfeq s t).1 hst)
    · rintro ⟨x, hx⟩
      simp only [Finset.mem_image, Finset.mem_univ, true_and] at hx
      obtain ⟨s, rfl⟩ := hx
      exact ⟨Quotient.mk _ s, rfl⟩
  rw [hcard, Nat.card_eq_fintype_card, Fintype.card_coe]

end Computation

section DihedralSkeleton

/-- The full symmetry group of a regular `n`-gon acting on its `n` vertices `ZMod n`:
the rotation `r i` sends the vertex `x` to `x + i`, the reflection `sr i` sends `x` to `-i - x`. -/
instance dihedralSMul (n : ℕ) : SMul (DihedralGroup n) (ZMod n) where
  smul g x := match g with
    | DihedralGroup.r i => x + i
    | DihedralGroup.sr i => -i - x

instance dihedralMulAction (n : ℕ) : MulAction (DihedralGroup n) (ZMod n) where
  one_smul x := by show x + 0 = x; ring
  mul_smul g h x := by
    cases g with
    | r i =>
      cases h with
      | r j => show x + (i + j) = (x + j) + i; ring
      | sr j => show -(j - i) - x = (-j - x) + i; ring
    | sr i =>
      cases h with
      | r j => show -(i + j) - x = -i - (x + j); ring
      | sr j => show x + (j - i) = -i - (-j - x); ring

/-- **Substitution isomers of benzene.**  The six ring positions of benzene are labelled by
`ZMod 6` and carry the action of the full symmetry group of the hexagon (the dihedral group of
order 12, i.e. rotations together with reflections).  With two possible substituents at each
position (`Bool`, e.g. `H` and `Cl`), there are exactly `13` distinct substitution isomers,
in agreement with the classical count `1 + 1 + 3 + 3 + 3 + 1 + 1` of
C₆H₆, C₆H₅X, the three C₆H₄X₂, the three C₆H₃X₃, the three C₆H₂X₄, C₆HX₅ and C₆X₆. -/
theorem benzene_isomer_count :
    Nat.card (orbitRel.Quotient (DihedralGroup 6) (ZMod 6 → Bool)) = 13 := by
  have hpow : ∀ g : DihedralGroup 6, g ^ 12 = 1 := by
    intro g
    have h := pow_card_eq_one (G := DihedralGroup 6) (x := g)
    rwa [DihedralGroup.card, show 2 * 6 = 12 from rfl] at h
  have hterm : ∀ g : DihedralGroup 6,
      Nat.card Bool ^ cycleCount (ZMod 6) g
        = 2 ^ (Finset.image (fun s : ZMod 6 =>
            Finset.image (fun i : Fin 12 => g ^ (i : ℕ) • s) Finset.univ) Finset.univ).card := by
    intro g
    rw [cycleCount_eq_card_image g 12 (by norm_num) (hpow g)]
    norm_num [Nat.card_eq_fintype_card]
  have hsum : ∑ g : DihedralGroup 6, Nat.card Bool ^ cycleCount (ZMod 6) g = 156 := by
    rw [Finset.sum_congr rfl (fun g _ => hterm g)]
    decide
  have hG : Nat.card (DihedralGroup 6) = 12 := by rw [DihedralGroup.nat_card]
  have h := polya_isomer_count (G := DihedralGroup 6) (S := ZMod 6) (C := Bool)
  rw [hsum, hG] at h
  omega

end DihedralSkeleton

end Chem

