import Mathlib

/-!
# Polya Isomer Count
Category: Chemistry
Target: Chem.polya_isomer_count
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)

(Note: Lean 4 requires `import` commands to precede any other command, including module
docstrings, so the header block appears immediately after the import.)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

namespace Chem

open MulAction

/- The symmetry group `G` of a skeleton acts on the substituted molecules (colourings of the
positions `P` by substituents `C`) by `(g • f) p = f (g⁻¹ • p)`. -/
attribute [local instance] arrowAction

variable {G P C : Type*} [Group G] [MulAction G P]

/-- A colouring fixed by `g` is constant along the orbits of the cyclic group generated by `g`. -/
theorem coloring_invariant_of_fixed {g : G} {f : P → C} (hf : g • f = f) {h : G}
    (hh : h ∈ Subgroup.zpowers g) (p : P) : f (h • p) = f p := by
  have hs : h • f = f := (Subgroup.zpowers_le (H := MulAction.stabilizer G f)).mpr hf hh
  calc f (h • p) = (h • f) (h • p) := by rw [hs]
    _ = f (h⁻¹ • h • p) := rfl
    _ = f p := by simp

/-- The colourings of the positions `P` by substituents `C` that are fixed by a symmetry `g`
are exactly the colourings that are constant on the cycles of `g`, i.e. they correspond to
arbitrary colourings of the orbit set of `⟨g⟩` acting on `P`. -/
noncomputable def fixedColoringsEquiv (g : G) :
    MulAction.fixedBy (P → C) g ≃ (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P → C) where
  toFun F := Quotient.lift (fun p => (F : P → C) p) (by
    rintro p q hpq
    obtain ⟨⟨h, hh⟩, rfl⟩ := hpq
    exact coloring_invariant_of_fixed F.2 hh q)
  invFun q := ⟨fun p => q (Quotient.mk'' p), by
    ext p
    show q (Quotient.mk'' (g⁻¹ • p)) = q (Quotient.mk'' p)
    exact congrArg q (Quotient.sound ⟨⟨g⁻¹, Subgroup.inv_mem _ (Subgroup.mem_zpowers g)⟩, rfl⟩)⟩
  left_inv _ := rfl
  right_inv q := by ext x; induction x using Quotient.inductionOn with | _ p => rfl

/-- The number of colourings fixed by a symmetry `g` is `|C|` raised to the number of cycles
of `g` on the positions (the term appearing in Pólya's cycle index). -/
theorem card_fixedBy_colorings (g : G) [Finite P] :
    Nat.card (MulAction.fixedBy (P → C) g)
      = Nat.card C ^ Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P) := by
  rw [Nat.card_congr (fixedColoringsEquiv (C := C) g), Nat.card_fun]

/-- **Pólya / Burnside isomer count.**  Let a finite symmetry group `G` act on the positions `P`
of a molecular skeleton, and let `C` be a finite set of substituents.  Substitution isomers are
the orbits of `G` on the colourings `P → C`.  Their number, multiplied by `|G|`, equals the sum
over the symmetries `g ∈ G` of `|C|` raised to the number of cycles of `g` on the positions,
i.e. the isomer count is the Pólya cycle-index average
`(1/|G|) ∑_{g ∈ G} |C| ^ (number of cycles of g)`. -/
theorem polya_isomer_count [Fintype G] [Finite P] [Finite C] :
    Nat.card (MulAction.orbitRel.Quotient G (P → C)) * Nat.card G
      = ∑ g : G, Nat.card C ^ Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P) := by
  classical
  have hPC : Finite (P → C) := Pi.finite
  letI : Fintype (MulAction.orbitRel.Quotient G (P → C)) := Fintype.ofFinite _
  haveI : ∀ g : G, Fintype (MulAction.fixedBy (P → C) g) := fun _ => Fintype.ofFinite _
  have burnside := MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group G (P → C)
  calc Nat.card (MulAction.orbitRel.Quotient G (P → C)) * Nat.card G
      = Fintype.card (MulAction.orbitRel.Quotient G (P → C)) * Fintype.card G := by
        rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card]
    _ = ∑ g : G, Fintype.card (MulAction.fixedBy (P → C) g) := burnside.symm
    _ = ∑ g : G, Nat.card C ^ Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) P) := by
        refine Finset.sum_congr rfl fun g _ => ?_
        rw [← Nat.card_eq_fintype_card, card_fixedBy_colorings]

end Chem

