/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 857e33a2-b300-4e10-bc08-3e5b2fcd4456

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Matrix

open Finset Matrix SimpleGraph Real

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- Laplacian matrix L = D - A -/
abbrev L (G : SimpleGraph V) : Matrix V V ℝ := G.lapMatrix ℝ

/-- Matrix PSD ordering: M ⪯ N iff N - M is PSD -/
def psdLe (M N : Matrix V V ℝ) : Prop := (N - M).PosSemidef

infix:50 " ⪯ " => psdLe

/-- Standard basis vector -/
def e (v : V) : V → ℝ := fun i => if i = v then 1 else 0

/-- Edge matrix: (e_u - e_v)(e_u - e_v)^T -/
def edgeMat (u v : V) : Matrix V V ℝ :=
  Matrix.vecMulVec (e u - e v) (e u - e v)

/-- Edge matrix is PSD -/
theorem edgeMat_psd (u v : V) : (edgeMat u v).PosSemidef := by
  -- The edge matrix is of the form $xx^T$, which is positive semi-definite.
  have h_edge : ∀ (x : V → ℝ), (Matrix.vecMulVec x x).PosSemidef := by
    intro x
    unfold Matrix.PosSemidef
    simp [Matrix.vecMulVec];
    simp [Matrix.IsHermitian, Matrix.mulVec, dotProduct];
    -- The transpose of the matrix is equal to itself because multiplication is commutative.
    simp [Matrix.transpose, mul_comm];
    intro y
    have h_sum : ∑ x_2 : V, y x_2 * ∑ x_3 : V, y x_3 * (x x_2 * x x_3) = (∑ x_2 : V, y x_2 * x x_2)^2 := by
      simp +decide only [mul_left_comm, mul_comm, Finset.mul_sum _ _ _, pow_two];
    exact h_sum.symm ▸ sq_nonneg _;
  exact h_edge _

/-- Vertex chunk: A_v := (1/2) Σ_{u~v} (e_v - e_u)(e_v - e_u)^T -/
def Av (G : SimpleGraph V) (v : V) : Matrix V V ℝ :=
  (1/2 : ℝ) • ∑ u ∈ G.neighborFinset v, edgeMat v u

/-- Graph G_S with edges only inside S -/
def restrictToFinset (G : SimpleGraph V) (S : Finset V) : SimpleGraph V where
  Adj i j := i ∈ S ∧ j ∈ S ∧ G.Adj i j
  symm := fun i j h => ⟨h.2.1, h.1, h.2.2.symm⟩
  loopless := fun i hi => hi.2.2.ne rfl

/-- Induced Laplacian L_S -/
abbrev Ls (G : SimpleGraph V) (S : Finset V) : Matrix V V ℝ :=
  L (restrictToFinset G S)

/-- S is ε-light if εL - L_S is positive semidefinite -/
def IsEpsilonLight (G : SimpleGraph V) (S : Finset V) (ε : ℝ) : Prop :=
  (ε • L G - Ls G S).PosSemidef

/--
**BRIDGE LEMMA** (PROVEN)

For any S ⊆ V: L_S ⪯ Σ_{v∈S} A_v

This was proven by Aristotle in ~180 lines. The proof shows that the
difference Σ A_v - L_S equals the sum of boundary edge contributions,
each of which is PSD.
-/
theorem Ls_psdLe_sumAv (G : SimpleGraph V) (S : Finset V) :
    Ls G S ⪯ ∑ v ∈ S, Av G v := by
  -- Full proof omitted for brevity (see Aristotle's version)
  -- The proof works by showing:
  -- 1. L_S = sum of A_v for restricted graph
  -- 2. Each boundary edge contributes PSD slack
  -- 3. Therefore the difference is PSD
  -- By definition of $Ls$, we know that $Ls(G, S) = \sum_{v \in S} \frac{1}{2} \sum_{u \in N(v)} (e_v - e_u)(e_v - e_u)^T$.
  have h_laplacian : Ls G S = ∑ v ∈ S, (1 / 2 : ℝ) • ∑ u ∈ G.neighborFinset v ∩ S, edgeMat v u := by
    -- By definition of the Laplacian matrix, we can write it as the sum of edge matrices for all edges in the graph.
    have h_laplacian : ∀ (G : SimpleGraph V), L G = ∑ v ∈ Finset.univ, (1 / 2 : ℝ) • ∑ u ∈ G.neighborFinset v, edgeMat v u := by
      intro G
      ext v w
      simp [L, edgeMat];
      by_cases hvw : v = w <;> simp +decide [ hvw, Matrix.vecMulVec, SimpleGraph.lapMatrix ];
      · simp +decide [ Matrix.sum_apply, Matrix.of_apply, e ];
        simp +decide [ Finset.sum_add_distrib, sub_mul, mul_sub, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, SimpleGraph.degMatrix ];
        simp +decide [ Finset.sum_ite, SimpleGraph.degree, SimpleGraph.neighborFinset ];
        rw [ show ( Finset.filter ( fun x => G.Adj x w ) Finset.univ ) = Finset.filter ( fun x => G.Adj w x ) Finset.univ from Finset.filter_congr fun x _ => by rw [ SimpleGraph.adj_comm ] ] ; ring;
      · simp +decide [ Matrix.sum_apply, SimpleGraph.degMatrix, SimpleGraph.neighborFinset_def, hvw ];
        simp +decide [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, sub_mul, mul_sub, e ];
        simp +decide [ hvw, SimpleGraph.adj_comm, Finset.sum_ite ];
        split_ifs <;> norm_num;
    rw [ show Ls G S = L ( restrictToFinset G S ) from rfl, h_laplacian ];
    rw [ ← Finset.sum_subset ( Finset.subset_univ S ) ];
    · congr! 3;
      ext; simp [restrictToFinset];
      aesop;
    · simp +contextual [ SimpleGraph.neighborFinset ];
      simp +contextual [ SimpleGraph.neighborSet, restrictToFinset ];
  -- By definition of $Av$, we know that $\sum_{v \in S} Av v = \sum_{v \in S} \frac{1}{2} \sum_{u \in N(v)} (e_v - e_u)(e_v - e_u)^T$.
  have h_sum_av : ∑ v ∈ S, Av G v = ∑ v ∈ S, (1 / 2 : ℝ) • ∑ u ∈ G.neighborFinset v, edgeMat v u := by
    rfl;
  -- Since these two sums only differ by the terms where $u \notin S$, we can conclude that $Ls(G, S) \preceq \sum_{v \in S} Av v$.
  have h_diff : ∑ v ∈ S, (1 / 2 : ℝ) • ∑ u ∈ G.neighborFinset v, edgeMat v u - ∑ v ∈ S, (1 / 2 : ℝ) • ∑ u ∈ G.neighborFinset v ∩ S, edgeMat v u = ∑ v ∈ S, (1 / 2 : ℝ) • ∑ u ∈ G.neighborFinset v \ S, edgeMat v u := by
    rw [ ← Finset.sum_sub_distrib ];
    refine' Finset.sum_congr rfl fun v hv => _;
    rw [ ← smul_sub, ← Finset.sum_sdiff ( Finset.inter_subset_left : G.neighborFinset v ∩ S ⊆ G.neighborFinset v ) ];
    simp +decide [ Finset.sdiff_inter_self_left ];
  -- Since these two sums only differ by the terms where $u \notin S$, we can conclude that $Ls(G, S) \preceq \sum_{v \in S} Av v$ by showing that the difference is positive semidefinite.
  have h_diff_pos : (∑ v ∈ S, (1 / 2 : ℝ) • ∑ u ∈ G.neighborFinset v \ S, edgeMat v u).PosSemidef := by
    have h_diff_pos : ∀ v ∈ S, (∑ u ∈ G.neighborFinset v \ S, edgeMat v u).PosSemidef := by
      intro v hv
      have h_diff_pos : ∀ u ∈ G.neighborFinset v \ S, (edgeMat v u).PosSemidef := by
        exact?;
      -- Apply the fact that the sum of positive semidefinite matrices is positive semidefinite.
      have h_sum_pos : ∀ (s : Finset V), (∀ u ∈ s, (edgeMat v u).PosSemidef) → (∑ u ∈ s, edgeMat v u).PosSemidef := by
        -- The sum of positive semidefinite matrices is positive semidefinite.
        intros s hs
        induction' s using Finset.induction with u s ih;
        · simp +decide [ Matrix.PosSemidef ];
        · rw [ Finset.sum_insert ih ];
          exact Matrix.PosSemidef.add ( hs u ( Finset.mem_insert_self _ _ ) ) ( by apply_assumption; exact fun x hx => hs x ( Finset.mem_insert_of_mem hx ) );
      exact h_sum_pos _ h_diff_pos;
    -- Since each term in the sum is positive semidefinite, their sum is also positive semidefinite.
    have h_sum_pos : ∀ {M : Finset V} {f : V → Matrix V V ℝ}, (∀ v ∈ M, (f v).PosSemidef) → (∑ v ∈ M, f v).PosSemidef := by
      -- The sum of positive semidefinite matrices is positive semidefinite.
      intros M f hf
      induction' M using Finset.induction with v M ih;
      · simp +decide [ Matrix.PosSemidef ];
      · rw [ Finset.sum_insert ih ];
        exact Matrix.PosSemidef.add ( hf v ( Finset.mem_insert_self _ _ ) ) ( by apply_assumption; exact fun x hx => hf x ( Finset.mem_insert_of_mem hx ) );
    convert h_sum_pos fun v hv => ?_ using 1;
    convert h_diff_pos v hv |> fun h => h.smul ( show ( 0 : ℝ ) ≤ 1 / 2 by norm_num ) using 1;
  unfold psdLe; aesop; -- Proven by Aristotle, 180 lines

/-- Moore-Penrose conditions -/
def IsMoorePenrose (M P : Matrix V V ℝ) : Prop :=
  M * P * M = M ∧ P * M * P = P ∧ (M * P).IsHermitian ∧ (P * M).IsHermitian

/-- Pseudoinverse definition -/
def Matrix.pseudoInverse (M : Matrix V V ℝ) : Matrix V V ℝ :=
  if h : ∃ P, IsMoorePenrose M P then Classical.choose h else 0

/-- Pseudoinverse of Laplacian -/
def LDagger (G : SimpleGraph V) : Matrix V V ℝ := 
  (L G).pseudoInverse

#check dotProduct

/-- 
Leverage score of edge (s,t):
ℓ(s,t) = w(s,t) · (δ_s - δ_t)^T L† (δ_s - δ_t)

For simple graphs, w(s,t) = 1 when adjacent, 0 otherwise.
-/
def leverageScore (G : SimpleGraph V) (s t : V) : ℝ :=
  if G.Adj s t then
    let diff := e s - e t
    dotProduct diff ((LDagger G).mulVec diff)
  else 0

/-- 
Total leverage score from S to T:
ℓ(S,T) = Σ_{s∈S, t∈T} ℓ(s,t)
-/
def leverageScoreSet (G : SimpleGraph V) (S T : Finset V) : ℝ :=
  ∑ s ∈ S, ∑ t ∈ T, leverageScore G s t

/-- 
Boundary leverage score:
ℓ(S) = ℓ(S, V \ S)
-/
def boundaryLeverageScore (G : SimpleGraph V) (S : Finset V) : ℝ :=
  leverageScoreSet G S (Finset.univ.filter (· ∉ S))

/-- 
Sum of top σ eigenvalues of matrix A.
Tr_σ(A) = λ₁ + λ₂ + ... + λ_σ where λ₁ ≥ λ₂ ≥ ... ≥ λ_n
-/
def Trσ (A : Matrix V V ℝ) (k : ℕ) : ℝ :=
  if h : A.IsHermitian then
    let evals := (Finset.univ.toList.map (h.eigenvalues)).mergeSort (fun x y => y ≤ x)
    (evals.take k).sum
  else 0

/-- 
Modified barrier function:
Φ_σ^u(A) = Tr_σ((uI - A)^{-1}) = Σᵢ₌₁^σ 1/(u - λᵢ)

If u ≤ λ₁, we define Φ = ∞.
-/
def barrierFunction (A : Matrix V V ℝ) (u : ℝ) (k : ℕ) : ℝ :=
  Trσ (u • (1 : Matrix V V ℝ) - A)⁻¹ k

/-- δ = 21/n (step size for barrier function) -/
def δ (n : ℕ) : ℝ := 21 / n

/-- φ = n/21 (upper bound on barrier function) -/
def φ (n : ℕ) : ℝ := n / 21

/-- σ = ⌊εn/42⌋ (target set size) -/
def σ (ε : ℝ) (n : ℕ) : ℕ := ⌊ε * n / 42⌋₊

/-- The set of vertices t ∉ S that satisfy the leverage score condition -/
def GoodLeverageVertices (G : SimpleGraph V) (S : Finset V) : Finset V :=
  Finset.univ.filter (fun t => t ∉ S ∧ 
    boundaryLeverageScore G (insert t S) ≤ boundaryLeverageScore G S + 4)

/--
Statement of Lemma 2.1: Leverage Score Bound
-/
def LeverageScoreBoundStatement (G : SimpleGraph V) : Prop :=
  ∀ (S : Finset V),
    2 * (Finset.univ.filter (fun t => t ∉ S ∧ 
      boundaryLeverageScore G (insert t S) ≤ boundaryLeverageScore G S + 4)).card 
    > (Finset.univ.filter (· ∉ S)).card

/-- The sum of vertex chunks over all vertices is the Laplacian -/
theorem sum_Av_eq_L (G : SimpleGraph V) : ∑ v ∈ Finset.univ, Av G v = L G := by
  simp [Av, L, SimpleGraph.lapMatrix, SimpleGraph.degMatrix, SimpleGraph.adjMatrix]
  ext i j
  simp [Matrix.sum_apply, Matrix.sub_apply, Matrix.diagonal_apply, Matrix.of_apply]
  -- The ATP should be able to handle the rest with some expansion
  unfold edgeMat;
  simp +decide [ Matrix.vecMulVec, e ];
  by_cases hij : i = j <;> simp +decide [ hij, SimpleGraph.degree, SimpleGraph.neighborFinset ];
  · simp +decide [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul, sub_mul, mul_sub, hij ];
    simp +decide [ Finset.sum_ite, SimpleGraph.adj_comm ];
    ring;
  · rw [ Finset.sum_eq_add ( i ) ( j ) ] <;> simp +decide [ hij, SimpleGraph.neighborSet ];
    · split_ifs <;> simp_all +decide [ SimpleGraph.adj_comm ];
      norm_num;
    · aesop

/--
Statement of Claim 2.2: Self-Leverage Bound
-/
def SelfLeverageBoundStatement (G : SimpleGraph V) : Prop :=
  ∀ (T : Finset V),
    ∑ t ∈ T, leverageScoreSet G {t} T ≤ 2 * ((T.card : ℝ) - 1)

/-
Lemma 2.4: If A, B are PSD, δ > 0, and a specific condition involving traces holds, then the barrier function of A + B at u + δ is bounded by the barrier function of A at u.
-/
/--
**LEMMA 2.4: Barrier Function Decrease**

If A, B are PSD, δ > 0, M = (u+δ)I - A, Φ_σ^u(A) < ∞, and
  Tr_σ(M^{-2}B) / (Φ_σ^u(A) - Φ_σ^{u+δ}(A)) + Tr_σ(M^{-1}B) < 1
then Φ_σ^{u+δ}(A + B) ≤ Φ_σ^u(A)
-/
def BarrierDecreaseStatement (V : Type*) [Fintype V] [DecidableEq V] : Prop :=
  ∀ (A B : Matrix V V ℝ) (u δ : ℝ) (k : ℕ),
    A.PosSemidef → B.PosSemidef → 0 < δ →
    (u • (1 : Matrix V V ℝ) - A).PosDef → -- Corresponds to Φ < ∞ (u > λ₁)
    let M := (u + δ) • (1 : Matrix V V ℝ) - A
    let condition := Trσ (M⁻¹ * M⁻¹ * B) k / 
                     (barrierFunction A u k - barrierFunction A (u + δ) k) +
                     Trσ (M⁻¹ * B) k
    condition < 1 → 
    barrierFunction (A + B) (u + δ) k ≤ barrierFunction A u k

/--
Corrected Statement of Claim 2.2: Self-Leverage Bound
Requires T to be nonempty.
-/
def SelfLeverageBoundProp (G : SimpleGraph V) : Prop :=
  ∀ (T : Finset V), T.Nonempty →
    ∑ t ∈ T, leverageScoreSet G {t} T ≤ 2 * ((T.card : ℝ) - 1)

/--
The update matrix when adding t to S: B_t = L_{S ∪ {t}} - L_S
-/
def UpdateMatrix (G : SimpleGraph V) (S : Finset V) (t : V) : Matrix V V ℝ :=
  Ls G (insert t S) - Ls G S
