/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ac5690da-0f40-4251-b6c1-fa69019790d1

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-- PSD ordering: M ⪯ N means N - M is PSD -/
def psdLe {V : Type*} [Fintype V] [DecidableEq V] (M N : Matrix V V ℝ) : Prop := (N - M).PosSemidef
infix:50 " ⪯ " => psdLe

/-- Standard basis vector e_v -/
def e {V : Type*} [Fintype V] [DecidableEq V] (v : V) : V → ℝ := fun i => if i = v then 1 else 0

/-- Rank-1 edge matrix (e_u - e_v)(e_u - e_v)^T -/
def edgeMat {V : Type*} [Fintype V] [DecidableEq V] (u v : V) : Matrix V V ℝ :=
  Matrix.vecMulVec (e u - e v) (e u - e v)

/--
Vertex chunk: A_v := (1/2) Σ_{u~v} (e_v - e_u)(e_v - e_u)^T

These are PSD vertex contributions. Summing over all vertices 
recovers the Laplacian.
-/
def Av {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (v : V) : Matrix V V ℝ := by
  classical
  exact ((1/2 : ℝ) • ∑ u ∈ G.neighborFinset v, edgeMat v u)

open scoped BigOperators Matrix
open Finset Matrix SimpleGraph Real

/-- Laplacian matrix L (Mathlib built-in) -/
abbrev L {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) : Matrix V V ℝ :=
  G.lapMatrix ℝ

/--
G_S = (V, E(S,S)) as in Question 6:
Same vertex set V, edges restricted to pairs inside S.
-/
def restrictToFinset {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) : SimpleGraph V where
  Adj i j := i ∈ S ∧ j ∈ S ∧ G.Adj i j
  symm := by
    -- Since adjacency is symmetric in a simple graph, if i is adjacent to j, then j is also adjacent to i. Therefore, the symmetric property holds.
    intros i j hij; exact ⟨hij.2.1, hij.1, hij.2.2.symm⟩
  loopless := by
    -- Since adjacency is irreflexive in a simple graph, the relation defined here is also irreflexive.
    intros i hi
    aesop

/-- L_S = Laplacian of G_S -/
abbrev Ls {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) : Matrix V V ℝ :=
  L (restrictToFinset G S)

/--
S is ε-light iff εL - L_S is positive semidefinite.
EXACT definition from Question 6.
-/
def IsEpsilonLight {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (ε : ℝ) : Prop :=
  (ε • L G - Ls G S).PosSemidef

/--
If Σ_{v∈S} A_v ⪯ εL, then S is ε-light.

Proof: PSD is closed under addition:
  εL - L_S = (εL - Σ A_v) + (Σ A_v - L_S)
-/
theorem epsilonLight_of_sumAv {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (ε : ℝ)
    (hBridge : Ls G S ⪯ ∑ v ∈ S, Av G v) :
    (∑ v ∈ S, Av G v) ⪯ ε • L G → IsEpsilonLight G S ε := by
      intro h;
      -- By transitivity of the PSD order, if L_S ≤ ∑_{v ∈ S} A_v and ∑_{v ∈ S} A_v ≤ ε • L, then L_S ≤ ε • L.
      have hTrans : (ε • L G - Ls G S).PosSemidef := by
        have h1 : (ε • L G - ∑ v ∈ S, Av G v).PosSemidef := by
          exact?
        have h2 : (∑ v ∈ S, Av G v - Ls G S).PosSemidef := by
          exact?
        convert h1.add h2 using 1 ; abel_nf;
      exact hTrans

theorem Ls_psdLe_sumAv {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) :
    Ls G S ⪯ ∑ v ∈ S, Av G v := by
      refine' ⟨ _, fun x => _ ⟩;
      · unfold Av Ls; simp +decide [ Matrix.IsHermitian, Matrix.transpose_sub, Matrix.transpose_smul ] ;
        unfold L; simp +decide [ SimpleGraph.lapMatrix, Matrix.transpose_sum, Matrix.transpose_smul ] ;
        simp +decide [ SimpleGraph.degMatrix, SimpleGraph.adjMatrix, edgeMat ];
      · -- By definition of $A_v$, we can expand the sum $\sum_{v \in S} (x^T A_v x)$.
        have h_expand : ∑ v ∈ S, (Star.star x ⬝ᵥ (Av G v) *ᵥ x) = (1 / 2 : ℝ) * ∑ v ∈ S, ∑ u ∈ G.neighborFinset v, ((x v - x u) ^ 2) := by
          unfold Av; simp +decide [ Matrix.mulVec, dotProduct, Finset.mul_sum _ _ _ ] ; ring;
          unfold edgeMat; simp +decide [ Matrix.sum_apply, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_assoc, mul_comm, mul_left_comm, sq ] ; ring;
          simp +decide [ Matrix.vecMulVec, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_assoc, mul_comm, mul_left_comm, sq ] ; ring;
          simp +decide [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, e ] ; ring;
          simp +decide [ Finset.sum_ite, Finset.filter_eq', Finset.filter_ne', SimpleGraph.neighborFinset ] ; ring;
          simp +decide [ Finset.sum_mul _ _ _, Finset.mul_sum, Finset.sum_add_distrib, sub_eq_add_neg ] ; ring;
          simp +decide [ sub_eq_add_neg, SimpleGraph.neighborSet ];
        -- By definition of $L_S$, we can expand the sum $\sum_{v \in S} (x^T L_S x)$.
        have h_expand_LS : (Star.star x ⬝ᵥ (Ls G S) *ᵥ x) = (1 / 2 : ℝ) * ∑ v ∈ S, ∑ u ∈ S, (if G.Adj v u then ((x v - x u) ^ 2) else 0) := by
          have h_expand_LS : (Star.star x ⬝ᵥ (Ls G S) *ᵥ x) = ∑ v ∈ S, ∑ u ∈ S, (if G.Adj v u then ((x v - x u) ^ 2) else 0) / 2 := by
            have h_laplacian : ∀ (H : SimpleGraph V), (Star.star x ⬝ᵥ (H.lapMatrix ℝ) *ᵥ x) = ∑ v, ∑ u, (if H.Adj v u then ((x v - x u) ^ 2) else 0) / 2 := by
              intro H
              simp [SimpleGraph.lapMatrix];
              simp +decide [ Matrix.mulVec, dotProduct, Finset.sum_div _ _ _ ];
              simp +decide [ SimpleGraph.degMatrix, Finset.sum_add_distrib, sub_mul, mul_sub, sq, Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, div_eq_inv_mul ];
              simp +decide [ Matrix.diagonal, Finset.sum_ite, Finset.filter_ne, Finset.filter_eq, SimpleGraph.degree, SimpleGraph.neighborFinset_def ] ; ring;
              simp +decide [ ← Finset.sum_mul _ _ _, ← Finset.mul_sum ] ; ring;
              simp +decide [ Finset.sum_filter, SimpleGraph.adj_comm ] ; ring;
              rw [ show ( ∑ v : V, ∑ w : V, if H.Adj v w then x w ^ 2 else 0 ) = ∑ v : V, ∑ w : V, if H.Adj v w then x v ^ 2 else 0 from ?_ ] ; ring;
              · simp +decide [ Finset.sum_ite, SimpleGraph.adj_comm ] ; ring;
                simpa only [ mul_comm ] using by ring;
              · rw [ Finset.sum_comm ];
                simp +decide only [adj_comm]
            convert h_laplacian ( restrictToFinset G S ) using 1;
            rw [ ← Finset.sum_subset ( Finset.subset_univ S ) ];
            · refine' Finset.sum_congr rfl fun v hv => _;
              rw [ ← Finset.sum_subset ( Finset.subset_univ S ) ];
              · exact Finset.sum_congr rfl fun u hu => by unfold restrictToFinset; aesop;
              · simp +contextual [ restrictToFinset ];
            · simp +contextual [ restrictToFinset ];
          rw [ h_expand_LS, Finset.mul_sum _ _ _ ] ; exact Finset.sum_congr rfl fun _ _ => by rw [ Finset.mul_sum _ _ _ ] ; exact Finset.sum_congr rfl fun _ _ => by split_ifs <;> ring;
        -- By combining the results from h_expand and h_expand_LS, we can conclude the proof.
        have h_combined : ∑ v ∈ S, ∑ u ∈ G.neighborFinset v, ((x v - x u) ^ 2) ≥ ∑ v ∈ S, ∑ u ∈ S, (if G.Adj v u then ((x v - x u) ^ 2) else 0) := by
          refine' Finset.sum_le_sum fun v hv => _;
          rw [ ← Finset.sum_filter ];
          exact Finset.sum_le_sum_of_subset_of_nonneg ( fun u hu => by aesop ) fun _ _ _ => sq_nonneg _;
        simp_all +decide [ Matrix.sub_mulVec ];
        convert mul_le_mul_of_nonneg_left h_combined ( by norm_num : ( 0 : ℝ ) ≤ 2⁻¹ ) using 1;
        convert h_expand using 1;
        simp +decide [ Matrix.mulVec, dotProduct, Finset.mul_sum _ _ _, Finset.sum_mul ];
        simp +decide [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul, Matrix.sum_apply ];
        exact Eq.symm ( by rw [ Finset.sum_comm ] ; exact Finset.sum_congr rfl fun _ _ => Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by ring ) )
