/-
# Voevodsky Milnor
Category: Frontier — Fields Medal Work
Target: Frontier.voevodsky_milnor
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

-- (Lean requires `import` to precede any module docstring, so the header above is repeated
-- below as the module docstring of this file.)

import Mathlib

/-!
# Voevodsky Milnor
Category: Frontier — Fields Medal Work
Target: Frontier.voevodsky_milnor
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 400000
set_option synthInstance.maxSize 512

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
## The Milnor conjecture (Voevodsky's theorem)

For a field `F` of characteristic `≠ 2`, the norm residue homomorphism
`K_n^M(F)/2 → H^n(Gal(F_sep/F), ℤ/2)` is an isomorphism for every `n`.

This file sets up both sides of the statement inside Mathlib:

* the mod-`2` Milnor `K`-theory `Frontier.MilnorKMod2 F n`, defined as the `n`-th tensor
  power over `𝔽₂ = ZMod 2` of the group of square classes `F^×/(F^×)²`, modulo the
  submodule generated by the Steinberg relations `{a, 1 - a}`;
* the mod-`2` Galois cohomology `Frontier.GaloisCohMod2 F n`, defined as Mathlib's
  *continuous* (profinite) cohomology `continuousCohomology` of the absolute Galois group
  `Gal(F_sep/F)`, equipped with its Krull topology, with coefficients in the trivial
  discrete module `ZMod 2`.

The full theorem of Voevodsky is far out of reach of a formal development at present.  What is
proved here is the **base case** `n = 0`, in the sharp form that *both* sides are canonically
isomorphic to `ℤ/2`:

* `Frontier.milnorKMod2ZeroEquiv : MilnorKMod2 F 0 ≃ₗ[ZMod 2] ZMod 2`;
* `Frontier.galoisCohMod2ZeroEquiv : GaloisCohMod2 F 0 ≃ₗ[ZMod 2] ZMod 2`
  (this is `H⁰(G, M) = M^G` together with triviality of the action);
* `Frontier.voevodsky_milnor : MilnorConjectureDegree F 0`, the resulting degree-zero
  instance of the conjecture, valid for every field `F`.

Alongside this, the degree-one identification `K₁^M(F)/2 ≅ F^×/(F^×)²` is proved
(`Frontier.milnorKMod2OneEquiv`), the Steinberg relation is verified in the quotient
(`Frontier.steinberg_symbol_eq_zero`), and the vanishing of `K_n^M(F)/2` for `n ≥ 1` over a
separably closed field is proved (`Frontier.subsingleton_milnorKMod2_of_isSepClosed`).

Caveat on the formalisation of the statement: `MilnorConjectureDegree F n` asserts the
*existence* of an isomorphism of `𝔽₂`-vector spaces between the two sides rather than the
bijectivity of the norm residue map itself (whose construction requires substantially more
machinery than is currently available).  In degree `0` the two formulations agree, since both
sides are one-dimensional over `𝔽₂` there.
-/

namespace Frontier

open CategoryTheory

universe u

section MilnorK

variable (F : Type u) [Field F]

/-- The subgroup of squares of `F^×`. -/
def squares : Subgroup Fˣ := (powMonoidHom 2 : Fˣ →* Fˣ).range

/-- The group of square classes `F^×/(F^×)²`, written additively.  This is the degree-one part
of mod-`2` Milnor `K`-theory. -/
def SquareClass : Type u := Additive (Fˣ ⧸ squares F)

instance : AddCommGroup (SquareClass F) := inferInstanceAs (AddCommGroup (Additive _))

variable {F} in
/-- The square class of a unit of `F`. -/
def sqClass (u : Fˣ) : SquareClass F := Additive.ofMul (QuotientGroup.mk u)

lemma sq_eq_one (y : Fˣ ⧸ squares F) : y ^ 2 = 1 := by
  induction y using QuotientGroup.induction_on with
  | H u => rw [← QuotientGroup.mk_pow]; exact (QuotientGroup.eq_one_iff _).2 ⟨u, rfl⟩

lemma two_nsmul_squareClass (x : SquareClass F) : (2 : ℕ) • x = 0 := by
  simpa [← ofMul_pow] using congrArg Additive.ofMul (sq_eq_one F (Additive.toMul x))

instance : Module (ZMod 2) (SquareClass F) := AddCommGroup.zmodModule (two_nsmul_squareClass F)

/-- The `n`-th tensor power over `𝔽₂` of the space of square classes. -/
abbrev SquareClassPow (n : ℕ) : Type u :=
  PiTensorProduct (ZMod 2) (fun _ : Fin n => SquareClass F)

/-- The set of Steinberg relations in degree `n`: pure tensors
`{a₀} ⊗ ⋯ ⊗ {a_{n-1}}` in which two adjacent entries satisfy `a_i + a_{i+1} = 1`. -/
def steinbergRelations (n : ℕ) : Set (SquareClassPow F n) :=
  {x | ∃ (a : Fin n → Fˣ) (i : Fin n) (h : (i : ℕ) + 1 < n),
      ((a i : F) + (a ⟨(i : ℕ) + 1, h⟩ : F) = 1) ∧
      x = PiTensorProduct.tprod (ZMod 2) (fun k => sqClass (a k))}

/-- Mod-`2` Milnor `K`-theory `K_n^M(F)/2`: the `n`-th tensor power of `F^×/(F^×)²` over `𝔽₂`
modulo the Steinberg relations. -/
def MilnorKMod2 (n : ℕ) : Type u :=
  SquareClassPow F n ⧸ Submodule.span (ZMod 2) (steinbergRelations F n)

instance (n : ℕ) : AddCommGroup (MilnorKMod2 F n) :=
  inferInstanceAs (AddCommGroup (_ ⧸ Submodule.span (ZMod 2) (steinbergRelations F n)))

instance (n : ℕ) : Module (ZMod 2) (MilnorKMod2 F n) :=
  inferInstanceAs (Module (ZMod 2) (_ ⧸ Submodule.span (ZMod 2) (steinbergRelations F n)))

/-- The symbol map: a tuple of units gives a class in `K_n^M(F)/2`. -/
def symbol {n : ℕ} (a : Fin n → Fˣ) : MilnorKMod2 F n :=
  Submodule.Quotient.mk (PiTensorProduct.tprod (ZMod 2) (fun k => sqClass (a k)))

variable {F} in
/-- The Steinberg relation holds in `K_n^M(F)/2`: a symbol containing two adjacent entries
summing to `1` vanishes. -/
theorem steinberg_symbol_eq_zero {n : ℕ} (a : Fin n → Fˣ) (i : Fin n) (h : (i : ℕ) + 1 < n)
    (ha : (a i : F) + (a ⟨(i : ℕ) + 1, h⟩ : F) = 1) : symbol F a = 0 := by
  refine (Submodule.Quotient.mk_eq_zero _).2 (Submodule.subset_span ?_)
  exact ⟨a, i, h, ha, rfl⟩

lemma steinbergRelations_zero : steinbergRelations F 0 = ∅ := by
  ext x; simp [steinbergRelations]

lemma steinbergRelations_one : steinbergRelations F 1 = ∅ := by
  ext x
  simp only [steinbergRelations, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
  rintro ⟨a, i, h, -⟩
  omega

/-- `K₀^M(F)/2 ≅ ℤ/2`. -/
noncomputable def milnorKMod2ZeroEquiv : MilnorKMod2 F 0 ≃ₗ[ZMod 2] ZMod 2 :=
  (Submodule.quotEquivOfEqBot _ (by rw [steinbergRelations_zero, Submodule.span_empty])).trans
    (PiTensorProduct.isEmptyEquiv (Fin 0))

/-- `K₁^M(F)/2 ≅ F^×/(F^×)²`. -/
noncomputable def milnorKMod2OneEquiv : MilnorKMod2 F 1 ≃ₗ[ZMod 2] SquareClass F :=
  (Submodule.quotEquivOfEqBot _ (by rw [steinbergRelations_one, Submodule.span_empty])).trans
    (PiTensorProduct.subsingletonEquiv 0)

end MilnorK

section GaloisCohomology

variable (F : Type u) [Field F]

/-- The absolute Galois group `Gal(F_sep/F)`, a profinite group via the Krull topology. -/
abbrev AbsGalois : Type u := SeparableClosure F ≃ₐ[F] SeparableClosure F

/-- `ℤ/2` with the discrete topology and the trivial action of the absolute Galois group. -/
def trivialRep : Action (TopModuleCat (ZMod 2)) (AbsGalois F) where
  V := TopModuleCat.of (ZMod 2) (ZMod 2)
  ρ := 1

/-- Mod-`2` Galois cohomology `H^n(Gal(F_sep/F), ℤ/2)`, defined as continuous (profinite)
cohomology of the absolute Galois group with trivial coefficients `ℤ/2`. -/
noncomputable def GaloisCohMod2 (n : ℕ) : Type u :=
  ((continuousCohomology (ZMod 2) (AbsGalois F) n).obj (trivialRep F) : TopModuleCat (ZMod 2))

noncomputable instance (n : ℕ) : AddCommGroup (GaloisCohMod2 F n) :=
  inferInstanceAs (AddCommGroup
    ((continuousCohomology (ZMod 2) (AbsGalois F) n).obj (trivialRep F) : TopModuleCat (ZMod 2)))

noncomputable instance (n : ℕ) : Module (ZMod 2) (GaloisCohMod2 F n) :=
  inferInstanceAs (Module (ZMod 2)
    ((continuousCohomology (ZMod 2) (AbsGalois F) n).obj (trivialRep F) : TopModuleCat (ZMod 2)))

/-- `H⁰_cont(G, M) ≅ M^G`, specialised to the trivial `ℤ/2`-representation. -/
noncomputable def galoisCohMod2ZeroEquivInvariants : GaloisCohMod2 F 0 ≃ₗ[ZMod 2]
    ((ContinuousCohomology.invariants (ZMod 2) (AbsGalois F)).obj (trivialRep F) :
      TopModuleCat (ZMod 2)) :=
  ((ContinuousCohomology.continuousCohomologyZeroIso (ZMod 2)
    (AbsGalois F)).app (trivialRep F)).toContinuousLinearEquiv.toLinearEquiv

/-- The invariants of the trivial representation `ℤ/2` are all of `ℤ/2`. -/
noncomputable def invariantsTrivialRepEquiv :
    (((ContinuousCohomology.invariants (ZMod 2) (AbsGalois F)).obj (trivialRep F) :
      TopModuleCat (ZMod 2)) : Type) ≃ₗ[ZMod 2] ZMod 2 :=
  (LinearEquiv.ofEq (R := ZMod 2) (M := ZMod 2) _ ⊤ (by ext x; simp [trivialRep])).trans
    Submodule.topEquiv

/-- `H⁰(Gal(F_sep/F), ℤ/2) ≅ ℤ/2`. -/
noncomputable def galoisCohMod2ZeroEquiv : GaloisCohMod2 F 0 ≃ₗ[ZMod 2] ZMod 2 :=
  (galoisCohMod2ZeroEquivInvariants F).trans (invariantsTrivialRepEquiv F)

end GaloisCohomology

section Statement

variable (F : Type u) [Field F]

/-- The Milnor conjecture in degree `n` for the field `F`: mod-`2` Milnor `K`-theory in degree
`n` is isomorphic to degree-`n` mod-`2` Galois cohomology. -/
def MilnorConjectureDegree (n : ℕ) : Prop :=
  Nonempty (MilnorKMod2 F n ≃ₗ[ZMod 2] GaloisCohMod2 F n)

/-- The Milnor conjecture for the field `F`: mod-`2` Milnor `K`-theory agrees with mod-`2`
Galois cohomology in every degree. -/
def MilnorConjecture : Prop := ∀ n, MilnorConjectureDegree F n

/-- **The Milnor conjecture in degree zero** (base case of Voevodsky's theorem): for every
field `F`, `K₀^M(F)/2 ≅ H⁰(Gal(F_sep/F), ℤ/2)`; indeed both sides are `ℤ/2`. -/
theorem voevodsky_milnor : MilnorConjectureDegree F 0 :=
  ⟨(milnorKMod2ZeroEquiv F).trans (galoisCohMod2ZeroEquiv F).symm⟩

end Statement

end Frontier

