import Mathlib

/-!
# Higgs Mass Toy
Category: Frontier Physics
Target: Frontier.higgs_mass_toy
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

namespace Frontier

/-- The "Mexican hat" scalar potential of the abelian Higgs model, written as a
function of the modulus `r = |φ|` of the complex scalar field:
`V(r) = lam * (r² - v²)²`. -/
noncomputable def higgsPotential (lam v r : ℝ) : ℝ := lam * (r ^ 2 - v ^ 2) ^ 2

/-- The quadratic term in the gauge field `A` coming from the covariant kinetic
term `|D φ|²` with `D φ = (∂ - i g A) φ`, evaluated on a configuration of
constant modulus `r`: `g² r² A²`. -/
noncomputable def gaugeQuadratic (g r A : ℝ) : ℝ := g ^ 2 * r ^ 2 * A ^ 2

/-- The gauge boson mass squared generated by a vacuum expectation value `v`. -/
noncomputable def gaugeMassSq (g v : ℝ) : ℝ := g ^ 2 * v ^ 2

/-- The Mexican-hat potential as a function of the complex scalar field itself:
`V(φ) = lam (|φ|² - v²)²`. -/
noncomputable def higgsPotentialC (lam v : ℝ) (phi : ℂ) : ℝ :=
  lam * (‖phi‖ ^ 2 - v ^ 2) ^ 2

/-- The `U(1)` covariant derivative `D φ = ∂φ - i g A φ`, where `dphi` stands for the
ordinary derivative `∂φ` and `A` is the (real) gauge potential. -/
noncomputable def covD (g A : ℝ) (dphi phi : ℂ) : ℂ :=
  dphi - Complex.I * ((g * A : ℝ) : ℂ) * phi

/-- The gauge kinetic energy `|D φ|²`. -/
noncomputable def gaugeKinetic (g A : ℝ) (dphi phi : ℂ) : ℝ := ‖covD g A dphi phi‖ ^ 2

/-- The complex-field potential only depends on the modulus of the field. -/
lemma higgsPotentialC_eq_higgsPotential (lam v : ℝ) (phi : ℂ) :
    higgsPotentialC lam v phi = higgsPotential lam v ‖phi‖ := rfl

/-- The potential is invariant under global `U(1)` phase rotations `φ ↦ e^{iθ} φ`. -/
lemma higgsPotentialC_gauge_invariant (lam v theta : ℝ) (phi : ℂ) :
    higgsPotentialC lam v (Complex.exp (theta * Complex.I) * phi)
      = higgsPotentialC lam v phi := by
  simp [higgsPotentialC]

/-- The kinetic term is invariant under global `U(1)` phase rotations. -/
lemma gaugeKinetic_gauge_invariant (g A theta : ℝ) (dphi phi : ℂ) :
    gaugeKinetic g A (Complex.exp (theta * Complex.I) * dphi)
      (Complex.exp (theta * Complex.I) * phi) = gaugeKinetic g A dphi phi := by
  have h : covD g A (Complex.exp (theta * Complex.I) * dphi)
      (Complex.exp (theta * Complex.I) * phi)
      = Complex.exp (theta * Complex.I) * covD g A dphi phi := by
    simp [covD]; ring
  simp [gaugeKinetic, h]

/-- The zero set of the potential is exactly the vacuum circle `|φ| = v`. -/
lemma higgsPotentialC_eq_zero_iff (lam v : ℝ) (hlam : 0 < lam) (phi : ℂ) :
    higgsPotentialC lam v phi = 0 ↔ ‖phi‖ ^ 2 = v ^ 2 := by
  simp only [higgsPotentialC]
  constructor
  · intro h
    rcases mul_eq_zero.1 h with h' | h'
    · exact absurd h' hlam.ne'
    · have := pow_eq_zero_iff (n := 2) (by norm_num) |>.1 h'
      linarith
  · intro h; rw [h]; ring

/-- On the vacuum configuration `φ = v` (constant, so `∂φ = 0`) the covariant kinetic
term reduces to the gauge boson mass term `m_A² A²`. -/
lemma gaugeKinetic_vacuum (g v A : ℝ) :
    gaugeKinetic g A 0 ((v : ℝ) : ℂ) = gaugeMassSq g v * A ^ 2 := by
  have h : covD g A 0 ((v : ℝ) : ℂ) = Complex.I * (-((g * A * v : ℝ) : ℂ)) := by
    simp [covD]; ring
  simp only [gaugeKinetic, h, gaugeMassSq, norm_mul, Complex.norm_I, one_mul,
    norm_neg, Complex.norm_real, Real.norm_eq_abs]
  simp [mul_pow, sq_abs]
  ring

/-- At the symmetric point `φ = 0` no mass term is generated: the gauge field is massless. -/
lemma gaugeKinetic_symmetric (g A : ℝ) : gaugeKinetic g A 0 0 = 0 := by
  simp [gaugeKinetic, covD]

lemma higgsPotential_hasDerivAt (lam v r : ℝ) :
    HasDerivAt (higgsPotential lam v) (4 * lam * r * (r ^ 2 - v ^ 2)) r := by
  have h : HasDerivAt (fun x : ℝ => x ^ 2 - v ^ 2) (2 * r) r := by
    simpa using (hasDerivAt_pow 2 r).sub_const (v ^ 2)
  have h2 : HasDerivAt (fun x : ℝ => lam * (x ^ 2 - v ^ 2) ^ 2)
      (lam * (2 * (r ^ 2 - v ^ 2) ^ (2 - 1) * (2 * r))) r := (h.pow 2).const_mul lam
  refine h2.congr_deriv ?_
  simp
  ring

lemma deriv_higgsPotential (lam v : ℝ) :
    deriv (higgsPotential lam v) = fun r => 4 * lam * r * (r ^ 2 - v ^ 2) := by
  funext r
  exact (higgsPotential_hasDerivAt lam v r).deriv

lemma deriv2_higgsPotential (lam v : ℝ) :
    deriv (deriv (higgsPotential lam v)) = fun r => 4 * lam * (3 * r ^ 2 - v ^ 2) := by
  funext r
  rw [deriv_higgsPotential]
  have h : HasDerivAt (fun r : ℝ => 4 * lam * r * (r ^ 2 - v ^ 2))
      (4 * lam * (3 * r ^ 2 - v ^ 2)) r := by
    have h1 : HasDerivAt (fun x : ℝ => 4 * lam * x) (4 * lam) r := by
      simpa using (hasDerivAt_id r).const_mul (4 * lam)
    have h2 : HasDerivAt (fun x : ℝ => x ^ 2 - v ^ 2) (2 * r) r := by
      simpa using (hasDerivAt_pow 2 r).sub_const (v ^ 2)
    have := h1.mul h2
    refine this.congr_deriv ?_
    ring
  exact h.deriv

/-- **Abelian Higgs toy model: spontaneous symmetry breaking gives the gauge boson a mass.**

For a `U(1)` gauge coupling `g > 0`, quartic coupling `lam > 0` and symmetry breaking
scale `v > 0`:

* the Mexican-hat potential `V(r) = lam (r² - v²)²` is minimized at the broken vacuum
  `r = v`, where it vanishes, and the symmetric point `r = 0` is *not* a minimum
  (`V(0) > V(v)`), i.e. the symmetry is spontaneously broken;
* `r = v` is a genuine stationary point with positive curvature, the physical Higgs
  mass squared being `V''(v) = 8 lam v² > 0`;
* expanding the covariant kinetic term about the vacuum produces the quadratic gauge
  term `g² v² A²`, i.e. a mass squared `m_A² = g² v² > 0` with `m_A = g v > 0`,
  whereas about the symmetric point `r = 0` the gauge field stays massless;
* in the complex-field formulation, `V(φ) = lam (|φ|² - v²)²` is nonnegative and vanishes
  exactly on the vacuum circle `|φ| = v` (a degenerate vacuum manifold, the origin of the
  Goldstone mode), both `V` and the covariant kinetic term `|Dφ|²`, `Dφ = ∂φ - i g A φ`,
  are invariant under global `U(1)` rotations `φ ↦ e^{iθ} φ`, and evaluating `|Dφ|²` on the
  constant vacuum `φ = v` produces exactly the gauge mass term `m_A² A²`, while at `φ = 0`
  it vanishes. -/
theorem higgs_mass_toy (g v lam A : ℝ) (hg : 0 < g) (hv : 0 < v) (hlam : 0 < lam) :
    -- the broken vacuum `r = v` is a global minimum of the potential, with zero energy
    (∀ r : ℝ, higgsPotential lam v v ≤ higgsPotential lam v r) ∧
      higgsPotential lam v v = 0 ∧
      -- the symmetric point is not a minimum: the symmetry is broken
      higgsPotential lam v v < higgsPotential lam v 0 ∧
      -- stationarity and positive curvature (physical Higgs mass squared)
      deriv (higgsPotential lam v) v = 0 ∧
      deriv (deriv (higgsPotential lam v)) v = 8 * lam * v ^ 2 ∧
      0 < deriv (deriv (higgsPotential lam v)) v ∧
      -- the gauge field acquires the mass term `m_A² A²` about the broken vacuum
      (∀ a : ℝ, gaugeQuadratic g v a = gaugeMassSq g v * a ^ 2) ∧
      0 < gaugeMassSq g v ∧
      Real.sqrt (gaugeMassSq g v) = g * v ∧
      0 < g * v ∧
      -- while about the symmetric point the gauge field remains massless
      (∀ a : ℝ, gaugeQuadratic g 0 a = 0) ∧
      -- complex-field formulation: the vacuum manifold is the circle `|φ| = v`,
      -- and the potential and kinetic term are `U(1)` invariant
      (∀ phi : ℂ, 0 ≤ higgsPotentialC lam v phi) ∧
      (∀ phi : ℂ, higgsPotentialC lam v phi = 0 ↔ ‖phi‖ = v) ∧
      (∀ (theta : ℝ) (phi : ℂ),
        higgsPotentialC lam v (Complex.exp (theta * Complex.I) * phi)
          = higgsPotentialC lam v phi) ∧
      (∀ (theta : ℝ) (dphi phi : ℂ),
        gaugeKinetic g A (Complex.exp (theta * Complex.I) * dphi)
            (Complex.exp (theta * Complex.I) * phi) = gaugeKinetic g A dphi phi) ∧
      -- the covariant kinetic term on the constant vacuum `φ = v` *is* the mass term
      gaugeKinetic g A 0 ((v : ℝ) : ℂ) = gaugeMassSq g v * A ^ 2 ∧
      -- and it vanishes identically at the symmetric point `φ = 0`
      gaugeKinetic g A 0 0 = 0 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro r
    have : (0:ℝ) ≤ lam * (r ^ 2 - v ^ 2) ^ 2 :=
      mul_nonneg hlam.le (sq_nonneg _)
    simpa [higgsPotential] using this
  · simp [higgsPotential]
  · have h : (0:ℝ) < lam * v ^ 4 := by positivity
    simp only [higgsPotential]
    nlinarith [h]
  · rw [deriv_higgsPotential]; ring
  · rw [deriv2_higgsPotential]; ring
  · rw [deriv2_higgsPotential]
    have : (0:ℝ) < v ^ 2 := by positivity
    nlinarith
  · intro a; simp [gaugeQuadratic, gaugeMassSq]
  · have : (0:ℝ) < g ^ 2 * v ^ 2 := by positivity
    simpa [gaugeMassSq] using this
  · rw [gaugeMassSq, show g ^ 2 * v ^ 2 = (g * v) ^ 2 by ring]
    exact Real.sqrt_sq (by positivity)
  · positivity
  · intro a; simp [gaugeQuadratic]
  · intro phi
    have : (0:ℝ) ≤ lam * (‖phi‖ ^ 2 - v ^ 2) ^ 2 := mul_nonneg hlam.le (sq_nonneg _)
    simpa [higgsPotentialC] using this
  · intro phi
    rw [higgsPotentialC_eq_zero_iff lam v hlam phi]
    constructor
    · intro h; nlinarith [norm_nonneg phi]
    · intro h; rw [h]
  · intro theta phi; exact higgsPotentialC_gauge_invariant lam v theta phi
  · intro theta dphi phi; exact gaugeKinetic_gauge_invariant g A theta dphi phi
  · exact gaugeKinetic_vacuum g v A
  · exact gaugeKinetic_symmetric g A

end Frontier

