import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

import Mathlib

/-!
# Zelmanov Restricted Burnside
Category: Frontier — Fields Medal Work
Target: Frontier.zelmanov_restricted_burnside
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

open Finset

/-- The *restricted Burnside statement* for `d` generators and exponent `n`:
there is a uniform bound `B` on the order of every finite group that is generated by at
most `d` elements and in which every element satisfies `g ^ n = 1`.

Zelmanov's theorem (1990/91, Fields Medal 1994) is the assertion
`∀ d n, 0 < n → RestrictedBurnsideBounded d n`. -/
def RestrictedBurnsideBounded (d n : ℕ) : Prop :=
  ∃ B : ℕ, ∀ (G : Type) [Group G] [Fintype G] (S : Finset G),
    S.card ≤ d → (∀ g : G, g ^ n = 1) → Subgroup.closure (S : Set G) = ⊤ →
      Fintype.card G ≤ B

section CommCase

variable {G : Type*} [CommGroup G] [DecidableEq G] (hG : ∀ g : G, g ^ 2 = 1)

include hG

/-- In a commutative group of exponent dividing `2`, the product over a finset is unchanged
by removing a "doubled" part: multiplying two subset-products gives the subset-product over
the symmetric difference. -/
theorem prod_mul_prod_eq_prod_symmDiff (T₁ T₂ : Finset G) :
    (∏ t ∈ T₁, t) * (∏ t ∈ T₂, t) = ∏ t ∈ (symmDiff T₁ T₂), t := by
  have hunion : (∏ t ∈ symmDiff T₁ T₂, t) * (∏ t ∈ T₁ ∩ T₂, t) = ∏ t ∈ T₁ ∪ T₂, t := by
    rw [← Finset.prod_union]
    · congr 1
      ext x
      simp only [Finset.mem_union, Finset.mem_inter, Finset.mem_symmDiff]
      tauto
    · rw [Finset.disjoint_left]
      intro x hx hx'
      simp only [Finset.mem_symmDiff] at hx
      simp only [Finset.mem_inter] at hx'
      tauto
  have hsq : (∏ t ∈ T₁ ∩ T₂, t) * (∏ t ∈ T₁ ∩ T₂, t) = 1 := by
    rw [← sq, ← Finset.prod_pow]
    exact Finset.prod_eq_one fun x _ => hG x
  calc (∏ t ∈ T₁, t) * (∏ t ∈ T₂, t)
      = (∏ t ∈ T₁ ∪ T₂, t) * (∏ t ∈ T₁ ∩ T₂, t) := (Finset.prod_union_inter).symm
    _ = (∏ t ∈ symmDiff T₁ T₂, t) * ((∏ t ∈ T₁ ∩ T₂, t) * (∏ t ∈ T₁ ∩ T₂, t)) := by
          rw [← hunion]; exact mul_assoc _ _ _
    _ = ∏ t ∈ symmDiff T₁ T₂, t := by rw [hsq, mul_one]

/-- The set of products over subsets of `S` is a subgroup, in a commutative group of
exponent dividing `2`. -/
def subsetProducts (S : Finset G) : Subgroup G where
  carrier := {g | ∃ T ⊆ S, (∏ t ∈ T, t) = g}
  one_mem' := ⟨∅, Finset.empty_subset _, by simp⟩
  mul_mem' := by
    rintro a b ⟨T₁, hT₁, rfl⟩ ⟨T₂, hT₂, rfl⟩
    refine ⟨symmDiff T₁ T₂, ?_, (prod_mul_prod_eq_prod_symmDiff hG T₁ T₂).symm⟩
    intro x hx
    simp only [Finset.mem_symmDiff] at hx
    rcases hx with ⟨h, _⟩ | ⟨h, _⟩
    · exact hT₁ h
    · exact hT₂ h
  inv_mem' := by
    rintro a ⟨T, hT, rfl⟩
    refine ⟨T, hT, ?_⟩
    have := hG (∏ t ∈ T, t)
    rw [sq] at this
    exact (inv_eq_of_mul_eq_one_right this).symm

theorem closure_le_subsetProducts (S : Finset G) :
    Subgroup.closure (S : Set G) ≤ subsetProducts hG S := by
  rw [Subgroup.closure_le]
  intro x hx
  exact ⟨{x}, by simpa using hx, Finset.prod_singleton _ _⟩

/-- A finite commutative group of exponent dividing `2` generated by `S` has at most
`2 ^ S.card` elements. -/
theorem card_le_two_pow_card_of_closure_eq_top [Fintype G] (S : Finset G)
    (hS : Subgroup.closure (S : Set G) = ⊤) :
    Fintype.card G ≤ 2 ^ S.card := by
  have himg : (Finset.univ : Finset G) ⊆ S.powerset.image (fun T => ∏ t ∈ T, t) := by
    intro g _
    have hg : g ∈ subsetProducts hG S := by
      have := closure_le_subsetProducts hG S
      rw [hS] at this
      exact this (Subgroup.mem_top g)
    obtain ⟨T, hT, rfl⟩ := hg
    exact Finset.mem_image.2 ⟨T, Finset.mem_powerset.2 hT, rfl⟩
  calc Fintype.card G = (Finset.univ : Finset G).card := rfl
    _ ≤ (S.powerset.image (fun T => ∏ t ∈ T, t)).card := Finset.card_le_card himg
    _ ≤ S.powerset.card := Finset.card_image_le
    _ = 2 ^ S.card := Finset.card_powerset S

end CommCase

/-- A group in which every element squares to the identity is commutative.
(Compare `mul_comm_of_exponent_two`, which assumes `Monoid.exponent G = 2` exactly.) -/
theorem mul_comm_of_sq_eq_one {G : Type*} [Group G] (hG : ∀ g : G, g ^ 2 = 1) (a b : G) :
    a * b = b * a := by
  have hinv : ∀ g : G, g⁻¹ = g := by
    intro g
    have := hG g
    rw [sq] at this
    exact (inv_eq_of_mul_eq_one_right this)
  calc a * b = (a * b)⁻¹ := (hinv _).symm
    _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
    _ = b * a := by rw [hinv, hinv]

/-- **Restricted Burnside problem, verified base case (exponent 2).**

Zelmanov's theorem states that for all `d` and all `n > 0` the restricted Burnside statement
`RestrictedBurnsideBounded d n` holds, i.e. there are only finitely many finite `d`-generated
groups of exponent `n`, so a largest one exists.  Here we prove, fully formally, the base case
`n = 2`: a `d`-generated group of exponent dividing `2` is elementary abelian of rank at most
`d`, hence has order at most `2 ^ d`.  This bound is sharp, attained by `(ZMod 2) ^ d`. -/
theorem zelmanov_restricted_burnside (d : ℕ) : RestrictedBurnsideBounded d 2 := by
  refine ⟨2 ^ d, ?_⟩
  intro G _ _ S hSd hexp hgen
  letI : DecidableEq G := Classical.decEq G
  letI : CommGroup G := { (inferInstance : Group G) with
    mul_comm := mul_comm_of_sq_eq_one hexp }
  calc Fintype.card G ≤ 2 ^ S.card := card_le_two_pow_card_of_closure_eq_top hexp S hgen
    _ ≤ 2 ^ d := Nat.pow_le_pow_right (by norm_num) hSd

/-- The exponent `1` case: a group of exponent `1` is trivial, so the bound is `1`. -/
theorem restrictedBurnsideBounded_one (d : ℕ) : RestrictedBurnsideBounded d 1 := by
  refine ⟨1, ?_⟩
  intro G _ _ S _ hexp _
  have : ∀ g : G, g = 1 := by intro g; simpa using hexp g
  have hsub : (Finset.univ : Finset G) ⊆ {(1 : G)} := by
    intro g _; simp [this g]
  calc Fintype.card G = (Finset.univ : Finset G).card := rfl
    _ ≤ ({(1 : G)} : Finset G).card := Finset.card_le_card hsub
    _ = 1 := Finset.card_singleton 1

/-- Monotonicity in the number of generators: a bound for `d` generators bounds groups
generated by fewer elements. -/
theorem RestrictedBurnsideBounded.mono {d d' n : ℕ} (h : d' ≤ d)
    (hd : RestrictedBurnsideBounded d n) : RestrictedBurnsideBounded d' n := by
  obtain ⟨B, hB⟩ := hd
  exact ⟨B, fun G _ _ S hS hexp hgen => hB G S (hS.trans h) hexp hgen⟩

end Frontier

