import Mathlib
/-!
# Higgs Mass Toy
Category: Frontier Physics
Target: Frontier.higgs_mass_toy
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace Frontier

/-- The Mexican-hat scalar potential of the abelian Higgs toy model,
`V(x) = lam * (x ^ 2 - v ^ 2) ^ 2`, with quartic coupling `lam` and vacuum expectation
value `v`. -/
noncomputable def higgsPotential (lam v x : ℝ) : ℝ := lam * (x ^ 2 - v ^ 2) ^ 2

/-- The gauge boson mass generated by the Higgs mechanism in the abelian toy model,
`m = g * |v|`, for gauge coupling `g` and vacuum expectation value `v`. -/
noncomputable def gaugeMass (g v : ℝ) : ℝ := g * |v|

/--
**Abelian Higgs toy model: spontaneous symmetry breaking gives the gauge boson a mass.**

For a positive gauge coupling `g` and positive quartic coupling `lam`:

* the field value `v` is a global minimum of the Mexican-hat potential, with zero potential
  energy there;
* the gauge boson mass `g * |v|` vanishes exactly in the symmetric phase `v = 0`;
* in the spontaneously broken phase `v ≠ 0` the gauge boson mass is strictly positive and its
  square equals `g ^ 2 * v ^ 2`.
-/
theorem higgs_mass_toy (g lam v : ℝ) (hg : 0 < g) (hlam : 0 < lam) :
    (∀ x : ℝ, higgsPotential lam v v ≤ higgsPotential lam v x) ∧
      higgsPotential lam v v = 0 ∧
      (gaugeMass g v = 0 ↔ v = 0) ∧
      (v ≠ 0 → 0 < gaugeMass g v ∧ gaugeMass g v ^ 2 = g ^ 2 * v ^ 2) := by
  have hmin : higgsPotential lam v v = 0 := by simp [higgsPotential]
  refine ⟨fun x => ?_, hmin, ⟨fun h => ?_, fun h => ?_⟩, fun hv => ?_⟩
  · rw [hmin]
    exact mul_nonneg hlam.le (sq_nonneg _)
  · rcases mul_eq_zero.mp h with h' | h'
    · exact absurd h' hg.ne'
    · exact abs_eq_zero.mp h'
  · simp [gaugeMass, h]
  · refine ⟨mul_pos hg (abs_pos.mpr hv), ?_⟩
    rw [gaugeMass, mul_pow, sq_abs]

end Frontier

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

