/-
# Noether Conservation
Category: Frontier Physics
Target: Frontier.noether_conservation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace Frontier

/-- Expansion of a continuous linear functional on `ℝ × ℝ` in the standard basis. -/
lemma clm_prod_apply (f : ℝ × ℝ →L[ℝ] ℝ) (a b : ℝ) :
    f (a, b) = a * f (1, 0) + b * f (0, 1) := by
  have h : ((a, b) : ℝ × ℝ) = a • ((1, 0) : ℝ × ℝ) + b • ((0, 1) : ℝ × ℝ) := by
    simp
  rw [h, map_add, map_smul, map_smul, smul_eq_mul, smul_eq_mul]

/-- Infinitesimal invariance of the Lagrangian along the generator
`w = (X x, X' x * u)` forces the directional derivative `dL z w` to vanish. -/
lemma dL_apply_generator_eq_zero
    (L : ℝ × ℝ → ℝ) (dL : ℝ × ℝ → (ℝ × ℝ →L[ℝ] ℝ)) (X X' : ℝ → ℝ)
    (hL : ∀ z, HasFDerivAt L (dL z) z)
    (hinv : ∀ z : ℝ × ℝ,
      HasDerivAt (fun e : ℝ => L (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) 0 0)
    (z : ℝ × ℝ) : dL z (X z.1, X' z.1 * z.2) = 0 := by
  set w : ℝ × ℝ := (X z.1, X' z.1 * z.2) with hw
  have hc : HasDerivAt (fun e : ℝ => (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) w 0 := by
    have h1 : HasDerivAt (fun e : ℝ => z.1 + e * X z.1) (X z.1) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X z.1)).const_add z.1
    have h2 : HasDerivAt (fun e : ℝ => z.2 + e * (X' z.1 * z.2)) (X' z.1 * z.2) 0 := by
      simpa using ((hasDerivAt_id (0 : ℝ)).mul_const (X' z.1 * z.2)).const_add z.2
    exact h1.prodMk h2
  have hcomp : HasDerivAt
      (fun e : ℝ => L (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) (dL z w) 0 := by
    have := (hL ((fun e : ℝ => (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) 0)).comp_hasDerivAt 0 hc
    simpa using this
  exact hcomp.unique (hinv z)

/-- **Noether's theorem, one-dimensional case.**

For a Lagrangian `L : ℝ × ℝ → ℝ` (arguments: position and velocity) with derivative `dL`,
a path `q` with velocity `v`, and a smooth symmetry generator `X` (with derivative `X'`):

* `hEL` is the Euler–Lagrange equation: the time derivative of the conjugate momentum
  `p t = ∂L/∂v (q t, v t) = dL (q t, v t) (0,1)` equals `∂L/∂q (q t, v t) = dL (q t, v t) (1,0)`;
* `hinv` says the Lagrangian is invariant to first order under the flow generated by
  `x ↦ X x` on positions and its lift `u ↦ X' x * u` on velocities.

Then the Noether current `J t = p t * X (q t)` is conserved. -/
theorem noether_conservation
    (L : ℝ × ℝ → ℝ) (dL : ℝ × ℝ → (ℝ × ℝ →L[ℝ] ℝ))
    (q v X X' : ℝ → ℝ)
    (hL : ∀ z, HasFDerivAt L (dL z) z)
    (hv : ∀ t, HasDerivAt q (v t) t)
    (hX : ∀ x, HasDerivAt X (X' x) x)
    (hEL : ∀ t, HasDerivAt (fun s => dL (q s, v s) (0, 1)) (dL (q t, v t) (1, 0)) t)
    (hinv : ∀ z : ℝ × ℝ,
      HasDerivAt (fun e : ℝ => L (z.1 + e * X z.1, z.2 + e * (X' z.1 * z.2))) 0 0) :
    ∀ t s : ℝ, dL (q t, v t) (0, 1) * X (q t) = dL (q s, v s) (0, 1) * X (q s) := by
  set J : ℝ → ℝ := fun t => dL (q t, v t) (0, 1) * X (q t) with hJ
  have hJderiv : ∀ t, HasDerivAt J 0 t := by
    intro t
    have hXq : HasDerivAt (fun s => X (q s)) (X' (q t) * v t) t := (hX (q t)).comp t (hv t)
    have hprod := (hEL t).mul hXq
    have hzero : dL (q t, v t) (1, 0) * X (q t)
        + dL (q t, v t) (0, 1) * (X' (q t) * v t) = 0 := by
      have h := dL_apply_generator_eq_zero L dL X X' hL hinv (q t, v t)
      rw [clm_prod_apply] at h
      simpa [mul_comm] using h
    rw [hzero] at hprod
    exact hprod
  intro t s
  exact is_const_of_deriv_eq_zero (fun t => (hJderiv t).differentiableAt)
    (fun t => (hJderiv t).deriv) t s

end Frontier

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

