/-
# Mordell Finite Generation
Category: Frontier — Prime Numbers
Target: Frontier.Mordell_finite_generation
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

import Mathlib

namespace Frontier

open scoped Pointwise

/-!
## The statement

Mordell's theorem asserts that for an elliptic curve `E` over `ℚ`, the abelian group `E(ℚ)` of
rational points is finitely generated.  In Mathlib an elliptic curve over `ℚ` is a Weierstrass
curve `W : WeierstrassCurve ℚ` satisfying the typeclass assumption `W.IsElliptic`, and its group
of rational points is `W.toAffine.Point`, which carries an `AddCommGroup` structure.

Mathlib (at the pinned commit) contains no form of the Mordell–Weil theorem: searching for
`MordellWeil` returns nothing, and the theory developed in
`Mathlib.AlgebraicGeometry.EllipticCurve.*` stops at the group law, division polynomials and
reduction.  So the statement below is a genuine formalization, and what is proved here is the
classical *descent step*: the reduction of Mordell's theorem to the two inputs of the standard
proof, namely

* the weak Mordell–Weil theorem (`E(ℚ)/2E(ℚ)` is finite), and
* the theory of the canonical height (heights have finite sublevel sets, and every point of large
  height can be brought down by subtracting a coset representative and halving).

Both inputs are packaged in `Frontier.DescentData`.
-/

/-- The full Mordell–Weil statement over `ℚ`: the group of rational points of every elliptic
curve over `ℚ` is finitely generated.  (Stated only; the theorem proved below is the descent
reduction `Frontier.Mordell_finite_generation`.) -/
def MordellStatement : Prop :=
  ∀ (W : WeierstrassCurve ℚ), W.IsElliptic → AddGroup.FG W.toAffine.Point

/-- Descent data on an abelian group `A`: a height function with finite sublevel sets, together
with a finite set `reps` of representatives (of `A / 2A`) such that any point of height exceeding
`bound` can be written as `r + 2 • b` with `r ∈ reps` and `b` of strictly smaller height.

For `A = E(ℚ)` this is exactly what the weak Mordell–Weil theorem plus the standard height
estimates provide. -/
structure DescentData (A : Type*) [AddCommGroup A] where
  /-- The height function. -/
  height : A → ℕ
  /-- The height threshold above which descent is possible. -/
  bound : ℕ
  /-- A finite set of representatives for `A / 2A`. -/
  reps : Finset A
  /-- Sublevel sets of the height are finite (Northcott property). -/
  finite_height_le : ∀ C : ℕ, {a : A | height a ≤ C}.Finite
  /-- Descent step: a point of large height is a representative plus twice a smaller point. -/
  descent : ∀ a : A, bound < height a → ∃ b : A, height b < height a ∧ a - 2 • b ∈ reps

/-- **Infinite descent.**  An abelian group carrying descent data is finitely generated:
it is generated by the (finite) set of points of height at most `bound` together with the
representatives. -/
theorem fg_of_descentData {A : Type*} [AddCommGroup A] (D : DescentData A) : AddGroup.FG A := by
  classical
  set T : Set A := {a : A | D.height a ≤ D.bound} ∪ (D.reps : Set A) with hT
  have hTfin : T.Finite := (D.finite_height_le D.bound).union D.reps.finite_toSet
  have key : ∀ n : ℕ, ∀ a : A, D.height a ≤ n → a ∈ AddSubgroup.closure T := by
    intro n
    induction n using Nat.strong_induction_on with
    | _ n ih =>
      intro a ha
      by_cases hb : D.height a ≤ D.bound
      · exact AddSubgroup.subset_closure (Or.inl hb)
      · obtain ⟨b, hlt, hmem⟩ := D.descent a (not_le.mp hb)
        have hbmem : b ∈ AddSubgroup.closure T :=
          ih (D.height b) (lt_of_lt_of_le hlt ha) b le_rfl
        have hrep : a - 2 • b ∈ AddSubgroup.closure T :=
          AddSubgroup.subset_closure (Or.inr hmem)
        have : a = (a - 2 • b) + 2 • b := by abel
        rw [this]
        exact add_mem hrep (nsmul_mem hbmem 2)
  refine AddGroup.fg_iff.mpr ⟨T, ?_, hTfin⟩
  refine eq_top_iff.mpr fun a _ => key (D.height a) a le_rfl

/-- **Mordell's theorem, reduced to descent.**  If the group of rational points of an elliptic
curve over `ℚ` admits descent data — i.e. the weak Mordell–Weil theorem together with the
Northcott property and the descent inequality for the height — then `E(ℚ)` is finitely
generated. -/
theorem Mordell_finite_generation (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (D : DescentData W.toAffine.Point) : AddGroup.FG W.toAffine.Point :=
  fg_of_descentData D

/-- The reduction, in the form of the full statement: if every elliptic curve over `ℚ` admits
descent data on its group of rational points, then Mordell's theorem holds. -/
theorem MordellStatement_of_descentData
    (H : ∀ (W : WeierstrassCurve ℚ), W.IsElliptic → Nonempty (DescentData W.toAffine.Point)) :
    MordellStatement := by
  intro W hW
  obtain ⟨D⟩ := H W hW
  exact fg_of_descentData D

/-- Base case: a rank-zero situation.  If `E(ℚ)` is finite then it is finitely generated
(unconditionally). -/
theorem fg_of_finite_points (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (h : Finite W.toAffine.Point) : AddGroup.FG W.toAffine.Point :=
  AddGroup.fg_iff.mpr ⟨Set.univ, by simp, Set.finite_univ⟩

/-!
## Non-vacuity of the hypothesis

Descent data is a satisfiable notion: the integers carry it (with the height `|·|`, threshold `1`
and representatives `{0, 1}` for `ℤ / 2ℤ`), and the descent theorem then recovers the finite
generation of `ℤ`.
-/

/-- Descent data on `ℤ`, showing that `Frontier.DescentData` is a satisfiable hypothesis. -/
def intDescentData : DescentData ℤ where
  height a := a.natAbs
  bound := 1
  reps := {0, 1}
  finite_height_le C := by
    apply Set.Finite.subset (Set.finite_Icc (-(C : ℤ)) (C : ℤ))
    intro x hx
    simp only [Set.mem_setOf_eq] at hx
    simp only [Set.mem_Icc]
    omega
  descent a ha := by
    refine ⟨a / 2, ?_, ?_⟩
    · omega
    · simp only [Finset.mem_insert, Finset.mem_singleton, nsmul_eq_mul, Nat.cast_ofNat]
      omega

example : AddGroup.FG ℤ := fg_of_descentData intDescentData

end Frontier

