/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b5ca580a-4872-4c8b-8a91-7235f3ca1af8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Checking if completedRiemannZeta is available at the top level.
-/
#check completedRiemannZeta

/-
Defining completedZeta as an alias for completedRiemannZeta from Mathlib.
-/
noncomputable def completedZeta : ℂ → ℂ := completedRiemannZeta

/-
The Universal Interface Hypothesis asserts the existence of a function G and a spectral interpretation of the completed zeta function. Specifically:
1. There exists a nowhere-vanishing function G such that D(s(1-s), τ) = Λ(s)G(s).
2. The operator D has real spectrum (if D(u, τ) = 0 then u is real).
3. The parameter space P is non-empty.
-/
def UniversalInterfaceHypothesis (P : Type) (D : ℂ → P → ℂ) : Prop :=
  ∃ G : ℂ → ℂ,
    (∀ s τ, D (s * (1 - s)) τ = completedZeta s * G s) ∧
    (∀ s, G s ≠ 0) ∧
    (∀ u τ, D u τ = 0 → u.im = 0) ∧
    (∃ τ : P, True)

/-
The Euler-Mascheroni constant is less than log(4π).
-/
lemma gamma_lt_log_four_pi : Real.eulerMascheroniConstant < Real.log (4 * Real.pi) := by
  -- We know that $\gamma \approx 0.577$ and $\log(4\pi) \approx 2.531$, so $\gamma < \log(4\pi)$.
  have h_gamma_lt_log : Real.eulerMascheroniConstant < 1 := by
    have h_gamma_lt_two_thirds : Real.eulerMascheroniConstant < 2 / 3 := by
      exact?
    linarith [h_gamma_lt_two_thirds];
  exact h_gamma_lt_log.trans_le ( Real.le_log_iff_exp_le ( by positivity ) |>.2 <| by exact Real.exp_one_lt_d9.le.trans <| by norm_num; linarith [ Real.pi_gt_three ] )

/-
Defining the Dirichlet eta function as the alternating sum of reciprocals of powers.
-/
noncomputable def dirichletEta (s : ℂ) : ℂ := ∑' n : ℕ, (-1) ^ n / (n + 1) ^ s

/-
For s with real part > 1, the Dirichlet eta function satisfies the standard relation with the Riemann zeta function.
-/
lemma dirichletEta_eq_zeta_mul_of_one_lt_re (s : ℂ) (hs : 1 < s.re) :
    dirichletEta s = (1 - 2 ^ (1 - s)) * riemannZeta s := by
  -- We use the series expansion valid for re(s) > 1
  rw [dirichletEta, zeta_eq_tsum_one_div_nat_add_one_cpow hs]
  -- We want to show sum (-1)^n / (n+1)^s = (1 - 2/2^s) * sum 1/(n+1)^s
  -- = sum 1/(n+1)^s - 2 * sum 1/(2(k+1))^s
  -- This is a standard rearrangement.
  -- We can split the series into two separate sums, one over odd terms and one over even terms.
  have h_split : ∑' n : ℕ, (-1 : ℂ) ^ n / (n + 1) ^ s = (∑' n : ℕ, (1 : ℂ) / (2 * n + 1) ^ s) - (∑' n : ℕ, (1 : ℂ) / (2 * n + 2) ^ s) := by
    rw [ ← tsum_even_add_odd ];
    · norm_num [ neg_div, tsum_neg, sub_eq_add_neg ] ; ring;
    · have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n + 1 : ℂ) ^ s) := by
        have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n : ℂ) ^ s) := by
          exact?;
        exact_mod_cast h_summable.comp_injective Nat.succ_injective;
      convert h_summable.comp_injective ( show Function.Injective ( fun k : ℕ => 2 * k ) from fun a b h => by simpa using h ) using 2 ; norm_num;
    · have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n + 1 : ℂ) ^ s) := by
        have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n : ℂ) ^ s) := by
          exact?;
        exact_mod_cast h_summable.comp_injective Nat.succ_injective;
      convert h_summable.comp_injective ( show Function.Injective ( fun k : ℕ => 2 * k + 1 ) from fun a b h => by simpa using h ) |> Summable.neg using 2 ; norm_num;
      ring;
  -- We can rewrite the sum over even terms as a sum over all terms multiplied by $2^{-s}$.
  have h_even : ∑' n : ℕ, (1 : ℂ) / (2 * n + 2) ^ s = (2 : ℂ) ^ (-s) * ∑' n : ℕ, (1 : ℂ) / (n + 1) ^ s := by
    rw [ ← tsum_mul_left ] ; congr ; ext n ; rw [ show ( 2 * n + 2 : ℂ ) = 2 * ( n + 1 ) by ring, mul_comm ] ; rw [ Complex.cpow_def_of_ne_zero, Complex.cpow_def_of_ne_zero ] <;> norm_num ; ring;
    · rw [ Complex.cpow_def_of_ne_zero ( by norm_cast; linarith ) ] ; ring ; norm_num [ Complex.exp_neg, Complex.exp_add, Complex.exp_log ] ; ring;
      rw [ ← mul_inv, ← Complex.exp_add ] ; rw [ show ( 2 + n * 2 : ℂ ) = 2 * ( 1 + n ) by ring, Complex.log_mul ] <;> norm_num ; ring ; norm_cast ; aesop;
      exact ⟨ by linarith [ Real.pi_pos, Complex.neg_pi_lt_arg ( 1 + n : ℂ ) ], by linarith [ Real.pi_pos, Complex.arg_le_pi ( 1 + n : ℂ ) ] ⟩;
    · exact Nat.cast_add_one_ne_zero _;
  -- We can rewrite the sum over odd terms as a sum over all terms minus the sum over even terms.
  have h_odd : ∑' n : ℕ, (1 : ℂ) / (2 * n + 1) ^ s = (∑' n : ℕ, (1 : ℂ) / (n + 1) ^ s) - (∑' n : ℕ, (1 : ℂ) / (2 * n + 2) ^ s) := by
    rw [ eq_comm, ← tsum_even_add_odd ];
    · norm_num [ add_assoc, mul_add ];
    · have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n + 1) ^ s) := by
        have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n : ℂ) ^ s) := by
          exact?;
        exact_mod_cast h_summable.comp_injective Nat.succ_injective;
      exact h_summable.comp_injective fun a b h => by simpa using h;
    · have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n + 1) ^ s) := by
        have h_summable : Summable (fun n : ℕ => (1 : ℂ) / (n : ℂ) ^ s) := by
          exact?;
        exact_mod_cast h_summable.comp_injective Nat.succ_injective;
      exact h_summable.comp_injective fun a b h => by simpa using h;
  simp_all +decide [ Complex.cpow_sub ] ; ring;
  rw [ Complex.cpow_neg ]

/-
For x in (0, 1), the real part of (1 - 2^(1-x)) is negative.
-/
lemma one_sub_two_pow_neg_of_pos_of_lt_one (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    ((1 : ℂ) - (2 : ℂ) ^ ((1 : ℂ) - (x : ℂ))).re < 0 := by
      norm_num [ Complex.exp_re, Complex.exp_im, Complex.log_re, Complex.log_im, Complex.cpow_def ];
      exact mul_pos ( Real.log_pos ( by norm_num ) ) ( by linarith )

/-
Defining the Dirichlet eta function via its relation to the Riemann zeta function (analytic continuation).
-/
noncomputable def dirichletEtaAC (s : ℂ) : ℂ := (1 - 2 ^ (1 - s)) * riemannZeta s

/-
The alternating Dirichlet series converges to a positive limit for positive x.
-/
noncomputable def etaPartialSum (x : ℝ) (n : ℕ) : ℝ := ∑ k ∈ Finset.range n, (-1 : ℝ) ^ k / (k + 1) ^ x

lemma eta_series_converges_pos (x : ℝ) (hx : 0 < x) :
    ∃ L, Filter.Tendsto (etaPartialSum x) Filter.atTop (nhds L) ∧ 0 < L := by
      -- The series $\sum_{n=0}^\infty \frac{(-1)^n}{(n+1)^x}$ is an alternating series with terms that decrease in absolute value and approach zero.
      have h_alt_series : ∃ L, Filter.Tendsto (fun n : ℕ => ∑ i ∈ Finset.range n, (-1 : ℝ) ^ i / (i + 1) ^ x) Filter.atTop (nhds L) := by
        have h_alt_series : ∀ {a : ℕ → ℝ}, Antitone a → Filter.Tendsto a Filter.atTop (nhds 0) → ∃ L, Filter.Tendsto (fun n => ∑ i ∈ Finset.range n, (-1 : ℝ) ^ i * a i) Filter.atTop (nhds L) := by
          exact?;
        exact h_alt_series ( fun n m hnm => by simpa using inv_anti₀ ( by positivity ) <| Real.rpow_le_rpow ( by positivity ) ( by norm_cast; linarith ) <| by positivity ) <| tendsto_inv_atTop_zero.comp <| tendsto_rpow_atTop ( by positivity ) |> Filter.Tendsto.comp <| Filter.tendsto_atTop_add_const_right _ _ tendsto_natCast_atTop_atTop;
      obtain ⟨L, hL⟩ := h_alt_series
      have h_pos : 0 < L := by
        have h_pos : ∀ k : ℕ, ∑ i ∈ Finset.range (2 * k), (-1 : ℝ) ^ i / (i + 1) ^ x ≤ L := by
          apply_rules [ Antitone.alternating_series_le_tendsto ];
          exact fun i j hij => inv_anti₀ ( by positivity ) ( by gcongr );
        refine' lt_of_lt_of_le _ ( h_pos 1 ) ; norm_num [ Finset.sum_range_succ ];
        rw [ add_div', lt_div_iff₀ ] <;> linarith [ Real.rpow_lt_rpow_of_exponent_lt one_lt_two hx ]
      use L;
      aesop

/-
The completed zeta function is non-zero at s=0.
-/
lemma completedZeta_zero_ne_zero : completedZeta 0 ≠ 0 := by
  unfold completedZeta;
  -- The completed zeta function at s=0 is (1 - 2)/2 = -1/2, which is non-zero. We can use the fact that the completed zeta function is equal to (γ - log(4π))/2 at s=0.
  have h_complete_zero : completedRiemannZeta 0 = (Real.eulerMascheroniConstant - Real.log (4 * Real.pi)) / 2 := by
    convert completedRiemannZeta_one using 1;
    · rw [ show ( 0 : ℂ ) = 1 - 1 by norm_num, completedRiemannZeta_one_sub ];
    · norm_num [ Complex.ofReal_log ( show 0 ≤ 4 * Real.pi by positivity ) ];
  rw [ h_complete_zero ] ; norm_num [ Complex.ext_iff ] ; linarith [ gamma_lt_log_four_pi ]

/-
The imaginary part of (1 - 2^(1-x)) is zero for real x.
-/
lemma one_sub_two_pow_im_eq_zero (x : ℝ) : ((1 : ℂ) - (2 : ℂ) ^ ((1 : ℂ) - (x : ℂ))).im = 0 := by
  norm_num [ Complex.exp_re, Complex.exp_im, Complex.log_re, Complex.log_im, Complex.cpow_def ]
