/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1b5e1e0a-2cd6-4b9e-b550-39236f069d6d

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Matrix
open Finset Matrix SimpleGraph Real

abbrev laplacianMatrix {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) : Matrix V V ℝ :=
  G.lapMatrix ℝ

def inducedLaplacian {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) : Matrix V V ℝ :=
  let G' := G.induce ↑S
  Matrix.of (fun i j =>
    if h : i ∈ S ∧ j ∈ S then (G'.lapMatrix ℝ) ⟨i, h.1⟩ ⟨j, h.2⟩ else 0)

def IsEpsilonLight {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (ε : ℝ) : Prop :=
  (ε • laplacianMatrix G - inducedLaplacian G S).PosSemidef

def internalEdges {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) : ℕ :=
  (G.edgeFinset.filter (fun e => ∀ v ∈ e, v ∈ S)).card

def boundaryEdges {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) : ℕ :=
  (G.edgeFinset.filter (fun e => ∃ v ∈ e, v ∈ S ∧ ∃ w ∈ e, w ∉ S)).card

def indicatorVec {V : Type*} [Fintype V] [DecidableEq V] (S : Finset V) : V → ℝ :=
  fun v => if v ∈ S then 1 else 0

theorem induced_laplacian_quad_form {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (x : V → ℝ) :
    dotProduct (inducedLaplacian G S *ᵥ x) x = ∑ e ∈ (G.induce ↑S).edgeFinset, (x (Quot.out e).1 - x (Quot.out e).2) ^ 2 := by
  unfold inducedLaplacian; simp +decide [ Matrix.vecMul, dotProduct ] ; ring;
  have h_laplacian_def : ∀ (G : SimpleGraph S) (x : S → ℝ), (∑ i, ((G.lapMatrix ℝ).mulVec x) i * x i) = (∑ e ∈ G.edgeFinset, (x e.out.1 - x e.out.2)^2) := by
    intro G x;
    have h_laplacian_def : (∑ i, ((G.lapMatrix ℝ).mulVec x) i * x i) = (∑ i, (∑ j ∈ G.neighborFinset i, (x i - x j) * x i)) := by
      simp +decide [ SimpleGraph.lapMatrix, Matrix.mulVec, dotProduct ];
      simp +decide [ SimpleGraph.degMatrix, Finset.sum_ite, Finset.filter_ne, Finset.filter_and, sub_mul, mul_sub ];
      simp +decide [ Matrix.diagonal, Finset.sum_ite, Finset.filter_eq, Finset.filter_ne, mul_assoc, Finset.sum_mul ];
      rcongr i ; aesop;
    have h_laplacian_def : (∑ i, (∑ j ∈ G.neighborFinset i, (x i - x j) * x i)) = (∑ e ∈ G.edgeFinset, ((x (e.out.1) - x (e.out.2)) * x (e.out.1) + (x (e.out.2) - x (e.out.1)) * x (e.out.2))) := by
      have h_laplacian_def : ∀ (i : { x : V // x ∈ S }), (∑ j ∈ G.neighborFinset i, (x i - x j) * x i) = (∑ e ∈ G.edgeFinset, if e.out.1 = i then (x i - x e.out.2) * x i else if e.out.2 = i then (x i - x e.out.1) * x i else 0) := by
        intro i
        have h_laplacian_def : (∑ j ∈ G.neighborFinset i, (x i - x j) * x i) = (∑ e ∈ G.edgeFinset, if e.out.1 = i then (x i - x e.out.2) * x i else if e.out.2 = i then (x i - x e.out.1) * x i else 0) := by
          have h_neighbor : G.neighborFinset i = Finset.image (fun e => if e.out.1 = i then e.out.2 else e.out.1) (Finset.filter (fun e => e.out.1 = i ∨ e.out.2 = i) G.edgeFinset) := by
            ext j; simp [SimpleGraph.neighborFinset];
            constructor;
            · have := Quot.out_eq ( s(i, j) );
              rw [ Sym2.eq_iff ] at this ; aesop;
            · rintro ⟨ a, ⟨ ha₁, ha₂ ⟩, rfl ⟩;
              split_ifs <;> simp_all +decide [ SimpleGraph.adj_comm ];
              · convert ha₁ using 1;
                rw [ ← ‹ ( Quot.out a ).1 = i › ];
                rw [ ← SimpleGraph.mem_edgeSet ];
                simp +decide [ Sym2.eq_swap ];
              · rw [ ← ha₂, SimpleGraph.adj_comm ];
                convert ha₁ using 1;
                rw [ ← SimpleGraph.mem_edgeSet ];
                simp +decide [ Sym2.eq_swap ]
          rw [ h_neighbor, Finset.sum_image ];
          · rw [ Finset.sum_filter ] ; congr ; ext ; aesop;
          · intro e he e' he' h_eq; simp_all +decide [ Sym2.eq_iff ] ;
            -- Since $e$ and $e'$ are both edges in $G$, and their outputs are equal, they must be the same edge.
            have h_eq_edges : e = e' := by
              have h_eq_out : (Quot.out e).1 = (Quot.out e').1 ∧ (Quot.out e).2 = (Quot.out e').2 ∨ (Quot.out e).1 = (Quot.out e').2 ∧ (Quot.out e).2 = (Quot.out e').1 := by
                grind
              -- Since the outputs of e and e' are equal, we can conclude that e and e' are the same edge.
              have h_eq_edges : e = Sym2.mk ((Quot.out e).1, (Quot.out e).2) ∧ e' = Sym2.mk ((Quot.out e').1, (Quot.out e').2) := by
                exact ⟨ by exact Eq.symm ( Quot.out_eq e ), by exact Eq.symm ( Quot.out_eq e' ) ⟩;
              rw [ h_eq_edges.1, h_eq_edges.2 ] ; rcases h_eq_out with h | h <;> simp +decide [ h ] ;
              exact h_eq_edges.2.symm ▸ by simp +decide [ Sym2.eq_swap ] ;
            exact h_eq_edges;
        exact h_laplacian_def;
      simp +decide only [h_laplacian_def, sum_add_distrib];
      rw [ Finset.sum_comm ];
      rw [ ← Finset.sum_add_distrib ] ; refine' Finset.sum_congr rfl fun e he => _ ; simp +decide [ Finset.sum_ite, Finset.filter_eq', Finset.filter_ne' ] ; ring;
      -- Since there's only one element in S.attach that equals (Quot.out e).1, the sum simplifies to just that term.
      have h_sum : ∑ x_1 ∈ S.attach with (Quot.out e).1 = x_1, (-(x x_1 * x (Quot.out e).2) + x x_1 ^ 2) = -(x (Quot.out e).1 * x (Quot.out e).2) + x (Quot.out e).1 ^ 2 := by
        rw [ Finset.sum_eq_single ( Quot.out e |>.1 ) ] <;> simp +contextual [ eq_comm ];
      split_ifs <;> simp_all +decide [ sq, mul_comm ] ; ring;
      ring;
    exact Eq.trans ‹_› ( Eq.trans h_laplacian_def ( Finset.sum_congr rfl fun _ _ => by ring ) );
  convert h_laplacian_def ( SimpleGraph.induce S G ) ( fun i => x i ) using 1;
  · rw [ ← Finset.sum_subset ( Finset.subset_univ S ) ];
    · refine' Finset.sum_bij ( fun i hi => ⟨ i, hi ⟩ ) _ _ _ _ <;> simp +decide [ Matrix.mulVec, dotProduct ];
      intro a ha; rw [ ← Finset.sum_subset ( Finset.subset_univ ( Finset.image ( fun i : { x // x ∈ S } => i.val ) Finset.univ ) ) ] ; simp +decide [ Finset.sum_image, ha ] ;
      · rw [ ← Finset.sum_attach ] ; aesop;
      · aesop;
    · simp +contextual [ Matrix.mulVec, dotProduct ];
  · exact Finset.sum_congr rfl fun _ _ => by ring;

theorem laplacian_quad_form {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) (x : V → ℝ) :
    dotProduct (laplacianMatrix G *ᵥ x) x = ∑ e ∈ G.edgeFinset, (x (Quot.out e).1 - x (Quot.out e).2) ^ 2 := by
  simp [laplacianMatrix, dotProduct, mulVec, Finset.sum_add_distrib]
  -- We need to expand the laplacian matrix multiplication
  -- (L x)_i = deg(i) x_i - sum_{j ~ i} x_j
  -- x^T L x = sum_i x_i (deg(i) x_i - sum_{j ~ i} x_j)
  --         = sum_i deg(i) x_i^2 - sum_i sum_{j ~ i} x_i x_j
  --         = sum_i sum_{j ~ i} x_i^2 - sum_{i, j, i ~ j} x_i x_j
  --         = sum_{i ~ j} (x_i^2 - x_i x_j)
  --         = sum_{{i, j} in E} (x_i^2 - 2 x_i x_j + x_j^2)
  --         = sum_{{i, j} in E} (x_i - x_j)^2
  -- By definition of the Laplacian matrix, we can expand the quadratic form.
  have h_expand : ∑ i, (∑ j, (G.lapMatrix ℝ i j) * x j) * x i = ∑ i, (∑ j ∈ G.neighborFinset i, (x i - x j)) * x i := by
    simp +decide [ SimpleGraph.lapMatrix, Finset.sum_sub_distrib, sub_mul ];
    simp +decide [ SimpleGraph.degMatrix, Finset.sum_ite, SimpleGraph.neighborFinset_eq_filter ];
    simp +decide [ Matrix.diagonal ];
  -- By definition of the Laplacian matrix, we can rewrite the sum as a sum over edges.
  have h_sum_edges : ∑ i, (∑ j ∈ G.neighborFinset i, (x i - x j)) * x i = ∑ e ∈ G.edgeFinset, (x (e.out.1) - x (e.out.2)) ^ 2 := by
    have h_sum_edges : ∑ i, (∑ j ∈ G.neighborFinset i, (x i - x j)) * x i = ∑ i, ∑ j ∈ G.neighborFinset i, (x i - x j) * x i := by
      simp +decide only [Finset.sum_mul _ _ _]
    have h_sum_edges : ∑ i, ∑ j ∈ G.neighborFinset i, (x i - x j) * x i = ∑ e ∈ G.edgeFinset, ((x (e.out.1) - x (e.out.2)) * x (e.out.1) + (x (e.out.2) - x (e.out.1)) * x (e.out.2)) := by
      have h_sum_edges : ∀ i, ∑ j ∈ G.neighborFinset i, (x i - x j) * x i = ∑ e ∈ G.edgeFinset, (if e.out.1 = i then (x i - x e.out.2) * x i else if e.out.2 = i then (x i - x e.out.1) * x i else 0) := by
        intro i
        have h_sum_edges : ∑ j ∈ G.neighborFinset i, (x i - x j) * x i = ∑ e ∈ G.edgeFinset, (if e.out.1 = i then (x i - x e.out.2) * x i else if e.out.2 = i then (x i - x e.out.1) * x i else 0) := by
          have h_neighbor : G.neighborFinset i = Finset.image (fun e => if e.out.1 = i then e.out.2 else e.out.1) (Finset.filter (fun e => e.out.1 = i ∨ e.out.2 = i) G.edgeFinset) := by
            ext j; simp [SimpleGraph.neighborFinset];
            constructor;
            · intro hij
              use Sym2.mk (i, j);
              have := Quot.out_eq ( s(i, j) );
              rw [ Sym2.eq_iff ] at this ; aesop;
            · rintro ⟨ a, ⟨ ha₁, ha₂ ⟩, rfl ⟩;
              split_ifs <;> simp_all +decide [ SimpleGraph.adj_comm ];
              · -- Since $a$ is in $G$'s edge set, by definition of $G$'s edge set, $a$ is an edge between two vertices. The quotient out of $a$ gives me the two vertices that form the edge. Since the first element is $i$, the second element must be the other vertex connected to $i$ by this edge. Therefore, $G.Adj i (Quot.out a).2$ should hold because $a$ is an edge in $G$.
                have h_adj : G.Adj (Quot.out a).1 (Quot.out a).2 := by
                  convert ha₁ using 1;
                  rw [ ← SimpleGraph.mem_edgeSet ];
                  simp +decide [ Sym2.eq_swap ];
                grind;
              · rw [ ← ha₂, SimpleGraph.adj_comm ];
                convert ha₁ using 1;
                rw [ ← SimpleGraph.mem_edgeSet ];
                simp +decide [ Sym2.eq_swap ]
          rw [ h_neighbor, Finset.sum_image ];
          · rw [ Finset.sum_filter ] ; congr ; ext ; aesop;
          · intro e he e' he' h_eq;
            have h_eq_out : (Quot.out e).1 = (Quot.out e').1 ∧ (Quot.out e).2 = (Quot.out e').2 ∨ (Quot.out e).1 = (Quot.out e').2 ∧ (Quot.out e).2 = (Quot.out e').1 := by
              grind;
            -- Since the edge is unordered, if either the first elements are equal and the second elements are equal, or the first element of one is equal to the second element of the other and vice versa, then the edges must be the same.
            have h_eq_edges : ∀ (a b c d : V), a = c ∧ b = d ∨ a = d ∧ b = c → Sym2.mk (a, b) = Sym2.mk (c, d) := by
              rintro a b c d ( ⟨ rfl, rfl ⟩ | ⟨ rfl, rfl ⟩ ) <;> simp +decide [ Sym2.eq_swap ];
            convert h_eq_edges _ _ _ _ h_eq_out using 1;
            · exact Eq.symm ( Quot.out_eq e );
            · exact Eq.symm ( Quot.out_eq e' );
        exact h_sum_edges
      rw [ Finset.sum_congr rfl fun i hi => h_sum_edges i, Finset.sum_comm ];
      refine' Finset.sum_congr rfl fun e he => _;
      simp +decide [ Finset.sum_ite, Finset.filter_eq, Finset.filter_ne ];
      exact fun h => Or.inl <| by rw [ h, sub_self ] ;
    exact Eq.trans ‹_› ( h_sum_edges.trans ( Finset.sum_congr rfl fun _ _ => by ring ) );
  rw [h_expand, h_sum_edges]
