/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f898e4f5-4bad-4d7a-9a31-aeb52cd39866

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized the Brockian-style finite dynamics kernel engine, including the transition-count kernel definition and the row-sum, column-sum, and total-sum theorems.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

universe u

open scoped BigOperators

/-
Transition predicate for a labeled step system.
-/
def Transition {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) (i j : Fin k) (s : S) : Prop :=
  dom s ∧ dom (step s) ∧ label s = i ∧ label (step s) = j

/-
The transition-count kernel K(i,j).
-/
def Kernel {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) (i j : Fin k) : ℕ :=
  ((Finset.univ : Finset S).filter (fun s => Transition (step := step) (label := label) (dom := dom) i j s)).card

/-
Admissible-start predicate.
-/
def Dom2 {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (dom : S → Prop) (s : S) : Prop :=
  dom s ∧ dom (step s)

/-
Row predicate.
-/
def RowPred {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) (i : Fin k) (s : S) : Prop :=
  Dom2 (k := k) (step := step) (dom := dom) s ∧ label s = i

/-
Column predicate.
-/
def ColPred {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) (j : Fin k) (s : S) : Prop :=
  Dom2 (k := k) (step := step) (dom := dom) s ∧ label (step s) = j

/-
Total predicate.
-/
def TotPred {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (dom : S → Prop) (s : S) : Prop :=
  Dom2 (k := k) (step := step) (dom := dom) s

/-
Decidability for RowPred.
-/
instance {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) [DecidablePred dom] (i : Fin k) : DecidablePred (RowPred (step := step) (label := label) (dom := dom) i) := by
  intro s
  dsimp [RowPred]
  infer_instance

/-
Decidability for ColPred.
-/
instance {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) [DecidablePred dom] (j : Fin k) : DecidablePred (ColPred (step := step) (label := label) (dom := dom) j) := by
  intro s
  dsimp [ColPred]
  infer_instance

/-
Unfolding lemma for Kernel.
-/
lemma Kernel_def {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) [DecidablePred dom] (i j : Fin k) :
    Kernel (step := step) (label := label) (dom := dom) i j =
      ((Finset.univ : Finset S).filter (fun s => Transition (step := step) (label := label) (dom := dom) i j s)).card := by
  rfl

/-
Row-sum theorem.
-/
theorem rowSum {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) [DecidablePred dom]
    (i : Fin k) :
    (∑ j : Fin k, Kernel (step := step) (label := label) (dom := dom) i j)
      =
    ((Finset.univ : Finset S).filter (fun s => RowPred (step := step) (label := label) (dom := dom) i s)).card := by
      unfold Kernel RowPred;
      rw [ ← Finset.card_biUnion ];
      · congr with s ; simp +decide [ Transition, Dom2 ];
        tauto;
      · exact fun i _ j _ hij => Finset.disjoint_left.mpr fun s => by unfold Transition; aesop;

/-
Column-sum theorem.
-/
theorem colSum {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) [DecidablePred dom]
    (j : Fin k) :
    (∑ i : Fin k, Kernel (step := step) (label := label) (dom := dom) i j)
      =
    ((Finset.univ : Finset S).filter (fun s => ColPred (step := step) (label := label) (dom := dom) j s)).card := by
      unfold Kernel ColPred;
      rw [ ← Finset.card_biUnion ];
      · congr with s ; simp +decide [ Transition, Dom2 ] ; aesop;
      · intro i _ j _ hij; simp_all +decide [ Finset.disjoint_left, Transition ] ;

/-
Total-sum theorem.
-/
theorem totalSum {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) [DecidablePred dom] :
    (∑ i : Fin k, ∑ j : Fin k, Kernel (step := step) (label := label) (dom := dom) i j)
      =
    ((Finset.univ : Finset S).filter (fun s => TotPred (k := k) (step := step) (dom := dom) s)).card := by
      convert Finset.sum_congr rfl fun i _ => rowSum step label dom i using 2;
      rw [ ← Finset.card_biUnion ];
      · congr with s ; simp +decide [ RowPred, TotPred ];
      · intro i _ j _ hij; simp_all +decide [ Finset.disjoint_left, RowPred ] ;

/-
Total-sum theorem (renamed to totalSum_eq).
-/
theorem totalSum_eq {S : Type u} [Fintype S] [DecidableEq S] {k : ℕ} (step : S → S) (label : S → Fin k) (dom : S → Prop) [DecidablePred dom] :
    (∑ i : Fin k, ∑ j : Fin k, Kernel (step := step) (label := label) (dom := dom) i j)
      =
    ((Finset.univ : Finset S).filter (fun s => TotPred (k := k) (step := step) (dom := dom) s)).card := by
      convert totalSum step label dom using 1
