/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 81c97b9e-4f0b-45bd-a0f4-aeb5fdb9a26d
-/

/-
This module formalizes geometric arithmetic on the natural numbers.
It establishes the canonical ray partition of ℕ modulo a prime p, proves its preservation under additive automorphisms,
defines the dihedral group action on ZMod p, demonstrates the appearance of the golden ratio in the spectral theory for p=5,
and proves the universal p-2 law for configuration counting.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-- A ray modulo p is the set of natural numbers congruent to i modulo p -/
def Ray (p : ℕ) (i : ZMod p) : Set ℕ :=
  {n : ℕ | (n : ZMod p) = i}

/-- The ray partition of ℕ for a given prime p -/
def RayPartition (p : ℕ) : Set (Set ℕ) :=
  {S | ∃ i : ZMod p, S = Ray p i}

theorem mem_ray_iff (p : ℕ) (i : ZMod p) (n : ℕ) :
    n ∈ Ray p i ↔ (n : ZMod p) = i := Iff.rfl

theorem ray_nonempty (p : ℕ) [NeZero p] (i : ZMod p) :
    (Ray p i).Nonempty := by
      -- By definition of Ray, there exists some natural number n such that n ≡ i (mod p).
      use i.val;
      -- By definition of Ray, we need to show that i.val ≡ i (mod p).
      simp [Ray]

/-- Covering: every natural number belongs to some ray -/
theorem ray_partition_covers (p : ℕ) [hp : Fact p.Prime] :
    ⋃ i : ZMod p, Ray p i = Set.univ := by
  ext n
  simp only [Set.mem_iUnion, Set.mem_univ, iff_true]
  use (n : ZMod p)
  rfl

/-- Disjointness: distinct rays are disjoint -/
theorem rays_disjoint (p : ℕ) [hp : Fact p.Prime] {i j : ZMod p} (hij : i ≠ j) :
    Ray p i ∩ Ray p j = ∅ := by
      -- If there exists an element $n$ in both $Ray p i$ and $Ray p j$, then $n \equiv i \pmod{p}$ and $n \equiv j \pmod{p}$, which implies $i \equiv j \pmod{p}$, contradicting $i \neq j$.
      ext n
      simp [Ray];
      grind

/-- Main partition theorem: each n belongs to exactly one ray -/
theorem ray_partition_unique (p : ℕ) [hp : Fact p.Prime] (n : ℕ) :
    ∃! i : ZMod p, n ∈ Ray p i := by
  use (n : ZMod p)
  constructor
  · rfl
  · intro j hn
    exact hn.symm

/-- An additive automorphism of ℕ -/
structure AdditiveAut where
  toFun : ℕ → ℕ
  bij : Function.Bijective toFun
  zero_map : toFun 0 = 0
  add_map : ∀ n m, toFun (n + m) = toFun n + toFun m

instance : CoeFun AdditiveAut (fun _ => ℕ → ℕ) where
  coe := AdditiveAut.toFun

def AdditiveAut.id : AdditiveAut where
  toFun := _root_.id
  bij := Function.bijective_id
  zero_map := rfl
  add_map := fun _ _ => rfl

/-- The only additive automorphism of ℕ is the identity -/
theorem additive_aut_is_id (σ : AdditiveAut) : σ.toFun = id := by
  -- By definition of automorphism, we know that σ(n) = n for all n in ℕ.
  have h_sigma_n : ∀ n : ℕ, σ.toFun n = n := by
    -- Since σ is additive, we have σ(n) = σ(1 + 1 + ... + 1) = σ(1) + σ(1) + ... + σ(1) = n * σ(1).
    have h_add : ∀ n : ℕ, σ.toFun n = n * σ.toFun 1 := by
      -- We proceed by induction on $n$.
      intro n
      induction' n with n ih;
      · simpa using σ.zero_map;
      · rw [ add_mul, one_mul, ← ih, σ.add_map ];
    -- Since σ is bijective, σ(1) must be 1.
    have h_sigma_one : σ.toFun 1 = 1 := by
      obtain ⟨ n, hn ⟩ := σ.bij.2 1 ; specialize h_add n ; rcases n with ( _ | _ | n ) <;> norm_num at * ; nlinarith;
      · exact hn;
      · grind;
    exact fun n => by simpa [ h_sigma_one ] using h_add n;
  exact funext h_sigma_n

/-- Weak canonicity: the ray partition is preserved by all automorphisms -/
theorem ray_partition_canonical (p : ℕ) [hp : Fact p.Prime] (σ : AdditiveAut) :
    ∀ i : ZMod p, σ '' (Ray p i) = Ray p i := by
  intro i
  rw [additive_aut_is_id σ]
  simp [Set.image_id]

/-- The canonical quotient map from ℕ to ZMod p -/
def quotientMap (p : ℕ) : ℕ → ZMod p := fun n => (n : ZMod p)

theorem quotientMap_additive (p : ℕ) (n m : ℕ) :
    quotientMap p (n + m) = quotientMap p n + quotientMap p m := by
      -- By definition of quotientMap, we have quotientMap p (n + m) = (n + m : ZMod p).
      simp [quotientMap]

/-- Embed ZMod p into ℂ as vertices of a regular p-gon on the unit circle -/
noncomputable def geometricEmbedding (p : ℕ) : ZMod p → ℂ :=
  fun i => Complex.exp (2 * Real.pi * Complex.I * i.val / p)

#check Complex.norm_exp
#check (norm : ℂ → ℝ)

theorem geometricEmbedding_on_unit_circle (p : ℕ) [NeZero p] (i : ZMod p) :
    ‖geometricEmbedding p i‖ = 1 := by
      -- The norm of the exponential of an imaginary number is 1.
      have h_norm_exp : ∀ θ : ℝ, ‖Complex.exp (θ * Complex.I)‖ = 1 := by
        -- The norm of the exponential of an imaginary number is 1, since $|e^{i\theta}| = 1$ for any real $\theta$.
        intros θ
        simp [Complex.norm_exp];
      convert h_norm_exp ( 2 * Real.pi * i.val / p ) using 2 ; push_cast [ geometricEmbedding ] ; ring

/-- The Euclidean distance induced by the embedding -/
noncomputable def euclideanDist (p : ℕ) (i j : ZMod p) : ℝ :=
  ‖geometricEmbedding p i - geometricEmbedding p j‖

theorem euclideanDist_symm (p : ℕ) (i j : ZMod p) :
    euclideanDist p i j = euclideanDist p j i := by
  simp [euclideanDist]
  rw [←norm_neg]
  ring_nf

theorem euclideanDist_triangle (p : ℕ) (i j k : ZMod p) :
    euclideanDist p i k ≤ euclideanDist p i j + euclideanDist p j k := by
  simp [euclideanDist]
  calc ‖geometricEmbedding p i - geometricEmbedding p k‖
      = ‖(geometricEmbedding p i - geometricEmbedding p j) + (geometricEmbedding p j - geometricEmbedding p k)‖ := by ring_nf
    _ ≤ ‖geometricEmbedding p i - geometricEmbedding p j‖ + ‖geometricEmbedding p j - geometricEmbedding p k‖ := 
        norm_add_le _ _

/-- Elements of the dihedral group D_p -/
inductive DihedralElem (p : ℕ)
  | rot : ZMod p → DihedralElem p
  | ref : ZMod p → DihedralElem p

def DihedralElem.mul {p : ℕ} : DihedralElem p → DihedralElem p → DihedralElem p
  | DihedralElem.rot k, DihedralElem.rot j => DihedralElem.rot (k + j)
  | DihedralElem.rot k, DihedralElem.ref j => DihedralElem.ref (j + k)
  | DihedralElem.ref k, DihedralElem.rot j => DihedralElem.ref (k - j)
  | DihedralElem.ref k, DihedralElem.ref j => DihedralElem.rot (k - j)

#check DihedralGroup

def DihedralElem.one {p : ℕ} : DihedralElem p := DihedralElem.rot 0

def DihedralElem.inv {p : ℕ} : DihedralElem p → DihedralElem p
  | DihedralElem.rot k => DihedralElem.rot (-k)
  | DihedralElem.ref k => DihedralElem.ref k

instance (p : ℕ) [Fact p.Prime] : Group (DihedralElem p) where
  mul := DihedralElem.mul
  one := DihedralElem.one
  inv := DihedralElem.inv
  mul_assoc := by
    rintro ( a | a ) ( b | b ) ( c | c );
    all_goals erw [ show DihedralElem.mul = fun x y => match x, y with | DihedralElem.rot k, DihedralElem.rot j => DihedralElem.rot ( k + j ) | DihedralElem.rot k, DihedralElem.ref j => DihedralElem.ref ( j + k ) | DihedralElem.ref k, DihedralElem.rot j => DihedralElem.ref ( k - j ) | DihedralElem.ref k, DihedralElem.ref j => DihedralElem.rot ( k - j ) from ?_ ] ; ring!;
    -- By definition of DihedralElem.mul, we can split the multiplication into cases based on the types of the elements.
    have h_mul_def : ∀ (x y : DihedralElem p), DihedralElem.mul x y = match x, y with
      | DihedralElem.rot k, DihedralElem.rot j => DihedralElem.rot (k + j)
      | DihedralElem.rot k, DihedralElem.ref j => DihedralElem.ref (j + k)
      | DihedralElem.ref k, DihedralElem.rot j => DihedralElem.ref (k - j)
      | DihedralElem.ref k, DihedralElem.ref j => DihedralElem.rot (k - j) := by
        bound;
    -- By definition of DihedralElem.mul, we can split the multiplication into cases based on the types of the elements and show that it is associative in each case.
    have h_assoc_cases : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.rot a) (DihedralElem.rot b)) (DihedralElem.rot c) = DihedralElem.mul (DihedralElem.rot a) (DihedralElem.mul (DihedralElem.rot b) (DihedralElem.rot c)) := by
      grind;
    exact h_assoc_cases a b c
    all_goals generalize_proofs at *;
    any_goals rfl;
    -- By definition of multiplication in the dihedral group, we can expand both sides of the equation.
    have h_expand : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.rot a) (DihedralElem.rot b)) (DihedralElem.ref c) = DihedralElem.mul (DihedralElem.rot a) (DihedralElem.mul (DihedralElem.rot b) (DihedralElem.ref c)) := by
      -- By definition of multiplication in the dihedral group, we can expand both sides of the equation and show they are equal.
      intros a b c
      simp [DihedralElem.mul];
      ring;
    exact h_expand a b c;
    have h_expand : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.rot a) (DihedralElem.ref b)) (DihedralElem.rot c) = DihedralElem.mul (DihedralElem.rot a) (DihedralElem.mul (DihedralElem.ref b) (DihedralElem.rot c)) := by
      intros a b c
      simp [DihedralElem.mul];
      grind
    exact h_expand a b c
    all_goals generalize_proofs at *;
    · have h_expand : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.rot a) (DihedralElem.ref b)) (DihedralElem.ref c) = DihedralElem.mul (DihedralElem.rot a) (DihedralElem.mul (DihedralElem.ref b) (DihedralElem.ref c)) := by
        intros a b c
        simp [DihedralElem.mul];
        ring
      exact h_expand a b c;
    · have h_expand : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.ref a) (DihedralElem.rot b)) (DihedralElem.rot c) = DihedralElem.mul (DihedralElem.ref a) (DihedralElem.mul (DihedralElem.rot b) (DihedralElem.rot c)) := by
        intros a b c
        simp [DihedralElem.mul];
        ring
      exact h_expand a b c;
    · have h_expand : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.ref a) (DihedralElem.rot b)) (DihedralElem.ref c) = DihedralElem.mul (DihedralElem.ref a) (DihedralElem.mul (DihedralElem.rot b) (DihedralElem.ref c)) := by
        intros a b c
        simp [DihedralElem.mul];
        grind
      exact h_expand a b c;
    · have h_expand : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.ref a) (DihedralElem.ref b)) (DihedralElem.rot c) = DihedralElem.mul (DihedralElem.ref a) (DihedralElem.mul (DihedralElem.ref b) (DihedralElem.rot c)) := by
        intros a b c; exact (by
        -- By definition of multiplication in the dihedral group, we can expand both sides of the equation and show they are equal.
        simp [DihedralElem.mul];
        ring)
      exact h_expand a b c;
    · have h_expand : ∀ (a b c : ZMod p), DihedralElem.mul (DihedralElem.mul (DihedralElem.ref a) (DihedralElem.ref b)) (DihedralElem.ref c) = DihedralElem.mul (DihedralElem.ref a) (DihedralElem.mul (DihedralElem.ref b) (DihedralElem.ref c)) := by
        -- By definition of DihedralElem.mul, we can expand both sides of the equation and show they are equal.
        simp [DihedralElem.mul];
        grind
      exact h_expand a b c
  one_mul := by
    -- By definition of multiplication in the dihedral group, we can split into cases based on whether `a` is a rotation or a reflection.
    intro a
    cases' a with k j;
    · -- In the dihedral group, the identity element is the rotation by 0 degrees, which is the same as the identity rotation.
      have h_id : DihedralElem.mul (DihedralElem.rot 0) (DihedralElem.rot k) = DihedralElem.rot k := by
        -- By definition of multiplication in the dihedral group, multiplying a rotation by the identity rotation (which is DihedralElem.rot 0) results in the same rotation.
        simp [DihedralElem.mul];
      exact h_id;
    · -- By definition of multiplication in the dihedral group, we can split into cases based on whether `a` is a rotation or a reflection. For the reflection case, we have:
      have h_ref : DihedralElem.mul (DihedralElem.rot 0) (DihedralElem.ref j) = DihedralElem.ref (j + 0) := by
        rfl;
      aesop
  mul_one := by
    -- Show that the defined identity element is indeed the identity.
    intros a
    cases a;
    · -- By definition of DihedralElem.mul, when both elements are rotations, their product is the sum of their exponents.
      have h_rot_mul : ∀ (k j : ZMod p), DihedralElem.mul (DihedralElem.rot k) (DihedralElem.rot j) = DihedralElem.rot (k + j) := by
        exact?;
      convert h_rot_mul _ _;
      norm_num;
    · -- By definition of multiplication in the dihedral group, we have:
      have h_mul : ∀ k j : ZMod p, DihedralElem.mul (DihedralElem.ref k) (DihedralElem.rot j) = DihedralElem.ref (k - j) := by
        exact?;
      -- Apply the hypothesis h_mul with k = a and j = 0.
      specialize h_mul ‹_› 0;
      aesop
  inv_mul_cancel := by
    -- Let's consider the two cases for elements in DihedralElem p: rotations and reflections.
    intro a
    cases' a with k hk j hj;
    · -- By definition of multiplication in the dihedral group, we have:
      have h_mul : (DihedralElem.rot (-k)).mul (DihedralElem.rot k) = DihedralElem.rot ((-k) + k) := by
        rfl;
      aesop;
    · -- By definition of multiplication in the dihedral group, we have:
      have h_mul : DihedralElem.mul (DihedralElem.ref hk) (DihedralElem.ref hk) = DihedralElem.rot (hk - hk) := by
        rfl;
      exact h_mul.trans ( by cases p <;> aesop )

instance (p : ℕ) [Fact p.Prime] : Group (DihedralElem p) where
  mul := DihedralElem.mul
  one := DihedralElem.one
  inv := DihedralElem.inv
  mul_assoc := by
    grind
  one_mul := by
    aesop
  mul_one := by
    aesop
  inv_mul_cancel := by
    -- For rotations, the inverse is the rotation by the negative of the angle, so multiplying them gives the identity rotation.
    intro a
    cases a <;> simp [DihedralElem.inv];
    · exact congr_arg DihedralElem.rot ( by simp +decide );
    · exact?

lemma DihedralElem.mul_assoc {p : ℕ} (a b c : DihedralElem p) :
    DihedralElem.mul (DihedralElem.mul a b) c = DihedralElem.mul a (DihedralElem.mul b c) := by
  cases a <;> cases b <;> cases c <;> simp [DihedralElem.mul] <;> ring

/-- Action of D_p on ZMod p -/
def dihedralAction (p : ℕ) [Fact p.Prime] : DihedralElem p → ZMod p → ZMod p
  | DihedralElem.rot k, i => i + k
  | DihedralElem.ref k, i => k - i

instance (p : ℕ) [Fact p.Prime] : Group (DihedralElem p) where
  mul := DihedralElem.mul
  one := DihedralElem.one
  inv := DihedralElem.inv
  mul_assoc := DihedralElem.mul_assoc
  one_mul := by
    -- By definition of the group operation, multiplying by 1 (which is the rotation by 0) leaves any element unchanged.
    intros a
    cases a <;> simp [DihedralElem.mul]
  mul_one := by
    aesop
  inv_mul_cancel := by
    -- By definition of the inverse, we know that for any element a in D_p, a.inv * a = 1.
    apply inv_mul_cancel

lemma dihedral_action_one_smul (p : ℕ) [Fact p.Prime] (i : ZMod p) :
  dihedralAction p DihedralElem.one i = i := by
  simp [dihedralAction, DihedralElem.one]

lemma dihedral_action_mul_smul (p : ℕ) [Fact p.Prime] (g h : DihedralElem p) (i : ZMod p) :
  dihedralAction p (DihedralElem.mul g h) i = dihedralAction p g (dihedralAction p h i) := by
  cases g <;> cases h <;> simp [dihedralAction, DihedralElem.mul] <;> ring

instance (p : ℕ) [Fact p.Prime] : MulAction (DihedralElem p) (ZMod p) where
  smul := dihedralAction p
  one_smul := dihedral_action_one_smul p
  mul_smul := dihedral_action_mul_smul p

theorem dihedral_action_faithful (p : ℕ) [Fact p.Prime] (hp : p ≠ 2) :
    Function.Injective (fun (g : DihedralElem p) (i : ZMod p) => g • i) := by
      intro g h hgh;
      -- By definition of dihedral action, if $g • i = i$ for all $i$, then $g$ must be the identity element.
      have h_id : ∀ g : DihedralElem p, (∀ i : ZMod p, g • i = i) → g = DihedralElem.one := by
        intro g hg
        by_cases hg_rot : ∃ k : ZMod p, g = DihedralElem.rot k;
        · -- If $g$ is a rotation, then there exists some $k$ such that $g = DihedralElem.rot k$. The action of $g$ on any $i$ is $i + k$. Since $g • i = i$ for all $i$, we have $i + k = i$, which implies $k = 0$. Therefore, $g = DihedralElem.rot 0$, which is the identity element.
          obtain ⟨k, rfl⟩ := hg_rot
          have hk : k = 0 := by
            exact?
          simp [hk];
          rfl;
        · -- Since $g$ is not a rotation, it must be a reflection.
          obtain ⟨k, hk⟩ : ∃ k : ZMod p, g = DihedralElem.ref k := by
            cases g <;> tauto;
          simp_all +decide [ DihedralElem.one ];
          -- If $k - i = i$ for all $i$, then $k = 2i$ for all $i$. But since $p$ is prime and not equal to 2, this can't hold for all $i$.
          have h_contra : ∀ i : ZMod p, k = 2 * i := by
            intro i; specialize hg i; rw [ show DihedralElem.ref k • i = k - i from rfl ] at hg; linear_combination' hg;
          have := h_contra 0; have := h_contra 1; simp_all +decide ;
          rcases p with ( _ | _ | _ | p ) <;> cases ‹ ( 2 : ZMod _ ) = 0 › <;> contradiction;
      contrapose! h_id;
      refine' ⟨ g * h⁻¹, _, _ ⟩ <;> simp_all +decide [ funext_iff ];
      · simp_all +decide [ MulAction.mul_smul ];
      · exact fun h => h_id <| by simpa using eq_inv_of_mul_eq_one_left h;

/-- The golden ratio φ = (1 + √5)/2 -/
noncomputable def goldenRatio : ℝ := (1 + Real.sqrt 5) / 2

theorem golden_ratio_equation : goldenRatio^2 = goldenRatio + 1 := by
  -- We can calculate $\phi^2$ directly.
  norm_num [goldenRatio]

theorem golden_ratio_pos : 0 < goldenRatio := by
  -- The golden ratio is positive because it is the sum of two positive numbers divided by 2.
  apply div_pos; exact add_pos zero_lt_one (Real.sqrt_pos.mpr (by norm_num)); exact zero_lt_two

/-- 2D rotation matrix by angle θ -/
def rotationMatrix (θ : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  !![Real.cos θ, -Real.sin θ; 
     Real.sin θ,  Real.cos θ]

noncomputable def pentagonRotation : Matrix (Fin 2) (Fin 2) ℝ :=
  rotationMatrix (2 * Real.pi / 5)

theorem rotation_char_poly (θ : ℝ) (x : ℝ) :
    Matrix.det (rotationMatrix θ - x • (1 : Matrix (Fin 2) (Fin 2) ℝ)) =
    x^2 - 2 * Real.cos θ * x + 1 := by
      -- Expand the determinant using the formula for a 2x2 matrix.
      simp [rotationMatrix, Matrix.det_fin_two];
      -- Combine like terms and use the Pythagorean identity.
      ring_nf
      rw [Real.sin_sq]
      ring

theorem cos_2pi5_eq_golden : Real.cos (2 * Real.pi / 5) = (goldenRatio - 1) / 2 := by
  have h : Real.cos (Real.pi / 5) = (1 + Real.sqrt 5) / 4 := Real.cos_pi_div_five
  have h2 : 2 * Real.pi / 5 = 2 * (Real.pi / 5) := by ring
  rw [h2, Real.cos_two_mul, h]
  simp [goldenRatio]
  ring_nf
  rw [Real.sq_sqrt (by norm_num)]
  ring

#check Complex.exp_ofReal_mul_I_re

theorem golden_ratio_eigenvalue :
    let θ := 2 * Real.pi / 5
    let lam := Complex.exp (Complex.I * θ)
    lam.re = (goldenRatio - 1) / 2 := by
      -- Using the fact that the real part of $e^{i\theta}$ is $\cos\theta$, we can simplify the expression.
      simp [Complex.exp_re, cos_2pi5_eq_golden]

theorem golden_ratio_eigenvalue' :
    let θ := 2 * Real.pi / 5
    let lam := Complex.exp (Complex.I * θ)
    lam.re = (goldenRatio - 1) / 2 := by
  simp only [mul_comm Complex.I, Complex.exp_ofReal_mul_I_re]
  exact cos_2pi5_eq_golden

theorem fibonacci_divisible_by_5 (k : ℕ) :
    5 ∣ Nat.fib (5 * k) := by
  have h : Nat.fib 5 = 5 := by rfl
  rw [← h]
  apply Nat.fib_dvd
  apply dvd_mul_right

theorem fibonacci_in_ray_0 (k : ℕ) :
    Nat.fib (5 * k) ∈ Ray 5 0 := by
      -- By definition of Fibonacci sequence, we know that $F_{5k}$ is divisible by 5.
      have h_div : 5 ∣ Nat.fib (5 * k) := by
        -- Apply the theorem that states 5 divides F_{5k} for any integer k.
        apply fibonacci_divisible_by_5;
      -- Since $5 \mid \text{Nat.fib}(5k)$, we have $\text{Nat.fib}(5k) \equiv 0 \pmod{5}$.
      have h_mod : Nat.fib (5 * k) % 5 = 0 := by
        -- Since $5 \mid \text{Nat.fib}(5k)$, we have $\text{Nat.fib}(5k) \equiv 0 \pmod{5}$ by definition of divisibility.
        apply Nat.mod_eq_zero_of_dvd h_div;
      -- Since $Nat.fib (5 * k) \equiv 0 \pmod{5}$, we have $Nat.fib (5 * k) \in Ray 5 0$ by definition of Ray.
      simp [Ray, h_mod];
      erw [ ZMod.natCast_eq_zero_iff ] ; exact Nat.dvd_of_mod_eq_zero h_mod

/-- A configuration for gap g modulo p -/
structure Configuration (p : ℕ) (g : ℕ) where
  start : ZMod p
  finish : ZMod p
  gap_condition : finish = start + g

def Configuration.IsAdmissible {p g : ℕ} [Fact p.Prime] (c : Configuration p g) : Prop :=
  c.start ≠ 0 ∧ c.finish ≠ 0

def Configuration.allConfigs (p g : ℕ) [Fact p.Prime] : Finset (Configuration p g) :=
  (Finset.univ : Finset (ZMod p)).map ⟨fun s => { start := s, finish := s + g, gap_condition := rfl }, 
    by intro x y h; simp at h; exact h⟩

def Configuration.admissibleConfigs (p g : ℕ) [Fact p.Prime] : Finset (Configuration p g) :=
  (Configuration.allConfigs p g).filter (fun c => c.IsAdmissible)

#check ZMod.card

theorem all_configs_count (p g : ℕ) [Fact p.Prime] :
    (Configuration.allConfigs p g).card = p := by
      -- The cardinality of `Finset.univ : Finset (ZMod p)` is `p` because `ZMod p` has `p` elements.
      simp [Configuration.allConfigs]

/-- Universal p-2 law -/
theorem config_count_universal (p g : ℕ) [hp : Fact p.Prime]
    (hg : Nat.Coprime g p) :
    (Configuration.admissibleConfigs p g).card = p - 2 := by
  -- Let's count the number of configurations where start = 0 or finish = 0.
  have h_count : (Configuration.admissibleConfigs p g).card = (Finset.univ : Finset (ZMod p)).card - ((Finset.univ.filter (fun s : ZMod p => s = 0)) ∪ (Finset.filter (fun s : ZMod p => s + g = 0) Finset.univ)).card := by
    rw [ show ( Configuration.admissibleConfigs p g : Finset ( Configuration p g ) ) = Finset.image ( fun s : ZMod p => Configuration.mk s ( s + ↑g ) ( by aesop ) ) ( Finset.univ \ ( Finset.filter ( fun s : ZMod p => s = 0 ) Finset.univ ∪ Finset.filter ( fun s : ZMod p => s + g = 0 ) Finset.univ ) ) from ?_ ];
    · rw [ Finset.card_image_of_injective _ fun x y hxy => by injection hxy, Finset.card_sdiff ] ; aesop;
    · ext ⟨s, f, h⟩; simp [Configuration.admissibleConfigs];
      unfold Configuration.allConfigs Configuration.IsAdmissible; aesop;
  cases eq_or_ne ( g : ZMod p ) 0 <;> simp_all +decide [ Finset.filter_eq', Finset.filter_or ];
  · rw [ ZMod.natCast_eq_zero_iff ] at * ; have := Nat.gcd_eq_right ‹_› ; aesop;
  · rw [ show ( Finset.filter ( fun s : ZMod p => s + ( g : ZMod p ) = 0 ) Finset.univ ) = { - ( g : ZMod p ) } by ext x; simp +decide [ add_eq_zero_iff_eq_neg ] ] ; aesop

/-- Partition theorem -/
theorem main_partition (p : ℕ) [hp : Fact p.Prime] (n : ℕ) :
    ∃! i : ZMod p, n ∈ Ray p i :=
  ray_partition_unique p n

/-- Canonicity -/
theorem main_canonical (p : ℕ) [hp : Fact p.Prime] (σ : AdditiveAut) :
    ∀ i : ZMod p, σ '' (Ray p i) = Ray p i :=
  ray_partition_canonical p σ
