/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 649b43c5-f0ff-4991-8647-849b0a1089ba
-/

/-
This module formalizes the Universal Modular Structure of Prime Pairs and k-Tuples.
It includes definitions for AdmissibleTuple, IsPrincipalKTuple, and PrincipalKTuples.
The main results proven are:
1. `k_tuple_pairs_theorem`: The number of principal pairs is q - 2.
2. `card_principal_eq_q_sub_image`: The number of principal k-tuples is q - |image(G)|.
3. `gap_independence`: The count depends only on the residue pattern of the gaps.
Corollaries `pairs_always_q_minus_2` and `distinct_gaps_gives_q_minus_k` are also proven.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-- An admissible k-tuple has gaps coprime to q and g_0 = 0 -/
def AdmissibleTuple (q : ℕ) (g : ℕ → ℕ) (k : ℕ) : Prop :=
  g 0 = 0 ∧ ∀ i, i < k → i ≠ 0 → Nat.gcd (g i) q = 1

/-- A k-tuple of residues is principal if all non-zero and satisfy gap constraint -/
def IsPrincipalKTuple (q : ℕ) [Fact (Nat.Prime q)] (g : ℕ → ℕ) (k : ℕ) [NeZero k] 
    (t : Fin k → Fin q) : Prop :=
  (∀ i, t i ≠ 0) ∧ ∀ i, (t i).val ≡ (t 0).val + g i [MOD q]

instance (q : ℕ) [Fact (Nat.Prime q)] (g : ℕ → ℕ) (k : ℕ) [NeZero k] : 
    DecidablePred (IsPrincipalKTuple q g k) := by
  intro t
  unfold IsPrincipalKTuple
  infer_instance

/-- Finset of principal k-tuples -/
def PrincipalKTuples (q : ℕ) [Fact (Nat.Prime q)] (g : ℕ → ℕ) (k : ℕ) [NeZero k] : 
    Finset (Fin k → Fin q) :=
  Finset.univ.filter (IsPrincipalKTuple q g k)

/-- Pairs always give q-2 -/
theorem pairs_always_q_minus_2 (q : ℕ) [Fact (Nat.Prime q)] (g : ℕ → ℕ)
    (hga : AdmissibleTuple q g 2) :
    (PrincipalKTuples q g 2).card = q - 2 := by
      rcases hga with ⟨ ha, hg ⟩;
      -- Let's count the number of pairs $(b_1, b_2)$ such that $b_2 - b_1 \equiv g_1 \pmod{q}$ and $b_1, b_2 \neq 0$.
      have h_count : Finset.card (Finset.filter (fun p : ZMod q × ZMod q => p.2 - p.1 = g 1 ∧ p.1 ≠ 0 ∧ p.2 ≠ 0) (Finset.univ : Finset (ZMod q × ZMod q))) = q - 2 := by
        have h_count : Finset.card (Finset.filter (fun b1 : ZMod q => b1 ≠ 0 ∧ b1 + g 1 ≠ 0) (Finset.univ : Finset (ZMod q))) = q - 2 := by
          have h_count : Finset.card (Finset.filter (fun b1 : ZMod q => b1 = 0 ∨ b1 = -g 1) (Finset.univ : Finset (ZMod q))) = 2 := by
            rw [ Finset.card_eq_two ];
            refine' ⟨ 0, - ( g 1 : ZMod q ), _, _ ⟩ <;> simp +decide [ Finset.ext_iff ];
            rw [ ZMod.natCast_eq_zero_iff ];
            exact fun h => by have := hg 1 ( by decide ) ( by decide ) ; have := Nat.gcd_eq_right h; simp_all +decide ;
          have h_count : Finset.card (Finset.filter (fun b1 : ZMod q => b1 ≠ 0 ∧ b1 ≠ -g 1) (Finset.univ : Finset (ZMod q))) = q - 2 := by
            rw [ show ( Finset.filter ( fun b1 : ZMod q => b1 ≠ 0 ∧ b1 ≠ - ( g 1 : ZMod q ) ) Finset.univ ) = Finset.univ \ ( Finset.filter ( fun b1 : ZMod q => b1 = 0 ∨ b1 = - ( g 1 : ZMod q ) ) Finset.univ ) by ext; aesop, Finset.card_sdiff ] ; aesop;
          convert h_count using 2 ; ext ; simp +decide [ add_eq_zero_iff_eq_neg ];
        convert h_count using 1;
        rw [ ← Finset.card_image_of_injective _ ( show Function.Injective ( fun b1 : ZMod q => ( b1, b1 + ( g 1 : ZMod q ) ) ) from fun a b h => by simpa using h ) ] ; congr ; ext ; simp +decide [ sub_eq_iff_eq_add' ] ; aesop;
      convert h_count using 1;
      fapply Finset.card_bij;
      use fun a ha => ( a 0, a 1 );
      · simp +decide [ PrincipalKTuples ];
        intro a ha; have := ha.1; have := ha.2; simp_all +decide [ Fin.forall_fin_two, IsPrincipalKTuple ] ;
        simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ];
        simp_all +decide [ ZMod.natCast_eq_zero_iff ];
        exact ⟨ Nat.not_dvd_of_pos_of_lt ( Nat.pos_of_ne_zero ( by aesop ) ) ( Fin.is_lt _ ), by rw [ ← this ] ; exact by rw [ ZMod.natCast_eq_zero_iff ] ; exact fun h => by have := Nat.le_of_dvd ( Nat.pos_of_ne_zero ( by aesop ) ) h; linarith [ Fin.is_lt ( a 1 ) ] ⟩;
      · simp +contextual [ funext_iff, Fin.forall_fin_two ];
        simp +decide [ ZMod.natCast_eq_natCast_iff' ];
        exact fun a₁ ha₁ a₂ ha₂ h₁ h₂ => ⟨ Fin.ext <| Nat.mod_eq_of_lt ( show ( a₁ 0 : ℕ ) < q from Fin.is_lt _ ) ▸ Nat.mod_eq_of_lt ( show ( a₂ 0 : ℕ ) < q from Fin.is_lt _ ) ▸ h₁, Fin.ext <| Nat.mod_eq_of_lt ( show ( a₁ 1 : ℕ ) < q from Fin.is_lt _ ) ▸ Nat.mod_eq_of_lt ( show ( a₂ 1 : ℕ ) < q from Fin.is_lt _ ) ▸ h₂ ⟩;
      · simp +decide [ PrincipalKTuples ];
        intro a b hab ha hb; use fun i => if i = 0 then ⟨ a.val, by
          exact ZMod.val_lt a ⟩ else ⟨ b.val, by
          exact ZMod.val_lt b ⟩ ; simp_all +decide [ IsPrincipalKTuple ] ;
        simp +decide [ ← ZMod.natCast_eq_natCast_iff, ← hab ]

/-- When all gaps distinct mod q, count is q-k -/
theorem distinct_gaps_gives_q_minus_k (q : ℕ) [Fact (Nat.Prime q)] (g : ℕ → ℕ) (k : ℕ) [NeZero k]
    (hga : AdmissibleTuple q g k)
    (h_distinct : (Finset.univ.image (fun i : Fin k => (g i) % q)).card = k) :
    (PrincipalKTuples q g k).card = q - k := by
      -- The number of valid starting points is q - k, as we exclude the k residues that would make any t_i zero.
      have h_valid_starting_points : Finset.card (Finset.filter (fun t₀ : Fin q => ∀ i : Fin k, (t₀ + g i) % q ≠ 0) (Finset.univ : Finset (Fin q))) = q - k := by
        have h_valid_starting_points : Finset.card (Finset.biUnion (Finset.image (fun i : Fin k => g i % q) Finset.univ) (fun r => Finset.filter (fun t₀ : Fin q => (t₀ + r) % q = 0) (Finset.univ : Finset (Fin q)))) = k := by
          rw [ Finset.card_biUnion ];
          · rw [ Finset.sum_congr rfl fun x hx => show Finset.card _ = 1 from ?_ ] ; aesop;
            -- Since $x$ is a residue modulo $q$, there exists a unique $t₀$ such that $t₀ \equiv -x \pmod{q}$.
            obtain ⟨t₀, ht₀⟩ : ∃ t₀ : Fin q, (t₀ + x) % q = 0 := by
              use ⟨ ( q - x % q ) % q, Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) ⟩ ; simp +decide [ ← ZMod.val_natCast, Nat.cast_sub ( show x % q ≤ q from Nat.le_of_lt <| Nat.mod_lt _ <| Nat.Prime.pos Fact.out ) ] ;
              simp +decide [ Nat.cast_sub ( show x % q ≤ q from Nat.le_of_lt <| Nat.mod_lt _ <| Nat.Prime.pos Fact.out ) ];
            rw [ Finset.card_eq_one ];
            use t₀; ext t; simp [ht₀];
            constructor <;> intro h <;> simp_all +decide [ ← ZMod.val_natCast, Nat.add_mod ];
            exact Fin.ext ( Nat.mod_eq_of_lt t.2 ▸ Nat.mod_eq_of_lt t₀.2 ▸ by simpa [ ← ZMod.natCast_eq_natCast_iff' ] using by linear_combination' h - ht₀ );
          · intros r hr s hs hrs; simp_all +decide [ Finset.disjoint_left ] ;
            intro a ha hb; have := Nat.modEq_iff_dvd.mp ( ha.trans hb.symm ) ; simp_all +decide [ ← ZMod.natCast_eq_zero_iff ] ;
            obtain ⟨ y, rfl ⟩ := hr; obtain ⟨ z, rfl ⟩ := hs; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff' ] ;
            simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd, sub_eq_iff_eq_add ];
        rw [ show ( Finset.filter ( fun t₀ : Fin q => ∀ i : Fin k, ( t₀ + g i ) % q ≠ 0 ) Finset.univ ) = Finset.univ \ ( Finset.biUnion ( Finset.image ( fun i : Fin k => g i % q ) Finset.univ ) fun r => Finset.filter ( fun t₀ : Fin q => ( t₀ + r ) % q = 0 ) Finset.univ ) from ?_ ] ; rw [ Finset.card_sdiff ] ; aesop;
        ext; simp [Finset.mem_biUnion, Finset.mem_image];
      convert h_valid_starting_points using 1;
      -- Define a bijection between the set of principal k-tuples and the set of valid starting points.
      have h_bijection : PrincipalKTuples q g k = Finset.image (fun t₀ : Fin q => fun i : Fin k => ⟨(t₀ + g i) % q, Nat.mod_lt _ (Nat.Prime.pos Fact.out)⟩) (Finset.filter (fun t₀ : Fin q => ∀ i : Fin k, (t₀ + g i) % q ≠ 0) (Finset.univ : Finset (Fin q))) := by
        ext t; simp [PrincipalKTuples, IsPrincipalKTuple];
        constructor <;> intro h;
        · use t 0;
          exact ⟨ fun i => by simpa [ Nat.ModEq, Nat.mod_eq_of_lt ( show ( t i : ℕ ) < q from Fin.is_lt _ ) ] using h.2 i |> Nat.ModEq.symm |> fun x => x.of_dvd ( dvd_refl q ) |> fun y => y.symm ▸ by simpa [ Nat.ModEq, Nat.mod_eq_of_lt ( show ( t i : ℕ ) < q from Fin.is_lt _ ) ] using Fin.val_injective.ne ( h.1 i ), funext fun i => Fin.ext <| by simpa [ Nat.ModEq, Nat.mod_eq_of_lt ( show ( t i : ℕ ) < q from Fin.is_lt _ ) ] using h.2 i |> Nat.ModEq.symm |> fun x => x.of_dvd ( dvd_refl q ) |> fun y => y.symm ▸ by simp [ Nat.ModEq, Nat.mod_eq_of_lt ( show ( t i : ℕ ) < q from Fin.is_lt _ ) ] ⟩;
        · rcases h with ⟨ a, ha, rfl ⟩ ; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ] ;
          cases hga ; aesop;
      rw [ h_bijection, Finset.card_image_of_injective ];
      intro a b h; have := congr_fun h ⟨ 0, NeZero.pos k ⟩ ; simp_all +decide [ Fin.ext_iff, Nat.mod_eq_of_lt ] ;
      exact Nat.mod_eq_of_lt a.2 ▸ Nat.mod_eq_of_lt b.2 ▸ by simpa [ ← ZMod.natCast_eq_natCast_iff' ] using this;

theorem k_tuple_pairs_theorem (q : ℕ) [Fact (Nat.Prime q)] (g : ℕ → ℕ) 
    (hga : AdmissibleTuple q g 2) :
    (PrincipalKTuples q g 2).card = q - 2 :=
  pairs_always_q_minus_2 q g hga

lemma card_principal_eq_q_sub_image (q : ℕ) [Fact (Nat.Prime q)] (g : ℕ → ℕ) (k : ℕ) [NeZero k]
    (hga : AdmissibleTuple q g k) :
    (PrincipalKTuples q g k).card = q - (Finset.univ.image (fun i : Fin k => (g i) % q)).card := by
      -- Let's define the set S of values that t must satisfy.
      set S := Finset.image (fun i : Fin k => (g i) % q) Finset.univ with hS_def;
      -- Let's count the number of valid $t_0$.
      have h_count : Finset.card (Finset.filter (fun t0 : Fin q => ∀ i : Fin k, (t0.val + (g i)) % q ≠ 0) (Finset.univ : Finset (Fin q))) = q - Finset.card S := by
        -- Let's count the number of valid $t_0$ by considering the complement of the set of forbidden values.
        have h_complement : Finset.filter (fun t0 : Fin q => ∀ i : Fin k, (t0.val + (g i)) % q ≠ 0) (Finset.univ : Finset (Fin q)) = Finset.univ \ Finset.biUnion S (fun x => Finset.filter (fun t0 : Fin q => t0.val ≡ q - x [MOD q]) (Finset.univ : Finset (Fin q))) := by
          ext t0; simp [hS_def];
          simp +decide [ ← ZMod.natCast_eq_natCast_iff, Nat.cast_sub ( show g _ % q ≤ q from Nat.le_of_lt ( Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) ) ) ];
          simp +decide [ ← ZMod.val_natCast, Nat.add_mod ];
          simp +decide [ add_eq_zero_iff_eq_neg ];
        rw [ h_complement, Finset.card_sdiff ] ; norm_num [ Finset.card_univ ];
        rw [ Finset.card_biUnion ];
        · rw [ Finset.sum_congr rfl fun x hx => Finset.card_eq_one.mpr _ ] ; aesop;
          intro x hx; use ⟨ ( q - x ) % q, Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) ⟩ ; ext; simp +decide [ Nat.ModEq ] ;
          simp +decide [ Fin.ext_iff, Nat.mod_eq_of_lt ];
        · intros x hx y hy hxy; simp_all +decide [ Finset.disjoint_left, Nat.ModEq ] ;
          intro a ha; contrapose! hxy; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff' ] ;
          rw [ Nat.cast_sub, Nat.cast_sub ] at hxy <;> norm_num at *;
          · exact Nat.mod_eq_of_lt ( show x < q from hx.choose_spec ▸ Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) ) ▸ Nat.mod_eq_of_lt ( show y < q from hy.choose_spec ▸ Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) ) ▸ by simpa [ ← ZMod.natCast_eq_natCast_iff' ] using hxy;
          · exact hy.choose_spec ▸ Nat.le_of_lt ( Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) );
          · exact hx.choose_spec ▸ Nat.le_of_lt ( Nat.mod_lt _ ( Nat.Prime.pos Fact.out ) );
      rw [ ← h_count, show PrincipalKTuples q g k = Finset.image ( fun t0 : Fin q => fun i : Fin k => ⟨ ( t0.val + g i ) % q, Nat.mod_lt _ ( Fact.out ( p := Nat.Prime q ) |> Nat.Prime.pos ) ⟩ ) ( Finset.filter ( fun t0 : Fin q => ∀ i : Fin k, ( t0.val + g i ) % q ≠ 0 ) Finset.univ ) from ?_ ];
      · rw [ Finset.card_image_of_injective _ fun x y hxy => _ ];
        simp +decide [ funext_iff, Fin.ext_iff ];
        intro x y h; have := h ⟨ 0, NeZero.pos k ⟩ ; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff' ] ;
        exact Nat.mod_eq_of_lt x.2 ▸ Nat.mod_eq_of_lt y.2 ▸ by simpa [ ← ZMod.natCast_eq_natCast_iff' ] using h;
      · ext t; simp [PrincipalKTuples, IsPrincipalKTuple];
        constructor <;> intro h;
        · use t 0;
          exact ⟨ fun i => by rw [ ← h.2 i ] ; exact fun hi => h.1 i <| Fin.ext <| Nat.eq_zero_of_dvd_of_lt ( Nat.dvd_of_mod_eq_zero hi ) <| Fin.is_lt _, funext fun i => Fin.ext <| by simpa [ Nat.ModEq, Nat.mod_eq_of_lt ( Fin.is_lt ( t i ) ) ] using h.2 i |> Nat.ModEq.symm ⟩;
        · rcases h with ⟨ a, ha, rfl ⟩ ; simp_all +decide [ Fin.ext_iff, Nat.ModEq ] ;
          intro i; have := hga.1; aesop;

theorem gap_independence (q : ℕ) [Fact (Nat.Prime q)] (k : ℕ) [NeZero k] (g₁ g₂ : ℕ → ℕ)
    (hga₁ : AdmissibleTuple q g₁ k) (hga₂ : AdmissibleTuple q g₂ k)
    (h_same_pattern : ∀ i j : Fin k, g₁ i ≡ g₁ j [MOD q] ↔ g₂ i ≡ g₂ j [MOD q]) :
    (PrincipalKTuples q g₁ k).card = (PrincipalKTuples q g₂ k).card := by
      rw [ card_principal_eq_q_sub_image, card_principal_eq_q_sub_image ];
      · -- Since the equivalence relations are the same, the number of equivalence classes is the same, hence the cardinalities of the images are equal.
        have h_card_eq : (Finset.image (fun i : Fin k => (g₁ i) % q) Finset.univ).card = (Finset.image (fun i : Fin k => (g₂ i) % q) Finset.univ).card := by
          have h_equiv_classes : ∀ (f : Fin k → ℕ), (∀ i j : Fin k, (f i ≡ f j [MOD q]) ↔ (g₁ i ≡ g₁ j [MOD q])) → (Finset.image (fun i : Fin k => f i % q) Finset.univ).card = (Finset.image (fun i : Fin k => (g₁ i) % q) Finset.univ).card := by
            intros f hf;
            have h_equiv_classes : Finset.card (Finset.image (fun i : Fin k => (f i) % q) Finset.univ) = Finset.card (Finset.image (fun i : Fin k => (g₁ i) % q) Finset.univ) := by
              have h_equiv_classes : ∀ (s : Finset (Fin k)), (Finset.image (fun i : Fin k => (f i) % q) s).card = (Finset.image (fun i : Fin k => (g₁ i) % q) s).card := by
                intros s
                induction' s using Finset.induction with i s hi ih;
                · norm_num;
                · by_cases hi' : ∃ j ∈ s, g₁ j ≡ g₁ i [MOD q] <;> simp_all +decide [ Finset.image_insert, Nat.ModEq ]
              exact h_equiv_classes Finset.univ;
            exact h_equiv_classes
          rw [ h_equiv_classes ( fun i => g₂ i ) fun i j => by specialize h_same_pattern i j; aesop ];
        rw [ h_card_eq ];
      · assumption;
      · assumption
