import Mathlib

/-!
# Proof-Carrying Apps — Certificate soundness (`PCA.Cert` namespace)

Category: Proof-Carrying Apps
Provenance: Aristotle theorem prover (Harmonic); assembled from two AXLE-verified
best-proof files into one registered module.  One development models the
group-theoretic core of Ed25519 signature verification; the other models a
tamper-check via deterministic re-certification of a serialized artifact.  The
name `PCA.Cert` serves both as the enclosing namespace and (for the tamper-check
model) as a record type — the two coexist, as `List` does.
-/

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000

set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace PCA

/-- An artifact shipped by the isolation engine: a code image together with the
policy/configuration it is meant to run under. -/
structure Artifact where
  /-- The code image, as a byte (word) list. -/
  code : List Nat
  /-- The policy/configuration image, as a byte (word) list. -/
  policy : List Nat
deriving DecidableEq

/-- A length-prefixed serialization of an artifact.  The length prefix makes the
encoding unambiguous, i.e. injective. -/
def Artifact.encode (a : Artifact) : List Nat :=
  a.code.length :: (a.code ++ a.policy)

theorem Artifact.encode_injective : Function.Injective Artifact.encode := by
  rintro ⟨c₁, p₁⟩ ⟨c₂, p₂⟩ h
  simp only [Artifact.encode, List.cons.injEq] at h
  obtain ⟨hlen, happ⟩ := h
  obtain ⟨hc, hp⟩ := List.append_inj happ hlen
  simp [hc, hp]

/-- A certificate accompanying an artifact: the digest of the artifact together
with the identifier of the safety claim that was discharged for it. -/
structure Cert where
  /-- Digest of the (serialized) artifact. -/
  digest : Nat
  /-- Identifier of the safety claim established for the artifact. -/
  claim : Nat
deriving DecidableEq

namespace Cert

variable (hash : List Nat → Nat) (claimOf : Artifact → Nat)

/-- Certification: run the checker on the artifact, recording its digest and the
claim that was established. -/
def certify (a : Artifact) : Cert :=
  ⟨hash a.encode, claimOf a⟩

/-- Re-proving is just re-running certification on the artifact at hand; the
checker is deterministic. -/
def reprove (a : Artifact) : Cert :=
  certify hash claimOf a

theorem reprove_eq_certify (a : Artifact) :
    reprove hash claimOf a = certify hash claimOf a := rfl

/-- **Soundness and completeness of the isolation engine's tamper check.**

Given a collision-free digest function `hash`, a certificate `c` issued for the
original artifact `orig`, and a received artifact `recv`, re-proving `recv`
reproduces the certificate `c` exactly when `recv` has not been tampered with,
i.e. when `recv = orig`.

Left-to-right is soundness of the check: a matching re-proof witnesses integrity.
Right-to-left is completeness: an untampered artifact always re-certifies to the
same certificate, since the checker is deterministic. -/
theorem reprove_matches_iff_untampered
    (hinj : Function.Injective hash)
    (orig recv : Artifact) (c : Cert) (hc : c = certify hash claimOf orig) :
    reprove hash claimOf recv = c ↔ recv = orig := by
  subst hc
  constructor
  · intro h
    have hd : hash recv.encode = hash orig.encode := congrArg Cert.digest h
    exact Artifact.encode_injective (hinj hd)
  · rintro rfl
    rfl

/-- Contrapositive reading: any tampering with the artifact is detected by
re-proving. -/
theorem reprove_ne_of_tampered
    (hinj : Function.Injective hash)
    (orig recv : Artifact) (c : Cert) (hc : c = certify hash claimOf orig)
    (htamper : recv ≠ orig) :
    reprove hash claimOf recv ≠ c := by
  intro h
  exact htamper ((reprove_matches_iff_untampered hash claimOf hinj orig recv c hc).mp h)

end Cert

end PCA

/-! ## Ed25519 verification -/

namespace PCA.Cert

/-!
An abstract model of Ed25519 signature verification.  We model the
group-theoretic core (the part an isolation engine's certificate checker relies
upon):

* `G` is the prime-order subgroup generated by the base point `B`, written
  additively, and equipped with a scalar action of `ZMod L` (`L` being the group
  order, i.e. the order of the base point).
* A secret key is a scalar `s : ZMod L`; the corresponding public key is
  `A = s • B`.
* A signature on a message `m` with nonce `r` is the pair `(R, S)` where
  `R = r • B` and `S = r + H(R, A, m) * s`.
* Verification of `(R, S)` against `A` checks `S • B = R + H(R, A, m) • A`.

The hash function `H` is left completely abstract, so no property of SHA-512 is
assumed anywhere.
-/

variable {L : ℕ} {G : Type*} {Msg : Type*}

/-- The public key associated with the secret scalar `s`. -/
def pubKey [AddCommGroup G] [Module (ZMod L) G] (B : G) (s : ZMod L) : G := s • B

/-- The Ed25519 verification equation for the signature `(R, S)` on message `m`
under public key `A`, with challenge hash `H`. -/
def Verify [AddCommGroup G] [Module (ZMod L) G] (B : G)
    (H : G → G → Msg → ZMod L) (A : G) (R : G) (S : ZMod L) (m : Msg) : Prop :=
  S • B = R + H R A m • A

/-- Honest signing: with nonce `r` and secret key `s`, the signature on `m` is
`(r • B, r + H(R, A, m) * s)`. -/
def sign [AddCommGroup G] [Module (ZMod L) G] (B : G)
    (H : G → G → Msg → ZMod L) (s r : ZMod L) (m : Msg) : G × ZMod L :=
  (r • B, r + H (r • B) (pubKey B s) m * s)

/-- **Soundness (and completeness) of Ed25519 verification.**

Assuming the base point `B` has order exactly `L` in the strong sense that
`x ↦ x • B` is injective on `ZMod L` (true for the prime-order subgroup
generated by the Ed25519 base point), a pair `(r • B, S)` passes the
verification equation against the public key `s • B` *if and only if* the
scalar `S` is exactly the one produced by honest signing with nonce `r` and
secret key `s`.

The `←` direction is completeness of the scheme; the `→` direction is
soundness: no other scalar `S` can be accepted for a given nonce commitment. -/
theorem ed25519_verify_sound [AddCommGroup G] [Module (ZMod L) G] {B : G}
    (hB : Function.Injective (fun x : ZMod L => x • B))
    (H : G → G → Msg → ZMod L) (s r S : ZMod L) (m : Msg) :
    Verify B H (pubKey B s) (r • B) S m ↔
      S = r + H (r • B) (pubKey B s) m * s := by
  unfold Verify pubKey
  rw [smul_smul, ← add_smul]
  exact hB.eq_iff

/-- Completeness: an honestly generated Ed25519 signature always verifies. -/
theorem ed25519_verify_complete [AddCommGroup G] [Module (ZMod L) G] {B : G}
    (H : G → G → Msg → ZMod L) (s r : ZMod L) (m : Msg) :
    Verify B H (pubKey B s) (sign B H s r m).1 (sign B H s r m).2 m := by
  unfold Verify sign pubKey
  simp [smul_smul, add_smul]

/-- Strict soundness restated: acceptance pins down the signature scalar
uniquely, hence two accepted signatures sharing a nonce commitment coincide. -/
theorem ed25519_verify_unique [AddCommGroup G] [Module (ZMod L) G] {B : G}
    (hB : Function.Injective (fun x : ZMod L => x • B))
    (H : G → G → Msg → ZMod L) (s r S S' : ZMod L) (m : Msg)
    (h : Verify B H (pubKey B s) (r • B) S m)
    (h' : Verify B H (pubKey B s) (r • B) S' m) :
    S = S' := by
  rw [ed25519_verify_sound hB] at h h'
  rw [h, h']

/-- Sanity check that the hypotheses above are satisfiable (the model is not
vacuous): in the cyclic group `ZMod L` with base point `1`, scalar
multiplication by the base point is injective. -/
example (L : ℕ) : Function.Injective (fun x : ZMod L => x • (1 : ZMod L)) := by
  intro x y h
  simpa using h

end PCA.Cert
