/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1910ecc3-86ee-4c19-9869-d41f767f1221

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Complex Real

open scoped BigOperators

@[simp] def φ : ℝ := (1 + √5) / 2

@[simp] def ψ : ℝ := (1 - √5) / 2

theorem phi_minimal_polynomial : φ^2 = φ + 1 := by ring_nf ; simp [φ] ; ring

theorem psi_minimal_polynomial : ψ^2 = ψ + 1 := by ring_nf ; simp [ψ] ; ring

theorem phi_psi_sum : φ + ψ = 1 := by
  -- By definition of φ and ψ, we have φ + ψ = (1 + √5)/2 + (1 - √5)/2 = 1.
  simp [φ, ψ]

theorem phi_psi_product : φ * ψ = -1 := by
  -- By definition of φ and ψ, we have φ * ψ = ((1 + Real.sqrt 5) / 2) * ((1 - Real.sqrt 5) / 2).
  simp [φ, ψ]

theorem phi_pos : 0 < φ := by simp [φ] ; positivity

theorem phi_gt_one : 1 < φ := by
  have h : 2 < √5 := by
    rw [← sqrt_sq (by norm_num : (0:ℝ) ≤ 2)]
    exact sqrt_lt_sqrt (by norm_num) (by norm_num)
  simp [φ] ; linarith

@[simp] def pentagon (k : Fin 5) : ℂ := exp (2 * π * I * k.val / 5)

@[simp] def pentDist (j k : Fin 5) : ℝ := ‖pentagon j - pentagon k‖

inductive D5
  | rot : Fin 5 → D5  -- rotations by 2πk/5
  | ref : Fin 5 → D5  -- reflections through vertex k

def D5.mul : D5 → D5 → D5
  | rot j, rot k => rot (j + k)
  | rot j, ref k => ref (k - j)
  | ref j, rot k => ref (j + k)
  | ref j, ref k => rot (k - j)

@[simp] def spiral (t : ℝ) : ℂ := exp (t * (1 + φ * I))

theorem spiral_ode : deriv spiral = fun t => spiral t * (1 + φ * I) := by
  -- The derivative of the exponential function is itself multiplied by the derivative of the exponent.
  have h_deriv_spiral : deriv (fun t : ℝ => Complex.exp (t * (1 + φ * Complex.I))) = fun t : ℝ => Complex.exp (t * (1 + φ * Complex.I)) * (1 + φ * Complex.I) := by
    -- Apply the chain rule to compute the derivative.
    funext t; exact (by
    -- The derivative of $e^{t(1 + \varphi i)}$ with respect to $t$ is $(1 + \varphi i)e^{t(1 + \varphi i)}$ by the chain rule.
    have h_deriv : deriv (fun t : ℝ => Complex.exp (t * (1 + φ * Complex.I))) t = (1 + φ * Complex.I) * Complex.exp (t * (1 + φ * Complex.I)) := by
      have h_chain : deriv (fun t : ℝ => Complex.exp (t * (1 + φ * Complex.I))) t = deriv (fun t : ℂ => Complex.exp (t * (1 + φ * Complex.I))) (t : ℂ) := by
        exact HasDerivAt.deriv ( by simpa using HasDerivAt.comp t ( Complex.hasDerivAt_exp _ ) ( HasDerivAt.mul ( hasDerivAt_id _ |> HasDerivAt.ofReal_comp ) ( hasDerivAt_const _ _ ) ) )
      exact h_chain.trans ( by norm_num [ mul_comm ] );
    rw [ h_deriv, mul_comm ]);
  exact?

@[simp] def spiralPrime (p : Nat.Primes) : ℂ := spiral (log p.val)

theorem spiralPrime_norm (p : Nat.Primes) :
    ‖spiralPrime p‖ = p.val := by
      -- The norm of a complex exponential is 1 because it lies on the unit circle in the complex plane.
      have h_norm : ∀ t : ℝ, ‖Complex.exp (t * (1 + φ * Complex.I))‖ = Real.exp t := by
        norm_num [ Complex.norm_exp ];
      -- Substitute $t = \log p$ into the norm function.
      have h_subst : ‖spiralPrime p‖ = Real.exp (Real.log p.val) := by
        apply h_norm;
      -- Apply the fact that Real.exp (Real.log x) = x for any positive x.
      rw [h_subst, Real.exp_log (Nat.cast_pos.mpr p.prop.pos)]

def eulerFactor_phi (p : Nat.Primes) (s : ℂ) : ℂ :=
    (1 - spiralPrime p ^ (-s))⁻¹

def brockianZeta (s : ℂ) : ℂ := ∏' p : Nat.Primes, eulerFactor_phi p s

def BrockianOp : (ℝ → ℂ) →ₗ[ℂ] (ℝ → ℂ) where
  toFun f := fun t => (1 + φ * I) * f t
  map_add' := by
    -- By definition of scalar multiplication and function addition, we can show that the map is linear.
    intros x y
    funext t
    simp [mul_add, add_mul]
  map_smul' := by
    -- By definition of scalar multiplication and function composition, we can show that the two functions are equal.
    intros m x
    funext t
    simp [mul_assoc, mul_comm, mul_left_comm]

def phi_gamma (s : ℂ) : ℂ := Gamma s * (2 * π) ^ (-s)

def brockianZeros : Set ℂ := {s | brockianZeta s = 0}

def pentagonalAverage (f : ℂ → ℂ) (s : ℂ) : ℂ :=
    (1/5) * ∑ k : Fin 5, f (s + 2 * π * I * k / 5)

theorem pentagon_chord_formula (j k : Fin 5) :
    pentDist j k = 2 * |Real.sin (π * (k.val - j.val : ℤ) / 5)| := by
  norm_num [ Complex.norm_def, Complex.normSq, Complex.exp_re, Complex.exp_im ];
  rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> ring <;> norm_num [ Real.sin_sq, Real.cos_sq ] <;> ring;
  · norm_num [ Real.cos_add, Real.sin_add ] ; ring;
  · nlinarith [ sq_nonneg ( Real.cos ( Real.pi * j.val * ( 2 / 5 ) ) - Real.cos ( Real.pi * k.val * ( 2 / 5 ) ) ), sq_nonneg ( Real.sin ( Real.pi * j.val * ( 2 / 5 ) ) - Real.sin ( Real.pi * k.val * ( 2 / 5 ) ) ), Real.cos_sq' ( Real.pi * j.val * ( 2 / 5 ) ), Real.cos_sq' ( Real.pi * k.val * ( 2 / 5 ) ) ]

theorem pentagon_two_distances :
    ∃! p : ℝ × ℝ, let s := p.1; let d := p.2;
      0 < s ∧ s < d ∧
      (∀ j k : Fin 5, j ≠ k → pentDist j k = s ∨ pentDist j k = d) := by
  -- Let's choose any solution $p$ from the set $S$.
  obtain ⟨p, hp⟩ : ∃ p : ℝ × ℝ, 0 < p.1 ∧ p.1 < p.2 ∧ ∀ j k : Fin 5, j ≠ k → pentDist j k = p.1 ∨ pentDist j k = p.2 := by
    simp_all +decide [ pentDist, pentagon ];
    refine' ⟨ 2 * |Real.sin ( Real.pi / 5 )|, _, 2 * |Real.sin ( 2 * Real.pi / 5 )|, _, _ ⟩;
    · exact mul_pos zero_lt_two ( abs_pos.mpr ( ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) ) ) );
    · exact mul_lt_mul_of_pos_left ( by rw [ abs_of_nonneg ( Real.sin_nonneg_of_nonneg_of_le_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) ), abs_of_nonneg ( Real.sin_nonneg_of_nonneg_of_le_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) ) ] ; rw [ ← Real.cos_pi_div_two_sub, ← Real.cos_pi_div_two_sub ] ; exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ) zero_lt_two;
    · -- By simplifying the expression using the properties of the exponential function and the sine function, we can show that the distance between any two points j and k is either 2|sin(π/5)| or 2|sin(2π/5)|.
      intros j k hjk
      have h_dist : ‖Complex.exp (2 * Real.pi * Complex.I * j / 5) - Complex.exp (2 * Real.pi * Complex.I * k / 5)‖ = 2 * |Real.sin (Real.pi * (j - k) / 5)| := by
        norm_num [ Complex.norm_def, Complex.normSq, Complex.exp_re, Complex.exp_im ];
        rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> norm_num [ Real.sin_sub_sin, Real.cos_sub_cos ] <;> ring_nf <;> norm_num [ Real.sin_sq, Real.cos_sq ] <;> ring_nf ;
        nlinarith [ Real.cos_sq' ( Real.pi * j * ( 2 / 5 ) + Real.pi * k * ( -2 / 5 ) ) ];
      fin_cases j <;> fin_cases k <;> simp +decide at hjk h_dist ⊢;
      all_goals ring_nf at *; norm_num at *;
      all_goals rw [ h_dist ] ; norm_num [ mul_div ] ;
      all_goals rw [ ← Real.sin_pi_sub ] ; ring_nf; norm_num;
  -- To prove uniqueness, assume there exists another pair $(s', d')$ satisfying the conditions.
  have h_unique : ∀ p' : ℝ × ℝ, (0 < p'.1 ∧ p'.1 < p'.2 ∧ ∀ j k : Fin 5, j ≠ k → pentDist j k = p'.1 ∨ pentDist j k = p'.2) → p' = p := by
    intros p' hp'
    have h_eq : p'.1 = p.1 ∧ p'.2 = p.2 := by
      have := hp'.2.2 0 1; have := hp.2.2 0 1; have := hp'.2.2 0 2; have := hp.2.2 0 2; have := hp'.2.2 0 3; have := hp.2.2 0 3; have := hp'.2.2 0 4; have := hp.2.2 0 4; simp_all +decide [ pentagon_chord_formula ] ;
      have h_eq : ‖1 - Complex.exp (2 * Real.pi * Complex.I / 5)‖ < ‖1 - Complex.exp (2 * Real.pi * Complex.I * 2 / 5)‖ := by
        norm_num [ Complex.norm_def, Complex.normSq, Complex.exp_re, Complex.exp_im ] at *;
        rw [ Real.sqrt_lt_sqrt_iff ] <;> ring_nf <;> norm_num [ Real.sin_sq, Real.cos_sq ] <;> ring_nf <;> norm_num [ mul_div ] at *;
        · exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] );
        · exact Real.cos_le_one _;
      grind;
    exact Prod.ext h_eq.left h_eq.right;
  exact ⟨ p, hp, h_unique ⟩

theorem pentagon_golden_diagonal :
    let s := 2 * Real.sin (π / 5)
    let d := 2 * Real.sin (2 * π / 5)
    d / s = φ := by
  rw [ show 2 * Real.pi / 5 = Real.pi / 5 + Real.pi / 5 by ring, Real.sin_add ];
  -- Cancel out the common factor of $2 \sin(\pi/5)$ in the numerator and denominator.
  field_simp [mul_comm, mul_assoc, mul_left_comm];
  rw [ @mul_comm ];
  rw [ mul_div_assoc, mul_div_cancel_left₀ ] <;> norm_num;
  · ring;
  · exact ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) )

instance : Group D5 where
  mul := D5.mul
  one := D5.rot 0
  inv := fun g => match g with
    | D5.rot k => D5.rot (-k)
    | D5.ref k => D5.ref k
  mul_assoc := by
    intro a b c;
    -- By definition of multiplication in D5, we can expand both sides of the equation.
    induction' a with a ha generalizing b c;
    · -- By definition of multiplication in D5, we can expand both sides of the equation for the rotation case.
      induction' b with b hb generalizing c;
      · induction' c with c hc generalizing a b;
        · fin_cases a <;> fin_cases b <;> fin_cases c <;> rfl;
        · fin_cases a <;> fin_cases b <;> fin_cases hc <;> rfl;
      · induction' c with c hc generalizing a hb;
        · fin_cases a <;> fin_cases hb <;> fin_cases c <;> rfl;
        · fin_cases a <;> fin_cases hb <;> fin_cases hc <;> rfl;
    · induction' b with b hb generalizing c <;> induction' c with c hc;
      · fin_cases ha <;> fin_cases b <;> fin_cases c <;> rfl;
      · fin_cases ha <;> fin_cases b <;> fin_cases hc <;> rfl;
      · fin_cases ha <;> fin_cases hb <;> fin_cases c <;> rfl;
      · fin_cases ha <;> fin_cases hb <;> fin_cases hc <;> rfl
  one_mul := by
    -- By definition of multiplication in the dihedral group, we have:
    have h_mul : ∀ a : D5, D5.mul (D5.rot 0) a = a := by
      -- By definition of multiplication in the dihedral group, we can split into cases based on whether `a` is a rotation or a reflection.
      intro a
      cases a <;> simp [D5.mul];
    -- By definition of multiplication in the dihedral group, we have that $1 * a = a$ for any $a \in D5$.
    convert h_mul using 1
  mul_one := by
    rintro ( a | a );
    · fin_cases a <;> rfl;
    · fin_cases a <;> rfl
  inv_mul_cancel := by
    rintro ( _ | _ ) <;> norm_num [ D5.mul ];
    · rename_i k; fin_cases k <;> rfl;
    · rename_i k;
      fin_cases k <;> rfl

theorem spiral_growth (t : ℝ) : ‖spiral t‖ = Real.exp t := by
  simp [spiral, Complex.norm_exp, Complex.ofReal_mul]

def brockianSpectrum : Set ℂ := {μ | ∃ f : ℝ → ℂ, f ≠ 0 ∧ BrockianOp f = μ • f}

theorem brockian_zeros_critical_line
    (h : brockianSpectrum = {s : ℂ | s.re = 1/2}) :
    ∀ s ∈ brockianZeros, s.re = 1/2 := by
  -- By definition of $brockianSpectrum$, we know that for any $s \in brockianSpectrum$, $s.re = 1/2$.
  have h_spectrum : ∀ s : ℂ, s ∈ brockianSpectrum → s.re = 1 / 2 := by
    exact fun s hs => h.subset hs;
  contrapose! h_spectrum;
  refine' ⟨ 1 + φ * Complex.I, _, _ ⟩ <;> norm_num [ Complex.ext_iff ];
  refine' ⟨ fun t => Complex.exp ( t * ( 1 + φ * Complex.I ) ), _, _ ⟩ <;> norm_num [ Complex.exp_ne_zero, Complex.differentiableAt_exp ];
  · exact fun h => absurd ( congr_fun h 0 ) ( by norm_num );
  · ext; norm_num [ BrockianOp ]

theorem brockian_implies_RH
    (h : brockianSpectrum = {s : ℂ | s.re = 1/2}) :
    ∀ s : ℂ, riemannZeta s = 0 → (s.re < 0 ∨ s.re = 1/2) := by
  -- If the Brockian spectrum is {s | s.re = 1/2}, then for any s in the Brockian spectrum, we have s.re = 1/2.
  have h_brockian_spectrum : ∀ s : ℂ, s ∈ brockianSpectrum → s.re = 1 / 2 := by
    aesop;
  contrapose! h_brockian_spectrum;
  use 1 + φ * Complex.I;
  constructor <;> norm_num [ Complex.ext_iff ];
  refine' ⟨ fun t => Complex.exp ( t * ( 1 + ( 1 + Real.sqrt 5 ) / 2 * Complex.I ) ), _, _ ⟩ <;> norm_num [ Complex.ext_iff, Complex.exp_re, Complex.exp_im ];
  · exact fun h => absurd ( congr_fun h 0 ) ( by norm_num );
  · ext; norm_num [ BrockianOp ]

def primePi (x : ℝ) : ℕ := ((Finset.range (Nat.floor x + 1)).filter Nat.Prime).card

def Nat.primes_le (N : ℕ) : Finset ℕ := (Finset.range (N + 1)).filter Nat.Prime

def zeroGap : ℝ := sInf { x | ∃ ρ₁ ρ₂, ρ₁ ∈ brockianZeros ∧ ρ₂ ∈ brockianZeros ∧ ρ₁.im ≠ ρ₂.im ∧ x = |ρ₁.im - ρ₂.im| }

def phi_index (z : ℂ) : ℝ := |arg z / Real.log ‖z‖ - φ|

structure VerificationStrategy where
  N_max : ℕ := 10^6
  precision : ℝ := (10 : ℝ) ^ (-50 : ℤ)
  height : ℝ := 10^13

def phi_primePi (x : ℝ) (δ : ℝ) : ℕ :=
    ((Finset.range (Nat.floor x + 1)).filter (fun n => Nat.Prime n ∧ phi_index (spiral (Real.log n)) < δ)).card
