import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
# Steane Code
Category: Frontier Qi
Target: QI.steane_code
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QI

/-! ## Setting

We work in the standard binary (symplectic) representation of Pauli errors, using `Bool`
for the field `GF(2)` (`false = 0`, `true = 1`, addition = `xor`, multiplication = `&&`).

A Pauli operator on the seven physical qubits is written `E = (x, z)`, standing for
`∏ᵢ Xᵢ^(xᵢ) Zᵢ^(zᵢ)` up to phase.  The Steane code is the CSS code built from the
`[7,4,3]` Hamming code: its stabilizer group is generated by three `X`-type and three
`Z`-type generators, one of each for every row of the Hamming parity-check matrix.
An `X`-type error is detected by the `Z`-type generators and vice versa, so the syndrome
of `E = (x, z)` is the pair of Hamming syndromes `(H x, H z)`.
-/

/-- Binary vectors indexed by the seven physical qubits. -/
abbrev Bits := Fin 7 → Bool

/-- A three-bit (Hamming) syndrome. -/
abbrev Syn := Bool × Bool × Bool

/-- A Pauli error on 7 qubits in binary symplectic form: `(x, z)` encodes
`∏ᵢ Xᵢ^(xᵢ) Zᵢ^(zᵢ)` up to phase. -/
abbrev Pauli := Bits × Bits

/-- Parity-check matrix of the `[7,4,3]` Hamming code: the column at qubit `i` is the
binary expansion of `i + 1`.  Its rows give both the `X`-type and the `Z`-type stabilizer
generators of the Steane code. -/
def steaneH (r : Fin 3) (i : Fin 7) : Bool := Nat.testBit (i.val + 1) (2 - r.val)

/-- The `GF(2)` inner product of two binary vectors of length 7. -/
def dot (u v : Bits) : Bool :=
  xor (xor (xor (u 0 && v 0) (u 1 && v 1)) (xor (u 2 && v 2) (u 3 && v 3)))
      (xor (xor (u 4 && v 4) (u 5 && v 5)) (u 6 && v 6))

/-- The three Hamming parity checks applied to a binary vector. -/
def parity (v : Bits) : Syn := (dot (steaneH 0) v, dot (steaneH 1) v, dot (steaneH 2) v)

/-- The column of the parity-check matrix at qubit `i`. -/
def col (i : Fin 7) : Syn := (steaneH 0 i, steaneH 1 i, steaneH 2 i)

/-- The syndrome of a Pauli error: three bits measured by the `Z`-type generators
(detecting the `X`-part) and three bits measured by the `X`-type generators
(detecting the `Z`-part). -/
def syndrome (E : Pauli) : Syn × Syn := (parity E.1, parity E.2)

/-- The (unique) binary vector of weight `≤ 1` having the given Hamming syndrome:
qubit `i` is flagged exactly when the syndrome equals the `i`-th column. -/
def unitOf (s : Syn) : Bits := fun i => decide (col i = s)

/-- The recovery map of the Steane code: from the measured syndrome it produces the Pauli
correction to apply. -/
def recover (s : Syn × Syn) : Pauli := (unitOf s.1, unitOf s.2)

/-- The binary vector supported on qubit `i`, with value `a` there. -/
def single (i : Fin 7) (a : Bool) : Bits := fun j => if j = i then a else false

/-- A Pauli error acting nontrivially on at most one qubit. -/
def IsSingleQubitError (E : Pauli) : Prop :=
  ∃ i : Fin 7, ∀ j : Fin 7, j ≠ i → E.1 j = false ∧ E.2 j = false

/-- A vector supported on `{i}` is `single i` of its value at `i`. -/
theorem eq_single {v : Bits} {i : Fin 7} (h : ∀ j : Fin 7, j ≠ i → v j = false) :
    v = single i (v i) := by
  funext j
  by_cases hj : j = i
  · subst hj; simp [single]
  · simp [single, hj, h j hj]

/-- Pointwise correctness of the decoder on weight-`≤ 1` vectors (a finite check over all
seven qubits and both values of the bit). -/
theorem unitOf_parity_single_apply : ∀ (i : Fin 7) (a : Bool) (j : Fin 7),
    unitOf (parity (single i a)) j = single i a j := by decide

theorem unitOf_parity_single (i : Fin 7) (a : Bool) :
    unitOf (parity (single i a)) = single i a :=
  funext (unitOf_parity_single_apply i a)

/-- The Steane code is a genuine CSS code: since the `X`-type and `Z`-type stabilizer
generators both come from the rows of `steaneH`, their commutation amounts to
`steaneH * steaneHᵀ = 0` over `GF(2)`, so all stabilizer generators pairwise commute. -/
theorem steane_css_commuting : ∀ r s : Fin 3, dot (steaneH r) (steaneH s) = false := by decide

/--
**The 7-qubit Steane (CSS) code corrects any single-qubit error.**

For a Pauli error `E` acting on at most one qubit:

* the explicit decoder `recover` applied to the measured syndrome returns exactly the
  error that occurred, so applying the correction undoes it;
* consequently distinct single-qubit errors have distinct syndromes — the code is
  nondegenerate of distance `3`, which is the Knill–Laflamme correctability criterion for
  the set of single-qubit Pauli errors.
-/
theorem steane_code :
    (∀ E : Pauli, IsSingleQubitError E → recover (syndrome E) = E) ∧
    (∀ E F : Pauli, IsSingleQubitError E → IsSingleQubitError F →
      syndrome E = syndrome F → E = F) := by
  have key : ∀ E : Pauli, IsSingleQubitError E → recover (syndrome E) = E := by
    rintro ⟨x, z⟩ ⟨i, hi⟩
    have hx : x = single i (x i) := eq_single fun j hj => (hi j hj).1
    have hz : z = single i (z i) := eq_single fun j hj => (hi j hj).2
    have h : recover (syndrome (single i (x i), single i (z i))) =
        (single i (x i), single i (z i)) := by
      simp [recover, syndrome, unitOf_parity_single]
    rw [hx, hz]
    exact h
  refine ⟨key, ?_⟩
  intro E F hE hF h
  rw [← key E hE, ← key F hF, h]

end QI

