import Mathlib

/-!
# Unitary Time Evolution
Category: Quantum Physics
Target: QPhys.unitary_time_evolution
Verification: pending
Provenance: Aristotle theorem prover (Harmonic)
-/

namespace QPhys

open Matrix

/-- The time-evolution operator `U(t) = exp(-i H t / ℏ)` generated by a Hamiltonian `H`. -/
noncomputable def timeEvolution {n : Type*} [Fintype n] [DecidableEq n]
    (H : Matrix n n ℂ) (hbar t : ℝ) : Matrix n n ℂ :=
  NormedSpace.exp ((-Complex.I * (t / hbar)) • H)

/-- The exponent `(-i t / ℏ) • H` is skew-adjoint when `H` is self-adjoint. -/
lemma conjTranspose_smul_of_isHermitian {n : Type*} [Fintype n] [DecidableEq n]
    {H : Matrix n n ℂ} (hH : H.IsHermitian) (hbar t : ℝ) :
    ((-Complex.I * (t / hbar)) • H)ᴴ = -((-Complex.I * (t / hbar)) • H) := by
  rw [Matrix.conjTranspose_smul, hH.eq]
  rw [← neg_smul]
  congr 1
  simp

/-- **Unitary time evolution.** For a self-adjoint Hamiltonian `H`, the operator
`U(t) = exp(-i H t / ℏ)` is unitary for every real time `t`. -/
theorem unitary_time_evolution {n : Type*} [Fintype n] [DecidableEq n]
    {H : Matrix n n ℂ} (hH : H.IsHermitian) (hbar t : ℝ) :
    timeEvolution H hbar t ∈ Matrix.unitaryGroup n ℂ := by
  set A : Matrix n n ℂ := (-Complex.I * (t / hbar)) • H
  have hstar : star (NormedSpace.exp A) = NormedSpace.exp (-A) := by
    show (NormedSpace.exp A)ᴴ = _
    rw [← Matrix.exp_conjTranspose, conjTranspose_smul_of_isHermitian hH]
  rw [Matrix.mem_unitaryGroup_iff]
  show NormedSpace.exp A * star (NormedSpace.exp A) = 1
  rw [hstar, ← Matrix.exp_add_of_commute A (-A) (Commute.neg_right (Commute.refl A)),
    add_neg_cancel, NormedSpace.exp_zero]

end QPhys

#print axioms QPhys.unitary_time_evolution

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

