/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4498a651-56f7-4e3e-8440-ab0be28a438a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def zeta5 : ℂ := Complex.exp (2 * Real.pi * Complex.I / 5)

def complexPentagonVertex (k : Fin 5) : ℂ := zeta5 ^ (k : ℕ)

theorem rotation_is_complex_mul (k : Fin 5) :
    complexPentagonVertex (k + 1) = zeta5 * complexPentagonVertex k := by
      -- By definition of complexPentagonVertex, we have complexPentagonVertex k = -1 / Real.sqrt 5 * zeta5^(-2 * k : ℤ).
      simp [complexPentagonVertex];
      -- Since $k$ is a `Fin 5`, we have $k + 1 \equiv (k + 1) \mod 5$.
      fin_cases k <;> simp +decide [ pow_succ', mul_assoc ];
      -- By definition of $zeta5$, we know that $zeta5^5 = 1$.
      simp [zeta5];
      -- By definition of exponentiation, we know that $(e^{2\pi i / 5})^5 = e^{2\pi i} = 1$.
      ring_nf;
      rw [ ← Complex.exp_nat_mul, mul_comm, Complex.exp_eq_one_iff.mpr ⟨ 1, by ring ⟩ ]

/-
The rotation matrix by 72 degrees is in the orthogonal group O(2).
-/
def theta72 : ℝ := 2 * Real.pi / 5

def rotate72 : Matrix (Fin 2) (Fin 2) ℝ :=
  !![Real.cos theta72, -Real.sin theta72;
     Real.sin theta72,  Real.cos theta72]

theorem rotate72_mem_orthogonalGroup : rotate72 ∈ Matrix.orthogonalGroup (Fin 2) ℝ := by
  constructor <;> norm_num [ ← Matrix.ext_iff, Fin.forall_fin_two ];
  · unfold rotate72;
    norm_num [ Matrix.mul_apply, ← sq ];
    constructor <;> ring;
  · unfold rotate72; norm_num [ Matrix.mul_apply ] ; ring_nf; norm_num;

/-
The projection from R^5 to C is equivariant under the cyclic shift of coordinates and rotation by 72 degrees in C.
-/
def cyclicShift (v : Fin 5 → ℝ) : Fin 5 → ℝ :=
  fun k => v (k - 1)

def projectToC (v : Fin 5 → ℝ) : ℂ :=
  ∑ k : Fin 5, (v k : ℂ) * complexPentagonVertex k

theorem parallel_projection_equivariant (v : Fin 5 → ℝ) :
    projectToC (cyclicShift v) = zeta5 * projectToC v := by
  unfold projectToC;
  norm_num [ Fin.sum_univ_succ, cyclicShift ];
  unfold complexPentagonVertex; norm_num [ ← Complex.exp_nat_mul, ← Complex.exp_add ] ; ring!;
  norm_num [ zeta5, ← Complex.exp_nat_mul, mul_div_cancel₀ ]

/-
Definitions for the Penrose tiling vertices and adjacency using the cut-and-project method with a shift parameter gamma. The physical projection maps Z^5 to C using powers of zeta5. The internal projection maps Z^5 to C using powers of zeta5^2. The window is the projection of the unit hypercube into the internal space. Vertices are points in the physical projection whose internal projection (shifted by gamma) falls within the window. Adjacency is defined by connecting vertices separated by a unit vector (power of zeta5).
-/
def physicalProjection (n : Fin 5 → ℤ) : ℂ :=
  ∑ k, (n k : ℂ) * complexPentagonVertex k

def internalProjection (n : Fin 5 → ℤ) : ℂ :=
  ∑ k, (n k : ℂ) * complexPentagonVertex (2 * k)

def internalProjectionReal (v : Fin 5 → ℝ) : ℂ :=
  ∑ k, (v k : ℂ) * complexPentagonVertex (2 * k)

def window : Set ℂ :=
  { z | ∃ v : Fin 5 → ℝ, (∀ k, 0 ≤ v k ∧ v k ≤ 1) ∧ z = internalProjectionReal v }

def PenroseTilingVertices (gamma : Fin 5 → ℝ) : Set ℂ :=
  { z | ∃ n : Fin 5 → ℤ, z = physicalProjection n ∧ (internalProjection n + internalProjectionReal gamma) ∈ window }

def PenroseAdjacency (gamma : Fin 5 → ℝ) (u v : ℂ) : Prop :=
  u ∈ PenroseTilingVertices gamma ∧ v ∈ PenroseTilingVertices gamma ∧
  ∃ k : Fin 5, v = u + complexPentagonVertex k

/-
The Penrose tiling graph, defined by connecting vertices separated by a unit vector (power of zeta5).
-/
def PenroseGraph (gamma : Fin 5 → ℝ) : SimpleGraph (PenroseTilingVertices gamma) :=
  SimpleGraph.fromRel (fun u v => ∃ k, v.1 = u.1 + complexPentagonVertex k)

/-
Setup for the l2 space on the Penrose tiling vertices.
-/
open MeasureTheory

instance (gamma : Fin 5 → ℝ) : Countable (PenroseTilingVertices gamma) := by
  have h_range : (Set.range physicalProjection).Countable := Set.countable_range physicalProjection
  have h_subset : PenroseTilingVertices gamma ⊆ Set.range physicalProjection := by
    rintro z ⟨n, rfl, _⟩
    exact Set.mem_range_self n
  have h_count : (PenroseTilingVertices gamma).Countable := Set.Countable.mono h_subset h_range
  exact Set.Countable.to_subtype h_count

noncomputable instance (gamma : Fin 5 → ℝ) : MeasurableSpace (PenroseTilingVertices gamma) := ⊤

instance (gamma : Fin 5 → ℝ) : MeasurableSingletonClass (PenroseTilingVertices gamma) := ⟨fun _ => trivial⟩

noncomputable def verticesMeasure (gamma : Fin 5 → ℝ) : Measure (PenroseTilingVertices gamma) := Measure.count

noncomputable instance (gamma : Fin 5 → ℝ) : MeasureSpace (PenroseTilingVertices gamma) := ⟨verticesMeasure gamma⟩

abbrev l2_space (gamma : Fin 5 → ℝ) : Type := Lp ℂ 2 (verticesMeasure gamma)

noncomputable instance (gamma : Fin 5 → ℝ) : NormedAddCommGroup (l2_space gamma) :=
  Lp.instNormedAddCommGroup

noncomputable instance (gamma : Fin 5 → ℝ) : NormedSpace ℂ (l2_space gamma) :=
  Lp.instNormedSpace

noncomputable instance (gamma : Fin 5 → ℝ) : CompleteSpace (l2_space gamma) :=
  Lp.instCompleteSpace

/-
Definition of potential neighbors in the complex plane and proof of their finiteness.
-/
def potentialNeighbors (u : ℂ) : Set ℂ :=
  (Set.range (fun k : Fin 5 => u + complexPentagonVertex k)) ∪
  (Set.range (fun k : Fin 5 => u - complexPentagonVertex k))

lemma potentialNeighbors_finite (u : ℂ) : (potentialNeighbors u).Finite := by
  apply Set.Finite.union <;> apply Set.finite_range

/-
Proof that the neighbors of a vertex are a subset of the potential neighbors.
-/
lemma neighbor_subset_potential (gamma : Fin 5 → ℝ) (u : PenroseTilingVertices gamma) :
    (PenroseGraph gamma).neighborSet u ⊆ {v | v.1 ∈ potentialNeighbors u.1} := by
      intro v hv
      obtain ⟨k, hk⟩ := hv;
      cases hk <;> simp_all +decide [ Set.mem_union, Set.mem_range, potentialNeighbors ];
      · tauto;
      · grind +ring

/-
The neighbor set of any vertex in the Penrose graph is finite.
-/
instance (gamma : Fin 5 → ℝ) (v : PenroseTilingVertices gamma) : Finite ((PenroseGraph gamma).neighborSet v) := by
  let S := potentialNeighbors v.1
  have hS : S.Finite := potentialNeighbors_finite v.1
  have h_subset : (PenroseGraph gamma).neighborSet v ⊆ { w | w.1 ∈ S } := neighbor_subset_potential gamma v
  have h_image_subset : Subtype.val '' ((PenroseGraph gamma).neighborSet v) ⊆ S := by
    rintro _ ⟨w, hw, rfl⟩
    exact h_subset hw
  have h_image_finite : (Subtype.val '' ((PenroseGraph gamma).neighborSet v)).Finite :=
    Set.Finite.subset hS h_image_subset
  apply Set.Finite.of_finite_image h_image_finite
  intro x _ y _ h
  exact Subtype.eq h

/-
The Penrose graph is locally finite, meaning every vertex has a finite number of neighbors.
-/
noncomputable instance (gamma : Fin 5 → ℝ) : (PenroseGraph gamma).LocallyFinite :=
  fun v => Fintype.ofFinite ((PenroseGraph gamma).neighborSet v)

/-
The raw adjacency operator acting on functions on the vertices.
-/
def rawAdjacency (gamma : Fin 5 → ℝ) (f : PenroseTilingVertices gamma → ℂ) (u : PenroseTilingVertices gamma) : ℂ :=
  ∑ v ∈ (PenroseGraph gamma).neighborFinset u, f v

/-
The degree of every vertex in the Penrose graph is bounded by 10.
-/
lemma degree_bound (gamma : Fin 5 → ℝ) (u : PenroseTilingVertices gamma) :
    (PenroseGraph gamma).degree u ≤ 10 := by
  -- The degree of a vertex is the number of neighbors. The neighbors are a subset of the potential neighbors. The set of potential neighbors has size at most 10 (it is the union of two sets of size at most 5). Thus the degree is at most 10.
  have h_degree_le_10 : ∀ u : PenroseTilingVertices gamma, (PenroseGraph gamma).degree u ≤ (potentialNeighbors u.1).ncard := by
    intro u
    have h_subset : (PenroseGraph gamma).neighborSet u ⊆ {v : PenroseTilingVertices gamma | v.1 ∈ potentialNeighbors u.1} := by
      exact?;
    have h_card : (Set.ncard {v : PenroseTilingVertices gamma | v.1 ∈ potentialNeighbors u.1}) ≤ (potentialNeighbors u.1).ncard := by
      have h_card : (Set.ncard (Set.image (fun v : PenroseTilingVertices gamma => v.1) {v : PenroseTilingVertices gamma | v.1 ∈ potentialNeighbors u.1})) ≤ (potentialNeighbors u.1).ncard := by
        apply Set.ncard_le_ncard;
        · aesop_cat;
        · exact potentialNeighbors_finite _;
      rwa [ Set.ncard_image_of_injective _ fun x y hxy => by aesop ] at h_card;
    refine' le_trans _ h_card;
    rw [ Set.ncard_def ];
    rw [ Set.encard ];
    rw [ ENat.card ];
    rw [ SimpleGraph.degree ];
    rw [ ← Set.ncard_coe_finset ];
    rw [ Set.ncard_def ];
    rw [ Set.encard ];
    rw [ ENat.card ];
    gcongr;
    · simp +zetaDelta at *;
      exact Set.Finite.subset ( Set.Finite.preimage ( fun x => by aesop ) ( potentialNeighbors_finite u.1 ) ) fun x hx => hx;
    · exact Cardinal.mk_le_mk_of_subset fun x hx => h_subset <| by simpa using hx;
  have h_card_le_10 : ∀ u : ℂ, (potentialNeighbors u).ncard ≤ 10 := by
    intros u
    have h_card_le_10 : (potentialNeighbors u).ncard ≤ Finset.card (Finset.image (fun k : Fin 5 => u + complexPentagonVertex k) Finset.univ ∪ Finset.image (fun k : Fin 5 => u - complexPentagonVertex k) Finset.univ) := by
      rw [ ← Set.ncard_coe_finset ] ; aesop;
    exact h_card_le_10.trans ( le_trans ( Finset.card_union_le _ _ ) ( by exact le_trans ( add_le_add ( Finset.card_image_le ) ( Finset.card_image_le ) ) ( by decide ) ) );
  exact le_trans ( h_degree_le_10 u ) ( h_card_le_10 u )

/-
Norm bound for the raw adjacency operator using eLpNorm.
-/
lemma rawAdjacency_bound (gamma : Fin 5 → ℝ) (f : PenroseTilingVertices gamma → ℂ) :
    eLpNorm (rawAdjacency gamma f) 2 (verticesMeasure gamma) ≤ 10 * eLpNorm f 2 (verticesMeasure gamma) := by
  rw [ MeasureTheory.eLpNorm_eq_lintegral_rpow_enorm ];
  · -- Applying the Cauchy-Schwarz inequality to the sum inside the norm.
    have h_cauchy_schwarz : ∀ u : PenroseTilingVertices gamma, ‖rawAdjacency gamma f u‖ₑ ^ 2 ≤ 10 * ∑ v ∈ (PenroseGraph gamma).neighborFinset u, ‖f v‖ₑ ^ 2 := by
      intro u
      have h_cauchy_schwarz_step : ‖∑ v ∈ (PenroseGraph gamma).neighborFinset u, f v‖ ^ 2 ≤ (∑ v ∈ (PenroseGraph gamma).neighborFinset u, ‖f v‖) ^ 2 := by
        exact pow_le_pow_left₀ ( norm_nonneg _ ) ( norm_sum_le _ _ ) _;
      have h_cauchy_schwarz_step : (∑ v ∈ (PenroseGraph gamma).neighborFinset u, ‖f v‖) ^ 2 ≤ 10 * ∑ v ∈ (PenroseGraph gamma).neighborFinset u, ‖f v‖ ^ 2 := by
        have h_cauchy_schwarz_step : ∀ (s : Finset (PenroseTilingVertices gamma)), (∑ v ∈ s, ‖f v‖) ^ 2 ≤ (Finset.card s) * ∑ v ∈ s, ‖f v‖ ^ 2 := by
          exact?;
        exact le_trans ( h_cauchy_schwarz_step _ ) ( mul_le_mul_of_nonneg_right ( mod_cast by simpa using degree_bound gamma u ) ( Finset.sum_nonneg fun _ _ => sq_nonneg _ ) );
      convert ENNReal.ofReal_le_ofReal ( le_trans ‹_› h_cauchy_schwarz_step ) using 1;
      · rw [ ENNReal.ofReal_pow ] <;> norm_num [ rawAdjacency ];
      · simp +decide [ ENNReal.ofReal_mul, ENNReal.ofReal_sum_of_nonneg, sq_nonneg ];
    -- Summing over all vertices $u$, we get:
    have h_sum : ∫⁻ u : PenroseTilingVertices gamma, ‖rawAdjacency gamma f u‖ₑ ^ 2 ≤ 10 * ∫⁻ u : PenroseTilingVertices gamma, ∑ v ∈ (PenroseGraph gamma).neighborFinset u, ‖f v‖ₑ ^ 2 := by
      convert MeasureTheory.lintegral_mono h_cauchy_schwarz using 1;
      rw [ MeasureTheory.lintegral_const_mul' ] ; norm_num;
    -- By Fubini's theorem, we can interchange the order of summation.
    have h_fubini : ∫⁻ u : PenroseTilingVertices gamma, ∑ v ∈ (PenroseGraph gamma).neighborFinset u, ‖f v‖ₑ ^ 2 = ∫⁻ v : PenroseTilingVertices gamma, ∑ u ∈ (PenroseGraph gamma).neighborFinset v, ‖f v‖ₑ ^ 2 := by
      have h_fubini : ∫⁻ u : PenroseTilingVertices gamma, ∑ v ∈ (PenroseGraph gamma).neighborFinset u, ‖f v‖ₑ ^ 2 = ∫⁻ u : PenroseTilingVertices gamma, ∫⁻ v : PenroseTilingVertices gamma, ‖f v‖ₑ ^ 2 * (if v ∈ (PenroseGraph gamma).neighborFinset u then 1 else 0) := by
        congr;
        ext u;
        rw [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ];
        change ∑ v ∈ ( PenroseGraph gamma ).neighborFinset u, ‖f v‖ₑ ^ 2 = ∫⁻ v in ( PenroseGraph gamma ).neighborFinset u, ‖f v‖ₑ ^ 2;
        · rw [ MeasureTheory.lintegral_finset ];
          simp +decide [ MeasureTheory.MeasureSpace.volume ];
          unfold verticesMeasure; aesop;
        · exact?;
        · filter_upwards [ ] with v using by aesop;
      rw [ h_fubini, ← MeasureTheory.lintegral_lintegral_swap ];
      · refine' MeasureTheory.lintegral_congr fun v => _;
        rw [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ];
        change ∫⁻ u in ( PenroseGraph gamma ).neighborFinset v, ‖f v‖ₑ ^ 2 = ∑ u ∈ ( PenroseGraph gamma ).neighborFinset v, ‖f v‖ₑ ^ 2;
        · simp +decide [ MeasureTheory.lintegral_const ];
          erw [ mul_comm, MeasureTheory.Measure.count_apply ] ; aesop;
          exact?;
        · exact?;
        · filter_upwards [ ] with u ; simp +decide [ SimpleGraph.adj_comm ];
          simp +decide [ Set.indicator, SimpleGraph.adj_comm ];
      · refine' AEMeasurable.mul _ _;
        · fun_prop;
        · refine' Measurable.aemeasurable _;
          exact Measurable.ite ( by exact? ) measurable_const measurable_const;
    -- Since the degree of each vertex is at most 10, we have:
    have h_degree_bound : ∀ v : PenroseTilingVertices gamma, ∑ u ∈ (PenroseGraph gamma).neighborFinset v, ‖f v‖ₑ ^ 2 ≤ 10 * ‖f v‖ₑ ^ 2 := by
      simp +zetaDelta at *;
      exact fun a ha => mul_le_mul_right' ( mod_cast degree_bound gamma ⟨ a, ha ⟩ ) _;
    -- Therefore, we can conclude:
    have h_final : ∫⁻ u : PenroseTilingVertices gamma, ‖rawAdjacency gamma f u‖ₑ ^ 2 ≤ 100 * ∫⁻ v : PenroseTilingVertices gamma, ‖f v‖ₑ ^ 2 := by
      refine le_trans h_sum ?_;
      rw [ h_fubini ];
      rw [ show ( 100 : ENNReal ) = 10 * 10 by norm_num, mul_assoc ];
      refine' mul_le_mul_left' _ _;
      rw [ ← MeasureTheory.lintegral_const_mul ];
      · apply_rules [ MeasureTheory.lintegral_mono ];
      · fun_prop;
    convert ENNReal.rpow_le_rpow h_final _ using 1 <;> norm_num;
    congr! 1;
    · rw [ MeasureTheory.eLpNorm_eq_lintegral_rpow_enorm ] <;> norm_num;
      rw [ ENNReal.mul_rpow_of_nonneg ] <;> norm_num;
      rw [ show ( 100 : ENNReal ) = 10 ^ 2 by norm_num, ← ENNReal.rpow_natCast, ← ENNReal.rpow_mul ] ; norm_num;
      rfl;
    · norm_num;
  · norm_num;
  · decide +revert

/-
Linear map definition of raw adjacency and proof that it preserves L2 membership.
-/
def rawAdjacencyLinearMap (gamma : Fin 5 → ℝ) : (PenroseTilingVertices gamma → ℂ) →ₗ[ℂ] (PenroseTilingVertices gamma → ℂ) where
  toFun := rawAdjacency gamma
  map_add' f g := by
    ext u
    simp [rawAdjacency, Finset.sum_add_distrib]
  map_smul' c f := by
    ext u
    simp [rawAdjacency, Finset.mul_sum]

lemma memLp_rawAdjacency (gamma : Fin 5 → ℝ) {f : PenroseTilingVertices gamma → ℂ}
    (hf : MemLp f 2 (verticesMeasure gamma)) :
    MemLp (rawAdjacency gamma f) 2 (verticesMeasure gamma) := by
      refine' ⟨ _, _ ⟩;
      · exact?;
      · refine' lt_of_le_of_lt ( rawAdjacency_bound gamma f ) _;
        exact ENNReal.mul_lt_top ENNReal.coe_lt_top ( hf.eLpNorm_lt_top )

/-
Almost everywhere equality with respect to counting measure implies pointwise equality.
-/
lemma ae_eq_eq_of_count {α : Type*} [MeasurableSpace α] [MeasurableSingletonClass α] (f g : α → ℂ)
    (h : f =ᵐ[Measure.count] g) : f = g := by
  ext x
  have h_null : Measure.count {a | ¬ f a = g a} = 0 := h
  have h_empty : {a | ¬ f a = g a} = ∅ := by
    rw [← Measure.count_eq_zero_iff]
    exact h_null
  have h_x : x ∉ {a | ¬ f a = g a} := by
    rw [h_empty]
    exact Set.not_mem_empty x
  simpa using h_x

/-
Measurability of the raw adjacency function.
-/
lemma aestronglyMeasurable_rawAdjacency (gamma : Fin 5 → ℝ) (f : PenroseTilingVertices gamma → ℂ) :
    AEStronglyMeasurable (rawAdjacency gamma f) (verticesMeasure gamma) := by
  apply Measurable.aestronglyMeasurable
  apply measurable_of_countable

/-
Definition of the adjacency operator on AEEqFun.
-/
def adjacencyAEEqFun (gamma : Fin 5 → ℝ) : (PenroseTilingVertices gamma →ₘ[verticesMeasure gamma] ℂ) → (PenroseTilingVertices gamma →ₘ[verticesMeasure gamma] ℂ) :=
  Quotient.lift (fun f : {f : PenroseTilingVertices gamma → ℂ // AEStronglyMeasurable f (verticesMeasure gamma)} =>
    AEEqFun.mk (rawAdjacency gamma f.1) (by
      apply Measurable.aestronglyMeasurable
      apply measurable_of_countable))
    (fun f g h => by
      apply AEEqFun.mk_eq_mk.mpr
      have h_eq : f.1 = g.1 := ae_eq_eq_of_count f.1 g.1 h
      rw [h_eq])

/-
Linearity lemmas for adjacencyAEEqFun.
-/
lemma adjacencyAEEqFun_add (gamma : Fin 5 → ℝ) (f g : PenroseTilingVertices gamma →ₘ[verticesMeasure gamma] ℂ) :
    adjacencyAEEqFun gamma (f + g) = adjacencyAEEqFun gamma f + adjacencyAEEqFun gamma g := by
      induction' f using Quotient.inductionOn' with f;
      induction' g using Quotient.inductionOn' with g;
      erw [ Quotient.eq'' ];
      filter_upwards [ ] with x;
      simp +decide [ rawAdjacency, Finset.sum_add_distrib ]

lemma adjacencyAEEqFun_smul (gamma : Fin 5 → ℝ) (c : ℂ) (f : PenroseTilingVertices gamma →ₘ[verticesMeasure gamma] ℂ) :
    adjacencyAEEqFun gamma (c • f) = c • adjacencyAEEqFun gamma f := by
      obtain ⟨ f, hf ⟩ := f;
      convert AEEqFun.mk_eq_mk.mpr _;
      filter_upwards [ ] with u using by simp +decide [ rawAdjacency, Finset.mul_sum _ _ _ ] ;

/-
The adjacency operator on AEEqFun preserves L2 membership.
-/
lemma adjacencyAEEqFun_memLp (gamma : Fin 5 → ℝ) (f : PenroseTilingVertices gamma →ₘ[verticesMeasure gamma] ℂ)
    (hf : f ∈ MeasureTheory.Lp ℂ 2 (verticesMeasure gamma)) :
    adjacencyAEEqFun gamma f ∈ MeasureTheory.Lp ℂ 2 (verticesMeasure gamma) := by
      obtain ⟨g, hg⟩ := f;
      -- Apply the lemma that states if `f` is in L2, then `rawAdjacency f` is also in L2.
      have h_memLp : MemLp (rawAdjacency gamma g) 2 (verticesMeasure gamma) := by
        apply memLp_rawAdjacency;
        rw [ MeasureTheory.MemLp ];
        rw [ MeasureTheory.Lp.mem_Lp_iff_eLpNorm_lt_top ] at hf ; aesop;
      convert h_memLp using 1;
      constructor <;> intro h <;> rw [ MeasureTheory.Lp ] at * <;> norm_num at *;
      · exact h_memLp;
      · convert h_memLp.eLpNorm_lt_top using 1;
        rw [ MeasureTheory.eLpNorm_congr_ae ];
        exact AEEqFun.coeFn_mk _ _

/-
Linear map definition of the adjacency operator on the L2 space.
-/
def adjacencyLinearMap (gamma : Fin 5 → ℝ) : l2_space gamma →ₗ[ℂ] l2_space gamma where
  toFun f := ⟨adjacencyAEEqFun gamma f.1, adjacencyAEEqFun_memLp gamma f.1 f.2⟩
  map_add' f g := by
    apply Subtype.eq
    exact adjacencyAEEqFun_add gamma f.1 g.1
  map_smul' c f := by
    apply Subtype.eq
    exact adjacencyAEEqFun_smul gamma c f.1

#check adjacencyLinearMap
#check rawAdjacency_bound

/-
The cardinality of the set of potential neighbors is at most 10.
-/
lemma potentialNeighbors_card_le_10 (u : ℂ) : (potentialNeighbors u).ncard ≤ 10 := by
  have h_card : (potentialNeighbors u).ncard ≤ Set.ncard (Set.image (fun k : Fin 5 => u + complexPentagonVertex k) Set.univ) + Set.ncard (Set.image (fun k : Fin 5 => u - complexPentagonVertex k) Set.univ) := by
    convert Set.ncard_union_le _ _ using 1;
    simp +decide [ Set.ncard_eq_toFinset_card' ];
  exact h_card.trans ( add_le_add ( Set.ncard_image_le ) ( Set.ncard_image_le ) ) |> le_trans <| by norm_num [ Set.ncard_univ ] ;

#check adjacencyAEEqFun_add
#check adjacencyAEEqFun_smul

/-
Definition and bound of the degree function.
-/
def degreeFunction (gamma : Fin 5 → ℝ) (u : PenroseTilingVertices gamma) : ℂ :=
  ((PenroseGraph gamma).degree u : ℂ)

lemma degreeFunction_bound (gamma : Fin 5 → ℝ) (u : PenroseTilingVertices gamma) :
    ‖degreeFunction gamma u‖ ≤ 10 := by
      -- By definition of degreeFunction, we know that its norm is bounded by the degree of the vertex.
      simp [degreeFunction];
      convert degree_bound gamma u using 1

/-
Measurability of the degree-weighted function.
-/
lemma aestronglyMeasurable_degree (gamma : Fin 5 → ℝ) (f : PenroseTilingVertices gamma → ℂ) :
    AEStronglyMeasurable (fun u => degreeFunction gamma u * f u) (verticesMeasure gamma) := by
  apply Measurable.aestronglyMeasurable
  apply measurable_of_countable

#check Perfect
#check IsTotallyDisconnected
#check spectrum
