/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7aa1b75c-1878-4cfa-ada6-5ae50a9f33bd

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Classical
open Real Complex Finset Matrix
open scoped ComplexConjugate

/-- The golden ratio φ = (1 + √5)/2 ≈ 1.618... -/
def φ : ℝ := (1 + sqrt 5) / 2

/-- The golden conjugate φ̄ = (1 - √5)/2 ≈ -0.618... -/
def φ_bar : ℝ := (1 - sqrt 5) / 2

theorem sqrt5_gt_one : 1 < sqrt 5 := by
  have h : sqrt (1 : ℝ) < sqrt 5 := sqrt_lt_sqrt (by norm_num) (by norm_num)
  simpa using h

theorem sqrt5_gt_two : 2 < sqrt 5 := by
  rw [← sqrt_sq (by norm_num : (0 : ℝ) ≤ 2)]
  exact sqrt_lt_sqrt (by norm_num) (by norm_num)

theorem φ_pos : 0 < φ := by
  unfold φ
  have : 0 < sqrt 5 := sqrt_pos.2 (by norm_num)
  linarith

theorem φ_ne_zero : φ ≠ 0 := ne_of_gt φ_pos

theorem φ_gt_one : 1 < φ := by
  unfold φ
  linarith [sqrt5_gt_two]

/-- The fundamental equation: φ² = φ + 1 -/
theorem φ_squared : φ ^ 2 = φ + 1 := by
  unfold φ
  field_simp
  ring
  rw [sq_sqrt (by norm_num : (0 : ℝ) ≤ 5)]
  ring

/-- Polynomial form: φ² - φ - 1 = 0 -/
theorem φ_equation : φ ^ 2 - φ - 1 = 0 := by
  linarith [φ_squared]

/-- The reciprocal identity: 1/φ = φ - 1 -/
theorem φ_reciprocal : 1 / φ = φ - 1 := by
  have h := φ_squared
  field_simp [φ_ne_zero] at h ⊢
  linarith

theorem φ_sum_conjugate : φ + φ_bar = 1 := by
  unfold φ φ_bar
  field_simp
  ring

theorem φ_product_conjugate : φ * φ_bar = -1 := by
  unfold φ φ_bar
  field_simp
  ring
  rw [sq_sqrt (by norm_num : (0 : ℝ) ≤ 5)]
  ring

/-- The primitive 5th root of unity: ζ₅ = exp(2πi/5) -/
def ζ₅ : ℂ := exp (2 * π * I / 5)

theorem ζ₅_pow_five : ζ₅ ^ 5 = 1 := by
  -- By definition of ζ₅, we have ζ₅ = exp(2πi/5).
  have hζ₅_def : ζ₅ = Complex.exp (2 * Real.pi * Complex.I / 5) := by
    -- By definition of ζ₅, we have ζ₅ = Complex.exp (2 * Real.pi * Complex.I / 5).
    rw [show ζ₅ = Complex.exp (2 * Real.pi * Complex.I / 5) from rfl];
  rw [ hζ₅_def, ← Complex.exp_nat_mul, mul_comm ] ; norm_num

theorem ζ₅_norm : ‖ζ₅‖ = 1 := by
  -- The norm of a complex number on the unit circle is 1.
  simp [ζ₅, Complex.norm_exp]

/-- Pentagon vertex k as complex number: ζ₅^k -/
def pentagonVertex (k : Fin 5) : ℂ := ζ₅ ^ (k : ℕ)

theorem pentagonVertex_norm (k : Fin 5) : ‖pentagonVertex k‖ = 1 := by
  -- The norm of a complex exponential is always 1.
  simp [pentagonVertex, Complex.norm_exp];
  -- The norm of ζ₅ is 1 because it lies on the unit circle.
  simp [ζ₅, Complex.norm_exp]

/--
THE GOLDEN GATE: Rotation is multiplication by ζ₅
This trivializes all D₅ equivariance proofs.
-/
theorem rotation_is_multiplication (k : Fin 5) :
    pentagonVertex (k + 1) = ζ₅ * pentagonVertex k := by
      -- By definition of $pentagonVertex$, we have $pentagonVertex (k + 1) = \zeta_5^{k + 1}$ and $pentagonVertex k = \zeta_5^k$.
      have h_pentagonVertex : ∀ k : Fin 5, pentagonVertex k = ζ₅^k.val := by
        -- By definition of $pentagonVertex$, we have $pentagonVertex k = \zeta_5^k$ for any $k$.
        intro k
        simp [pentagonVertex];
      -- By definition of $pentagonVertex$, we have $pentagonVertex (k + 1) = \zeta_5^{k + 1}$ and $pentagonVertex k = \zeta_5^k$. Using the properties of exponents, we can rewrite this as $\zeta_5 * \zeta_5^k$.
      have h_exp : ∀ k : Fin 5, ζ₅ ^ (k + 1).val = ζ₅ * ζ₅ ^ k.val := by
        simp +decide [ ← pow_succ', Fin.val_add ];
        intro k; rw [ ← Nat.mod_add_div ( ( k : ℕ ) + 1 ) 5 ] ; norm_num [ pow_add, pow_mul, ζ₅_pow_five ] ;
      rw [ h_pentagonVertex, h_pentagonVertex, h_exp ]

/-- Convert complex number to ℝ² coordinates -/
def toReal2 (z : ℂ) : EuclideanSpace ℝ (Fin 2) := ![z.re, z.im]

/-- Pentagon vertex in ℝ² -/
def vertex (k : Fin 5) : EuclideanSpace ℝ (Fin 2) :=
  toReal2 (pentagonVertex k)

theorem vertex_norm (k : Fin 5) : ‖vertex k‖ = 1 := by
  -- By definition of vertex, we have vertex k = ζ₅ ^ (k : ℕ).
  simp [vertex];
  -- Since the norm of ζ₅ is 1, raising it to any power k will also result in a complex number with norm 1.
  have h_norm : ‖ζ₅ ^ (k : ℕ)‖ = 1 := by
    -- The norm of a power of a complex number is the power of the norm.
    simp [ζ₅, Complex.norm_exp];
  -- Since the norm of ζ₅ ^ k is 1, we can conclude that the norm of the vector [ζ₅ ^ k, ζ₅ ^ k] is also 1.
  simp [toReal2, h_norm];
  norm_num [ Norm.norm, h_norm ];
  norm_num [ ← Complex.normSq_add_mul_I, Complex.normSq_eq_norm_sq, h_norm ];
  norm_num [ ← Real.sqrt_eq_rpow, h_norm ];
  exact h_norm

/-- Rotation matrix: 72° = 2π/5 radians -/
def R : Matrix (Fin 2) (Fin 2) ℝ :=
  let θ := 2 * Real.pi / 5
  !![Real.cos θ, -Real.sin θ; Real.sin θ, Real.cos θ]

/-- Reflection matrix: flip across x-axis -/
def S : Matrix (Fin 2) (Fin 2) ℝ := !![1, 0; 0, -1]

/-- Orthogonality: M * Mᵀ = I -/
def IsOrthogonal {n : Type*} [Fintype n] [DecidableEq n] (M : Matrix n n ℝ) : Prop :=
  M * M.transpose = 1

theorem R_orthogonal : IsOrthogonal R := by
  ext i j
  fin_cases i <;> fin_cases j <;> 
    simp [R, Matrix.mul_apply, Matrix.transpose, IsOrthogonal] <;>
    ring_nf <;> norm_num [Real.cos_sq_add_sin_sq]

theorem S_orthogonal : IsOrthogonal S := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [S, Matrix.mul_apply, Matrix.transpose, IsOrthogonal]

open Real Complex Finset Matrix
open scoped BigOperators ComplexConjugate

/-- Rotation as linear map -/
def rotate : EuclideanSpace ℝ (Fin 2) →ₗ[ℝ] EuclideanSpace ℝ (Fin 2) :=
  Matrix.toLin' R

/-- Reflection as linear map -/
def reflect : EuclideanSpace ℝ (Fin 2) →ₗ[ℝ] EuclideanSpace ℝ (Fin 2) :=
  Matrix.toLin' S

/-- Pentagon vertices form a set -/
def Pentagon : Set (EuclideanSpace ℝ (Fin 2)) :=
  Set.range vertex

theorem pentagon_rotation_invariant (v : EuclideanSpace ℝ (Fin 2)) :
    v ∈ Pentagon → rotate v ∈ Pentagon := by
      rintro ⟨ k, rfl ⟩;
      -- By definition of $rotate$, we have $rotate (vertex k) = vertex (k + 1)$.
      have h_rotate_vertex : rotate (vertex k) = vertex (k + 1) := by
        -- By definition of $R$, we know that $R * vertex k = vertex (k + 1)$.
        have hR_vertex : R.mulVec (toReal2 (pentagonVertex k)) = toReal2 (pentagonVertex (k + 1)) := by
          unfold pentagonVertex R toReal2; norm_num [ ← List.ofFn_inj ] ; ring;
          norm_num [ Fin.val_add, ζ₅ ] ; ring;
          fin_cases k <;> norm_num [ ← Complex.exp_nat_mul, Complex.exp_re, Complex.exp_im ] <;> ring_nf <;> norm_num;
          · rw [ ← Real.cos_two_mul' ] ; rw [ show Real.pi * ( 4 / 5 ) = 2 * ( Real.pi * ( 2 / 5 ) ) by ring, Real.sin_two_mul ] ; ring;
            norm_num;
          · rw [ show Real.pi * ( 6 / 5 ) = Real.pi * ( 4 / 5 ) + Real.pi * ( 2 / 5 ) by ring, Real.cos_add, Real.sin_add ] ; ring ; norm_num;
          · rw [ ( by ring : Real.pi * ( 8 / 5 ) = Real.pi * ( 6 / 5 ) + Real.pi * ( 2 / 5 ) ), Real.cos_add, Real.sin_add ] ; ring ; norm_num;
          · rw [ show Real.pi * ( 8 / 5 ) = 2 * Real.pi - Real.pi * ( 2 / 5 ) by ring, Real.cos_two_pi_sub, Real.sin_two_pi_sub ] ; ring ; norm_num;
        convert hR_vertex using 1;
      exact h_rotate_vertex.symm ▸ Set.mem_range_self _

theorem pentagon_reflection_invariant (v : EuclideanSpace ℝ (Fin 2)) :
    v ∈ Pentagon → reflect v ∈ Pentagon := by
      unfold Pentagon;
      -- By definition of $vertex$, we know that $vertex k = ζ₅^k$ for some $k$.
      intro hv
      obtain ⟨k, rfl⟩ := hv;
      fin_cases k <;> simp +decide [ vertex ];
      · -- By definition of reflection, we have that reflect (toReal2 (pentagonVertex 0)) = toReal2 (pentagonVertex 0).
        use 0
        simp [toReal2, pentagonVertex, reflect];
        erw [ Matrix.toLin'_apply ] ; norm_num [ S ];
        ext i; fin_cases i <;> rfl;
      · unfold pentagonVertex toReal2 reflect;
        use 4;
        ext i ; fin_cases i <;> norm_num [ ← Complex.exp_nat_mul, Complex.exp_re, Complex.exp_im, ζ₅ ];
        · erw [ Matrix.toLin'_apply ] ; norm_num [ S ];
          rw [ ← Real.cos_two_pi_sub ] ; ring;
        · erw [ Matrix.toLin'_apply ] ; norm_num [ S ];
          rw [ ← Real.sin_two_pi_sub ] ; ring;
      · unfold pentagonVertex;
        unfold ζ₅; norm_num [ ← Complex.exp_nat_mul, mul_div_cancel₀ ] ;
        use 3; norm_num [ Complex.exp_re, Complex.exp_im, toReal2 ] ; ring_nf;
        unfold reflect; norm_num [ show Real.pi * ( 6 / 5 ) = Real.pi + Real.pi / 5 by ring, show Real.pi * ( 4 / 5 ) = Real.pi - Real.pi / 5 by ring, Real.cos_add, Real.sin_add, Real.cos_sub, Real.sin_sub ] ;
        erw [ Matrix.toLin'_apply ] ; norm_num [ S ];
        ext i ; fin_cases i <;> norm_num;
      · -- By definition of conjugate, we know that conjugate(ζ₅^3) = ζ₅^2.
        have h_conj : starRingEnd ℂ (ζ₅ ^ 3) = ζ₅ ^ 2 := by
          unfold ζ₅;
          norm_num [ ← Complex.exp_nat_mul, Complex.ext_iff, Complex.exp_re, Complex.exp_im ];
          norm_num [ ( by ring : 3 * ( 2 * Real.pi / 5 ) = 2 * Real.pi - 2 * ( 2 * Real.pi / 5 ) ), Real.cos_two_mul, Real.sin_two_mul ];
        -- By definition of conjugate, we know that conjugate(ζ₅^3) = ζ₅^2. Therefore, applying the reflection matrix S to pentagonVertex 3 gives us pentagonVertex 2.
        use 2
        simp [h_conj, pentagonVertex];
        -- By definition of conjugate, we know that conjugate(ζ₅^3) = ζ₅^2. Therefore, applying the reflection matrix S to pentagonVertex 3 gives us pentagonVertex 2. Hence, the equality holds.
        have h_reflect : toReal2 (starRingEnd ℂ (ζ₅ ^ 3)) = S.mulVec (toReal2 (ζ₅ ^ 3)) := by
          ext i; fin_cases i <;> norm_num [ Complex.ext_iff, toReal2 ] ;
          · simp +decide [ S, Matrix.mulVec ];
            simp +decide [ pow_succ, Complex.ext_iff ];
            ring;
          · simp_all +decide [ pow_succ, Complex.ext_iff ];
            norm_num [ S ] ; linarith;
        convert h_reflect using 1;
        rw [ h_conj ];
      · use 1; simp +decide [ toReal2, reflect ] ;
        ext i ; fin_cases i <;> norm_num [ S, pentagonVertex ];
        · erw [ Matrix.toLin'_apply ] ; norm_num [ ← Complex.exp_nat_mul, Complex.exp_re, Complex.exp_im ] ; ring ;
          norm_num [ ← Complex.exp_nat_mul, Complex.exp_re, Complex.exp_im, ζ₅ ] ; ring;
          rw [ ← Real.cos_two_pi_sub ] ; ring;
        · erw [ Matrix.toLin'_apply ] ; norm_num [ ← Complex.exp_nat_mul, Complex.exp_re, Complex.exp_im ] ; ring;
          norm_num [ ζ₅, ← Complex.exp_nat_mul, Complex.exp_re, Complex.exp_im ] ; ring;
          rw [ ← Real.sin_two_pi_sub ] ; ring

/-- Shift parameter γ for aperiodicity -/
def γ : Fin 5 → ℝ := fun _ => 1 / (2 * sqrt 5)

/-- 
Parallel projection: π‖ : ℤ⁵ → ℝ² (physical space)
This is where the tiling lives.
-/
def pi_par (n : Fin 5 → ℤ) : EuclideanSpace ℝ (Fin 2) :=
  ∑ k : Fin 5, ((n k : ℝ) + γ k) • vertex k

/--
Perpendicular projection: π⊥ : ℤ⁵ → ℝ² (internal space)  
Used for acceptance window.
-/
def pi_perp (n : Fin 5 → ℤ) : EuclideanSpace ℝ (Fin 2) :=
  ∑ k : Fin 5, ((n k : ℝ) + γ k) • 
    toReal2 (ζ₅ ^ (k : ℕ) * exp (π * I / 5))

/-- Acceptance window: closed ball of radius φ in perpendicular space -/
def Window : Set (EuclideanSpace ℝ (Fin 2)) :=
  Metric.closedBall 0 φ

/--
PENROSE TILING: The cut-and-project construction
Points are π‖(n) where n ∈ ℤ⁵ and π⊥(n) ∈ Window.
-/
def Penrose : Set (EuclideanSpace ℝ (Fin 2)) :=
  {p | ∃ n : Fin 5 → ℤ, p = pi_par n ∧ pi_perp n ∈ Window}

/-- The window is compact (Heine-Borel theorem) -/
theorem window_compact : IsCompact Window := by
  -- The window is a closed ball in ℝ², which is compact by the Heine-Borel theorem.
  apply ProperSpace.isCompact_closedBall

/-- Penrose is nonempty (the origin is in the tiling) -/
theorem penrose_nonempty : Penrose.Nonempty := by
  -- By definition of $Penrose$, we need to show that there exists some $p$ such that $p \in Penrose$.
  unfold Penrose
  simp [pi_par, pi_perp, Window];
  refine' ⟨ _, ⟨ 0, rfl, _ ⟩ ⟩ ; norm_num [ Complex.normSq, Complex.norm_def ];
  refine' le_trans ( norm_sum_le _ _ ) _;
  norm_num [ γ, norm_smul, toReal2 ];
  norm_num [ EuclideanSpace.norm_eq, ζ₅ ];
  norm_num [ ← Complex.exp_nat_mul, Complex.exp_re, Complex.exp_im ] ; ring_nf ; norm_num [ mul_div ];
  norm_num [ Real.sin_sq, Real.cos_sq ] ; ring_nf ; norm_num [ abs_of_pos ];
  rw [ show φ = ( 1 + Real.sqrt 5 ) / 2 by rfl ] ; nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ), inv_mul_cancel₀ ( ne_of_gt ( Real.sqrt_pos.mpr ( show 0 < 5 by norm_num ) ) ) ]

/-- Element of the Penrose tiling -/
abbrev PenrosePoint := Penrose.Elem

/-- 
Adjacency relation (defined abstractly)
In a full implementation, this would compute actual distances.
For this foundational formalization, we declare the existence of the relation.
-/
def adjacent (p q : PenrosePoint) : Prop := dist p.val q.val = 1

/-- Adjacency is symmetric -/
theorem adjacent_symm (p q : PenrosePoint) : adjacent p q → adjacent q p := by
  intro h
  rw [adjacent, dist_comm]
  exact h

/--
Neighbors as abstract set (finite by Delone property)
In full implementation, would be computed from adjacency relation.
-/
def neighbors_set (p : PenrosePoint) : Set PenrosePoint := {q | adjacent p q}

theorem neighbors_adjacent (p q : PenrosePoint) : q ∈ neighbors_set p ↔ adjacent p q := by
  rfl

/-- Class capturing the spectral axioms required for the Penrose tiling -/
class PenroseSpectralAxioms where
  neighbors_finite : ∀ p : PenrosePoint, (neighbors_set p).Finite
  degree_bounded : ∃ D : ℕ, ∀ p : PenrosePoint, ((neighbors_finite p).toFinset).card ≤ D

/-- Convert neighbor set to finset -/
def neighbors [PenroseSpectralAxioms] (p : PenrosePoint) : Finset PenrosePoint :=
  (PenroseSpectralAxioms.neighbors_finite p).toFinset

/-- Degree of a vertex -/
def degree [PenroseSpectralAxioms] (p : PenrosePoint) : ℕ := (neighbors p).card

/-- The ℓ² space over Penrose vertices -/
def L2Penrose := {f : PenrosePoint → ℝ // Summable (fun p => (f p) ^ 2)}

/-- Graph Laplacian: Δf(p) = deg(p)·f(p) - ∑_{q~p} f(q) -/
def Δ [PenroseSpectralAxioms] (f : PenrosePoint → ℝ) (p : PenrosePoint) : ℝ :=
  (degree p : ℝ) * f p - ∑ q ∈ neighbors p, f q

theorem sum_neighbors_in_L2 [PenroseSpectralAxioms] (f : L2Penrose) :
  Summable (fun p => (∑ q ∈ neighbors p, f.val q)^2) := by
  obtain ⟨D, hD⟩ := PenroseSpectralAxioms.degree_bounded
  -- Since $f \in \ell^2$, we have $\sum_p f(p)^2 < \infty$.
  have h_sum_f_sq : Summable (fun p => (f.val p) ^ 2) := by
    exact f.2;
  -- By the Cauchy-Schwarz inequality, we have $(\sum_{q \in N(p)} f(q))^2 \leq |N(p)| \sum_{q \in N(p)} f(q)^2$.
  have h_cauchy_schwarz : ∀ p : PenrosePoint, (∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q)) ^ 2 ≤ (D : ℝ) * ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2 := by
    intro p
    have h_cauchy_schwarz_step : (∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q)) ^ 2 ≤ ((‹PenroseSpectralAxioms›.neighbors_finite p).toFinset.card : ℝ) * ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2 := by
      exact?
    generalize_proofs at *;
    exact h_cauchy_schwarz_step.trans ( mul_le_mul_of_nonneg_right ( mod_cast hD p ) ( Finset.sum_nonneg fun _ _ => sq_nonneg _ ) );
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : Summable (fun p => ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2) := by
    refine' summable_of_sum_le _ _;
    exact ∑' p : PenrosePoint, ( f.val p ) ^ 2 * D;
    · exact fun p => Finset.sum_nonneg fun _ _ => sq_nonneg _;
    · intro u
      have h_sum_le : ∑ x ∈ u, ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite x).toFinset, (f.val q) ^ 2 ≤ ∑ q ∈ Finset.biUnion u (fun p => (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset), (f.val q) ^ 2 * D := by
        have h_sum_le : ∀ q ∈ Finset.biUnion u (fun p => (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset), ∑ x ∈ u, (if q ∈ (‹PenroseSpectralAxioms›.neighbors_finite x).toFinset then (f.val q) ^ 2 else 0) ≤ (f.val q) ^ 2 * D := by
          simp +contextual [ Finset.sum_ite ];
          intro a ha x hx hxu hx'; rw [ mul_comm ] ; gcongr;
          refine' le_trans _ ( hD ⟨ a, ha ⟩ );
          refine' Finset.card_le_card _;
          simp +contextual [ Finset.subset_iff, neighbors_set ];
          exact?;
        refine' le_trans _ ( Finset.sum_le_sum h_sum_le );
        rw [ Finset.sum_comm ];
        exact Finset.sum_le_sum fun p hp => by rw [ ← Finset.sum_filter ] ; exact Finset.sum_le_sum_of_subset_of_nonneg ( fun q hq => by aesop ) fun _ _ _ => sq_nonneg _;
      exact h_sum_le.trans ( Summable.sum_le_tsum _ ( fun _ _ => mul_nonneg ( sq_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( h_sum_f_sq.mul_right _ ) );
  exact Summable.of_nonneg_of_le ( fun p => sq_nonneg _ ) ( fun p => h_cauchy_schwarz p ) ( h_fubini.mul_left _ )

theorem sum_neighbors_eq_sum_degree_ennreal [PenroseSpectralAxioms] (g : PenrosePoint → ENNReal) :
  (∑' p, ∑ q ∈ neighbors p, g q) = ∑' q, (degree q) * g q := by
    have h_fubini : ∀ {f : PenrosePoint → PenrosePoint → ENNReal}, (∀ p, Summable (fun q => f p q)) → (∀ q, Summable (fun p => f p q)) → (∑' p, ∑' q, f p q) = (∑' q, ∑' p, f p q) := by
      exact?;
    convert h_fubini _ _ using 3;
    rotate_left;
    rotate_left;
    use fun p q => if q ∈ neighbors_set p then g q else 0;
    · exact?;
    · exact?;
    · rw [ tsum_eq_sum ];
      congr! 1;
      · rw [ if_pos ];
        exact Set.Finite.mem_toFinset _ |>.1 ‹_›;
      · -- By definition of neighbors_set, if b is not in the neighbors of x, then b is not adjacent to x.
        intro b hb
        simp [neighbors_set, adjacent] at hb;
        exact if_neg fun h => hb <| by simpa [ neighbors ] using h;
    · rename_i p;
      rw [ tsum_eq_sum ];
      any_goals exact ‹PenroseSpectralAxioms›.neighbors_finite p |> Set.Finite.toFinset;
      · simp +decide [ Finset.sum_ite, degree ];
        congr! 2;
        congr! 1;
        ext q; simp [neighbors, neighbors_set];
        exact?;
      · simp +contextual [ neighbors_set ];
        exact fun a ha h₁ h₂ => False.elim <| h₁ <| adjacent_symm _ _ h₂

theorem sum_neighbors_eq_tsum_ite [PenroseSpectralAxioms] (p : PenrosePoint) (g : PenrosePoint → ENNReal) :
  (∑ q ∈ neighbors p, g q) = ∑' q, if adjacent p q then g q else 0 := by
    rw [ tsum_eq_sum ];
    congr! 1;
    · -- Since x is in the neighbors of p, by definition, adjacent p x must hold.
      have h_adj : adjacent p ‹_› := by
        unfold neighbors at *; aesop;
      rw [ if_pos h_adj ];
    · -- By definition of neighbors, if b is not in the neighbors of p, then adjacent p b is false.
      intro b hb
      simp [neighbors, neighbors_set] at hb;
      -- Since `adjacent p b` is false, the if statement simplifies to 0.
      simp [hb]

theorem Δ_maps_L2 [PenroseSpectralAxioms] (f : L2Penrose) : Summable (fun p => (Δ f.val p) ^ 2) := by
  revert f;
  have := @sum_neighbors_in_L2;
  intro f;
  have := f.2;
  -- By the properties of summability, if the sum of squares of two sequences is summable, then the sum of squares of their linear combinations is also summable.
  have h_summable_linear_combination : ∀ (a b : PenrosePoint → ℝ), Summable (fun p => a p ^ 2) → Summable (fun p => b p ^ 2) → Summable (fun p => (a p - b p) ^ 2) := by
    intro a b ha hb;
    have h_summable_linear_combination : Summable (fun p => a p ^ 2 + b p ^ 2) := by
      exact ha.add hb;
    refine' .of_nonneg_of_le ( fun p => sq_nonneg _ ) ( fun p => _ ) ( h_summable_linear_combination.mul_left 2 );
    linarith [ sq_nonneg ( a p + b p ) ];
  apply h_summable_linear_combination;
  · obtain ⟨ D, hD ⟩ := ‹PenroseSpectralAxioms›.degree_bounded;
    exact Summable.of_nonneg_of_le ( fun p => sq_nonneg _ ) ( fun p => by simpa [ mul_pow ] using mul_le_mul_of_nonneg_right ( pow_le_pow_left₀ ( Nat.cast_nonneg _ ) ( Nat.cast_le.mpr ( hD p ) ) 2 ) ( sq_nonneg _ ) ) ( this.mul_left _ );
  · aesop

lemma sum_sq_neighbors_le [PenroseSpectralAxioms] (f : PenrosePoint → ℝ) (p : PenrosePoint) :
  (∑ q ∈ neighbors p, f q)^2 ≤ (degree p : ℝ) * ∑ q ∈ neighbors p, (f q)^2 := by
    have h_cauchy_schwarz : ∀ (S : Finset PenrosePoint) (f : PenrosePoint → ℝ), (∑ q ∈ S, f q) ^ 2 ≤ (S.card : ℝ) * ∑ q ∈ S, f q ^ 2 := by
      exact?;
    -- Apply the Cauchy-Schwarz inequality to the sum over the finite set `neighbors p`.
    apply h_cauchy_schwarz

lemma sum_sq_neighbors_le_aux [PenroseSpectralAxioms] (f : PenrosePoint → ℝ) (p : PenrosePoint) :
  (∑ q ∈ neighbors p, f q)^2 ≤ (degree p : ℝ) * ∑ q ∈ neighbors p, (f q)^2 := by
    -- By the Cauchy-Schwarz inequality, we have that for any finite set of real numbers, the square of their sum is less than or equal to the product of the number of elements and the sum of their squares.
    have h_cauchy_schwarz : ∀ (s : Finset PenrosePoint), (∑ q ∈ s, f q)^2 ≤ (s.card : ℝ) * ∑ q ∈ s, (f q)^2 := by
      exact?;
    -- Apply the Cauchy-Schwarz inequality to the set of neighbors.
    apply h_cauchy_schwarz

lemma sum_sq_neighbors_le_v2 [PenroseSpectralAxioms] (f : PenrosePoint → ℝ) (p : PenrosePoint) :
  (∑ q ∈ neighbors p, f q)^2 ≤ (degree p : ℝ) * ∑ q ∈ neighbors p, (f q)^2 := by
    -- By the Cauchy-Schwarz inequality, we have that for any vectors $u$ and $v$ of equal length, $(u \cdot v)^2 \leq \|u\|^2 \|v\|^2$.
    have h_cauchy_schwarz : ∀ (u v : Finset PenrosePoint), (∑ q ∈ u, f q) ^ 2 ≤ (Finset.card u : ℝ) * ∑ q ∈ u, f q ^ 2 := by
      exact?;
    exact h_cauchy_schwarz _ ∅

lemma sum_sq_le_card_mul_sum_sq_real {α : Type*} (s : Finset α) (f : α → ℝ) :
  (∑ x ∈ s, f x)^2 ≤ (s.card : ℝ) * ∑ x ∈ s, (f x)^2 := by
    exact?

lemma summable_degree_mul_sq [PenroseSpectralAxioms] (f : L2Penrose) :
  Summable (fun p => ((degree p : ℝ) * f.val p)^2) := by
    have h_summable : Summable (fun p => (f.val p) ^ 2) := by
      exact f.2;
    obtain ⟨ D, hD ⟩ := ‹PenroseSpectralAxioms›.degree_bounded;
    have h_summable : Summable (fun p => (D : ℝ) ^ 2 * (f.val p) ^ 2) := by
      exact h_summable.mul_left _;
    refine' .of_nonneg_of_le ( fun p => sq_nonneg _ ) ( fun p => _ ) h_summable;
    rw [ mul_pow ];
    gcongr;
    exact hD p

lemma summable_degree_mul_sq_aux [PenroseSpectralAxioms] (f : L2Penrose) :
  Summable (fun p => ((degree p : ℝ) * f.val p)^2) := by
    field_simp;
    obtain ⟨ D, hD ⟩ := ‹PenroseSpectralAxioms›.degree_bounded;
    -- Since the degree is bounded by D, we can use the fact that the sum of (f(p))^2 is summable to show that the sum of (D * f(p))^2 is also summable.
    have h_summable : Summable (fun p => (D * f.val p)^2) := by
      convert f.2.mul_left ( D ^ 2 : ℝ ) using 2 ; ring;
    refine' .of_nonneg_of_le ( fun p => by positivity ) ( fun p => _ ) h_summable;
    rw [ mul_pow ] ; gcongr ; aesop

/--
Inner product on ℓ²(Penrose)
In full formalization, would prove this converges.
-/
def L2_inner (f g : L2Penrose) : ℝ := ∑' p, f.val p * g.val p

theorem L2_inner_converges (f g : L2Penrose) : Summable (fun p => f.val p * g.val p) := by
  -- By the Cauchy-Schwarz inequality, if $f$ and $g$ are in $L^2$ (i.e., their squares are summable), then their product is in $L^1$ (i.e., the sum of their products is summable).
  have h_cauchy_schwarz : Summable (fun p => (f.val p)^2) → Summable (fun p => (g.val p)^2) → Summable (fun p => f.val p * g.val p) := by
    intro hf hg;
    -- By the Cauchy-Schwarz inequality, we have |f(p)g(p)| ≤ (f(p)^2 + g(p)^2)/2.
    have h_cauchy_schwarz : ∀ p : PenrosePoint, abs ((f.val p) * (g.val p)) ≤ (f.val p)^2 / 2 + (g.val p)^2 / 2 := by
      exact fun p => abs_le.mpr ⟨ by linarith [ sq_nonneg ( f.val p - g.val p ), sq_nonneg ( f.val p + g.val p ) ], by linarith [ sq_nonneg ( f.val p - g.val p ), sq_nonneg ( f.val p + g.val p ) ] ⟩;
    -- Since the absolute value of the product is bounded by a summable series, we can apply the comparison test.
    have h_comparison : Summable (fun p : PenrosePoint => abs ((f.val p) * (g.val p))) := by
      exact Summable.of_nonneg_of_le ( fun p => abs_nonneg _ ) ( fun p => h_cauchy_schwarz p ) ( Summable.add ( hf.div_const 2 ) ( hg.div_const 2 ) );
    exact h_comparison.of_abs;
  exact h_cauchy_schwarz f.2 g.2

theorem L2_inner_symm (f g : L2Penrose) : L2_inner f g = L2_inner g f := by
  unfold L2_inner;
  ac_rfl

theorem L2_inner_pos (f : L2Penrose) : 0 ≤ L2_inner f f := by
  exact tsum_nonneg fun _ => by exact mul_self_nonneg _;

lemma sum_sq_le_card_mul_sum_sq_real_v2 {α : Type*} (s : Finset α) (f : α → ℝ) :
  (∑ x ∈ s, f x)^2 ≤ (s.card : ℝ) * ∑ x ∈ s, (f x)^2 := by
  have h := Finset.sum_mul_sq_le_sq_mul_sq s (fun _ => 1) f
  simp only [one_mul, one_pow, Finset.sum_const, nsmul_eq_mul, mul_one] at h
  exact h

lemma sum_sq_le_card_mul_sum_sq_real_v3 {α : Type*} (s : Finset α) (f : α → ℝ) :
  (∑ x ∈ s, f x)^2 ≤ (s.card : ℝ) * ∑ x ∈ s, (f x)^2 := by
  have h := Finset.sum_mul_sq_le_sq_mul_sq s (fun _ => 1) f
  simp only [one_mul, one_pow, Finset.sum_const, nsmul_eq_mul, mul_one] at h
  exact h

lemma sum_sq_le_card_mul_sum_sq_generic {α : Type*} (s : Finset α) (f : α → ℝ) :
  (∑ x ∈ s, f x)^2 ≤ (s.card : ℝ) * ∑ x ∈ s, (f x)^2 := by
    exact?

/-- The Laplacian as an operator on L2Penrose -/
def Δ_L2 [PenroseSpectralAxioms] (f : L2Penrose) : L2Penrose := ⟨Δ f.val, Δ_maps_L2 f⟩

#check Δ_maps_L2
#check sum_neighbors_in_L2

#check Δ_maps_L2
#check Δ_L2

theorem sum_neighbors_rearrange_ennreal_v2 [PenroseSpectralAxioms] (g : PenrosePoint → ENNReal) : 
  (∑' p, ∑ q ∈ neighbors p, g q) = ∑' q, (degree q) * g q := by
  -- Convert inner sum to tsum
  have h1 : (∑' p, ∑ q ∈ neighbors p, g q) = ∑' p, ∑' q, if adjacent p q then g q else 0 := by
    congr; ext p
    rw [sum_neighbors_eq_tsum_ite]
  rw [h1]
  -- Swap sums
  rw [ENNReal.tsum_comm]
  -- Analyze the new inner sum
  congr; ext q
  -- Use symmetry
  have h_symm : ∀ p, adjacent p q ↔ adjacent q p := fun p => ⟨adjacent_symm p q, adjacent_symm q p⟩
  simp_rw [h_symm]
  -- Factor out g q
  have h_factor : ∀ p, (if adjacent q p then g q else 0) = (if adjacent q p then 1 else 0) * g q := by
    intro p; split_ifs <;> simp
  simp_rw [h_factor]
  rw [ENNReal.tsum_mul_right]
  congr
  -- Identify the sum of indicators as the degree
  rw [← sum_neighbors_eq_tsum_ite]
  simp only [Finset.sum_const, nsmul_eq_mul, mul_one]
  rfl

#check sum_neighbors_in_L2
#check Δ_maps_L2

theorem sum_neighbors_rearrange_ennreal_v3 [PenroseSpectralAxioms] (g : PenrosePoint → ENNReal) : 
  (∑' p, ∑ q ∈ neighbors p, g q) = ∑' q, (degree q) * g q := by
  -- Convert inner sum to tsum
  have h1 : (∑' p, ∑ q ∈ neighbors p, g q) = ∑' p, ∑' q, if adjacent p q then g q else 0 := by
    congr; ext p
    rw [sum_neighbors_eq_tsum_ite]
  rw [h1]
  -- Swap sums
  rw [ENNReal.tsum_comm]
  -- Analyze the new inner sum
  congr; ext q
  -- Use symmetry
  have h_symm : ∀ p, adjacent p q ↔ adjacent q p := fun p => ⟨adjacent_symm p q, adjacent_symm q p⟩
  simp_rw [h_symm]
  -- Factor out g q
  have h_factor : ∀ p, (if adjacent q p then g q else 0) = (if adjacent q p then 1 else 0) * g q := by
    intro p; split_ifs <;> simp
  simp_rw [h_factor]
  rw [ENNReal.tsum_mul_right]
  congr
  -- Identify the sum of indicators as the degree
  rw [← sum_neighbors_eq_tsum_ite]
  simp only [Finset.sum_const, nsmul_eq_mul, mul_one]
  rfl

lemma summable_sum_sq_neighbors [PenroseSpectralAxioms] (f : L2Penrose) :
  Summable (fun p => ∑ q ∈ neighbors p, (f.val q)^2) := by
    refine' summable_of_sum_le _ _;
    exact ∑' p, ( f.val p ) ^ 2 * ( ‹PenroseSpectralAxioms›.neighbors_finite p ).toFinset.card;
    · exact fun p => Finset.sum_nonneg fun _ _ => sq_nonneg _;
    · -- Since the degree of each vertex is bounded by D, we can factor out D from the sum.
      have h_deg_bound : ∀ p : PenrosePoint, (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset.card ≤ (‹PenroseSpectralAxioms›.degree_bounded.choose : ℕ) := by
        exact fun p => by simpa using ‹PenroseSpectralAxioms›.degree_bounded.choose_spec p;
      intro u;
      refine' le_trans _ ( Summable.sum_le_tsum _ _ _ );
      rotate_left;
      exact Finset.biUnion u fun p => ( ‹PenroseSpectralAxioms›.neighbors_finite p ).toFinset;
      · exact fun _ _ => by positivity;
      · refine' Summable.of_nonneg_of_le ( fun p => mul_nonneg ( sq_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( fun p => mul_le_mul_of_nonneg_left ( Nat.cast_le.mpr ( h_deg_bound p ) ) ( sq_nonneg _ ) ) _;
        exact Summable.mul_right _ ( f.2 );
      · -- By Fubini's theorem, we can interchange the order of summation.
        have h_fubini : ∑ p ∈ u, ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2 = ∑ q ∈ Finset.biUnion u (fun p => (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset), (f.val q) ^ 2 * (∑ p ∈ u, if q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset then 1 else 0) := by
          simp +decide only [Finset.mul_sum _ _ _, mul_boole];
          -- By Fubini's theorem, we can interchange the order of summation. The left-hand side sums over u first, then over the neighbors of each p in u. The right-hand side sums over the union of all neighbors of p in u, then over u. Since the neighbors of p in u are exactly the elements in the union, the two sums are equal.
          have h_fubini : ∀ p ∈ u, ∑ q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset, (f.val q) ^ 2 = ∑ q ∈ Finset.biUnion u (fun p => (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset), if q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset then (f.val q) ^ 2 else 0 := by
            intro p hp; rw [ ← Finset.sum_filter ] ; congr; ext q; aesop;
          rw [ Finset.sum_congr rfl h_fubini, Finset.sum_comm ];
        convert h_fubini.le.trans _;
        -- Since the sum over p in u of if q is in the neighbors of p then 1 else 0 is equal to the cardinality of the neighbors of q, we can replace the sum with the cardinality.
        have h_card : ∀ q ∈ Finset.biUnion u (fun p => (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset), (∑ p ∈ u, if q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset then 1 else 0) ≤ (‹PenroseSpectralAxioms›.neighbors_finite q).toFinset.card := by
          intros q hq
          have h_card : (∑ p ∈ u, if q ∈ (‹PenroseSpectralAxioms›.neighbors_finite p).toFinset then 1 else 0) ≤ (‹PenroseSpectralAxioms›.neighbors_finite q).toFinset.card := by
            simp +zetaDelta at *;
            refine' Finset.card_le_card _;
            simp +decide [ Finset.subset_iff, neighbors_set ];
            exact?;
          convert h_card using 1;
        exact Finset.sum_le_sum fun q hq => mul_le_mul_of_nonneg_left ( mod_cast h_card q hq ) ( sq_nonneg _ )
